### ISSUE TITLE
Running DappNode behind a router

### ISSUE THREAD

**Issue by sponnet** [dappnode/DAppNode#10]
It would be nice to have a separate section in the installation manual for installing dappnode behind a NAT firewall. Topics might include

- firewall configuration ( ports to open for VPN access )
- dynamic DNS configuration 

I could work on that when I have my node fully up and running since that is my configuration.

**Comment by eduadiez** [comment]
Yes, I totally agree. 
Your help is greatly appreciated

**Comment by sponnet** [comment]
Also the VPN configuration is different when you connect from behing your firewall ( uses DHCP IP from your router ) - so being able to download 2 VPN configurations ( one for internal use - one for external use ) could be useful too...

**Comment by sponnet** [comment]
Where is the script located in the repo that writes out the `motd` like message ( including the QR code ) when you start up the dappnode OS ?

**Comment by eduadiez** [comment]
We've added UPnP functionality to the VPN: https://github.com/dappnode/DNP_VPN/pull/26

> Where is the script located in the repo that writes out the motd like message ( including the QR code ) when you start up the dappnode OS ? @eduadiez

it is a VPN script, which is added to the profile of the user: https://github.com/dappnode/DNP_VPN/blob/master/build/src/getAdminCredentials.js

```
echo "docker exec DAppNodeCore-vpn.dnp.dappnode.eth node getAdminCredentials" >> ${DAPPNODE_CORE_DIR}scripts/.dappnode_profile
```
