### ISSUE TITLE
Broken Links on Documentation Site

### ISSUE THREAD

**Issue by jeremybeal11** [dappnode/DAppNode#104]
When going through the [documentation](https://dappnode.github.io/DAppNodeDocs/), I have noticed a couple of broken links that are referencing to internal pages(FAQ,Install,etc) 
-  [What can you do with DAppNode?. ](https://dappnode.github.io/what-can-you-do)
-  [introduction](https://dappnode.github.io/introduction)
-  [install](https://dappnode.github.io/install)
-  etc

I have noticed the links on the page are missing the **DAppNodeDocs** in the url path.

**Comment by eduadiez** [comment]
Thanks @jeremybeal11! @Shelpin, please review this

**Comment by jeremybeal11** [comment]
Anytime, glad to help!

**Comment by dapplion** [comment]
Thanks for reporting! <3 Fixed with https://github.com/dappnode/DAppNodeDocs/commit/712ac1f986a787dc32a75851fa5bf48807e661ec
