### ISSUE TITLE
Broken image in User Guide 

### ISSUE THREAD

**Issue by jeremybeal11** [dappnode/DAppNode#105]
In the [User Guide Documentation](https://dappnode.github.io/DAppNodeDocs/user-guide/), all of the images won't render. Tested in safari and chrome, still having the same result.  

Just a heads up.  If I find any more bugs I will keep you posted.

**Comment by dapplion** [comment]
Thank you for reporting! Fixed with https://github.com/dappnode/DAppNodeDocs/commit/4eae25ae1c1452cf9ee6fa503ebe78c2cd4e7f4e
