### ISSUE TITLE
Add `devices` field in the manifest

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#106]
Transparent option in the image object just like the docker-compose reference
https://docs.docker.com/compose/compose-file/#devices

**Comment by Shelpin** [comment]
How can i test this one? :( thanks!

**Comment by dapplion** [comment]
Checked! Used a modified manifest ` /ipfs/QmQ9cECwZWBvokB6KXdvYGUdmsexTUAAoWCwbbnPaDFvrh` and check that the docker-compose.yml changed accordingly
