### ISSUE TITLE
Display network usage in the ADMIN UI (dashboard)

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DAppNode#108]
A user has paid more than regularly for network consumption of the dappnode and he suggests that it would be useful to have the info on the consumption in the UI.

**Comment by dapplion** [comment]
@vdo if you can please add a command example and I'll implement it

**Comment by vdo** [comment]
A command to get stats of all running conatiners would be:

    docker stats  --no-stream --format "{{.NetIO}}"
