### ISSUE TITLE
VPN / identity migration to DM + testing

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#113]
## Summarized changelog
- Move functionality from VPN to DAPPMANAGER:
  - DynDNS code (responsible for):
    - Creating a keypair (the current DN identity) to sign IP updates
    - Doing checks to know internal IP if nat loopback is ok, etc
    - Every interval checks if the IP changes and does a DynDNS update
  - Static IP code (responsible for):
    - Loading a static IP set during an ISO installation
    - Backend for the UI so the user can change the static IP afterward
  - Read hostname code (responsible for):
    - Reading the hostname file mounted on a volume and provide this info to other components
- Split the DAPPMANAGER DB into a "main" (permanent data) and a "cache" (disposable data)
- Add global ENVs functionality by adding a custom .env files to all DNPs that request it and the VPN
- Re-organized the /system tab in the ADMIN.
- Added /system/identity view in the ADMIN so a user can introduce their ether.card identity. The DAPPMANAGER will just store it for now, no action.

## To test
- [ ] Make sure that the .env file is properly loaded into the VPN docker-compose.yml and all docker-compose command succeed
  - [ ] From an ISO installation
  - [x] From an update
  - [x] From dev commands run from the host
- [ ] Make sure the VPN db is properly migrated
  - [x] The DynDNS identity should be the same
  - [x] The static IP if set should be the same
- [x] Make sure the DAPPMANAGER DB split is the properly migrated
  - [x] The auto-update settings, if set, should the same
- [x] Make sure the re-organized /system tab in the ADMIN doesn't break any funcionality.
- [x] Enter an ethercard mnemonic words in /system/identity (one can be generated here https://iancoleman.io/bip39/), make sure the correct address is returned by the DAPPMANGER after refreshing the admin.

Proposed test routine for the migration:
1. Install DAppNode to the current ISO or script versions
2. Activate auto-updates for some packages
3. Write down the current DAppNode identity (1263175412.dyndns...)
4. Set the static IP to the current IP of the system (even if it's not actually static)
5. Update using the command to the test versions, and make sure all versions are correct in the ADMIN UI
6. Check that the auto-updates are set, DAppNode identity is the same and the static IP is set.

Repos and branches with the changes to test:
- ADMIN: [v0.2.9](https://github.com/dappnode/DNP_ADMIN/tree/v0.2.9)
- DAPPMANAGER: [v0.2.15](https://github.com/dappnode/DNP_DAPPMANAGER/tree/v0.2.15) <= Version has changed!
- VPN: [v0.2.2](https://github.com/dappnode/DNP_VPN/tree/v0.2.2)

**Comment by Shelpin** [comment]
Hi !!! I installed the test branches with the restore command + env vars for admin, DM and VPN but the configuration of autoupdates has changed (before installing the branches i had system packages off and packages update on ( lightning on and bitcoin off)and after installing the last versions both were switched off. 


<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21328788/66704027-d7fa1680-ed18-11e9-90ec-5af730a5550f.png">

The static ip was correctly held and also when disabling it the dyndns was the same as before. Words were correctly input in identity and the correct address shown in the admin. 

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/21328788/66704222-307de380-ed1a-11e9-866b-12e8a28f4d52.png">


However when using the peer connect link provided by Lion ```http://my.dappnode/#/system/peers/%2Fip4%2F206.189.107.149%2Ftcp%2F4001%2Fipfs%2FQmWceYKRW7z1BXjCvmqb2VXyhCs1eXqcXBkwKbx1qqtj79```

I got this error screen saying that the package peers is not installed. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/21328788/66704157-e563d080-ed19-11e9-8a33-eab994548d8a.png">

These are the versions I had before doing a script restore before installing the test branches, and the following screen are the versions installed by the script 

```sudo wget -O - https://installer.dappnode.io | sudo  VPN_VERSION=dev:v0.2.2 DAPPMANAGER_VERSION=dev:v0.2.14 ADMIN_VERSION=dev:v0.2.9 UPDATE=true bash```

Starting point

![telegram-cloud-photo-size-4-5841323224309281203-y](https://user-images.githubusercontent.com/21328788/66704301-cca7ea80-ed1a-11e9-8054-a871a44fbf43.jpg)


then I installed the test branches and ended up here 

<img width="724" alt="image" src="https://user-images.githubusercontent.com/21328788/66704306-dc273380-ed1a-11e9-942f-19d42a3fce02.png">

Now i will restore again to the restore script versions and repeat the test but updating to the current versions before installing the test branches. In this described attempt I got this update warning after restoring but executed the installation of the test branches without updating. Now i will update before installing the test branches, and let you know in another comment if there is any different behaviour. 

![image](https://user-images.githubusercontent.com/21328788/66704362-869f5680-ed1b-11e9-91a6-cb309849be2c.png)

**Comment by Shelpin** [comment]
Ii just repeated the test installing the test branches after restoring and updating through the admin UI, the behauviour  has been exactly tthe same as described above. Autoupdates config is not being kept, also I had the flag no ancient blocks in parity before installing the new versioins and it got erased and substituted by warp barrier that i had previously deleted when i set no ancient blocks

**Comment by Shelpin** [comment]
Just repeated this set of tests with @dapplion , and he found that the autoupdates config was deleted because of the restore command i was using  

```
sudo wget -O - https://installer.dappnode.io | sudo VPN_VERSION=dev:v0.2.2 DAPPMANAGER_VERSION=dev:v0.2.14 ADMIN_VERSION=dev:v0.2.9 UPDATE=true bash
```


I repeated the test with this command he prepared and the autoupdate config was held after the restore 

```
sudo wget -O - https://raw.githubusercontent.com/dappnode/DAppNode_Installer/better_update/build/dappnode/scripts/dappnode_install.sh | sudo VPN_VERSION=dev:v0.2.2 DAPPMANAGER_VERSION=dev:v0.2.14 ADMIN_VERSION=dev:v0.2.9 UPDATE=true bash
```
As per the tickboxes , I still need to check this  branches via a regular update and a ISO  installation

The features described are fine , I still need checking these branches via ISO installation and admin update when it is possible to do them

**Comment by dapplion** [comment]
New install link with rebased DAPPMANAGER at `v0.2.15`

http://my.dappnode/#/installer/%2Fipfs%2FQmVunC3uGaV7nTZpyL8k3qe1S8sKa6abZuRjp43eS82t7L

**Comment by dapplion** [comment]
Successful release
