### ISSUE TITLE
Setup wizard - Testing

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#115]
## Summarized changelog

- Refactored UX for installing and configuring a new DNP. Developers can add a JSON schema specifying
- Push for covering more codebase with typescript
  - Strongly type RPC endpoints and pubsub interactions in WAMP. Also, validate data structures in runtime with JSON schemas. This ensures compatibility between both DNPs and reduces the possibility of bugs in production.
  - Started the typescript migration in the ADMIN UI
- Serve avatars directly from the DAppNode's IPFS node and take advantage of the browser's cache
- Prevent double installs on the server-side
- Move logic to parse special permissions and categories from the client to the server

## To test

- [x] Install DNPs with setup wizard and make sure all the settings were correctly set
Semi-mock DNPs with placeholder setup wizards to test
```
Trustls: /ipfs/QmaoCZkST5pHfbjVx5yR5bJyhXSrNrdmYNhkND1LCimii8 (Nov 18 2019 17:10:26)
Vipnode: /ipfs/Qma1QtWnSDdVTcjtFHVB68mKPWnirCfLFun17byJsSuW8B (Nov 18 2019 17:22:59)
Raiden : /ipfs/Qme5ABrtGLKXhEWAWAEfKQGVAqAquB3YAZmGfnmnDbFxFE (Nov 18 2019 17:15:16)
```
- [ ] General test to make sure DAPPMANAGER <-> ADMIN functionality is stable

Repos and branches with changes to test:
- `dappmanager` `:` [`setup_wizard`](https://github.com/dappnode/DNP_DAPPMANAGER/pull/292) `34b990`
- `admin` `:` [`setup_wizard`](https://github.com/dappnode/DNP_ADMIN/pull/380) `010c7f`

## Demo

![trustlines setup](https://user-images.githubusercontent.com/35266934/68964051-b3da9b00-07d8-11ea-9890-49cc1a51267f.png)

**Comment by Shelpin** [comment]
Hi!!! some feedback testing these branches. In this doc all the comments with screenshots. 

https://docs.google.com/document/d/12nbQga3UTBg1GSp3uuLlqr16MFSwLrpJgvj3d3JYDYY/edit?usp=sharing

When trying to install Trustlines as observer there are fields that are not supposed to be filled according to the instructions that appear as compulsory



Passwords are not hidden when including them in the wizard


The installation of trust lines as a participant was correct but I could not try as a validator.

Raiden installation was smooth through the wizard. 

VIPNODE keeps in “restarting” and throwing an error in the logs but I am sure this has not to do with the wizard. 








I fact after reinstalling it the logs where the same but the previous label “restarting” was showing “running”

This is not new but as I mentioned for the trustlines wizard it applies for the whole UI. IMHO none of the fields where passwords are entered or shown after the installation should be just shown…. Better to be hidden by default and shown when clicking the typical “eye button”




Port forwarding seems to not be working. I am trying to forward 8081 to 5001 the usual test I made to test this feature but I can’t access http://ipfs.dappode:8081/webui after updating the port mappings 







When trying to set a custom path for the Monero package it throws a weird error



Also with zcash





I am not able to install Raiden with the wizard, even though i have no ancient blocks activated the package is not starting, in a normal installation with no ancient blocks logs would start to run and an error about NAB would appear. Now it justs get stuck ….








With the Raiden testnet package in the installer it is also not getting the keystore file




I added a device and all the rest disappeared from the UI



When trying to grant admin permissions.




And when trying to get the link the device is not found



Only after a hard reload I could see my devices again in the UI, get the link of the newly added device and connect through it.

However with the mobile, it seems that new versions of Ios have changed the way you download the files, normally when you hit the download button, OpenVPN opened the file and you were connected, now it first asks to download the file and then it does nothing. 


User needs to go to files and double click on the file for OpenVPN to open it.

**Comment by dapplion** [comment]
1.
> When trying to install Trustlines as observer there are fields that are not supposed to be filled according to the instructions that appear as compulsory

Seems that the `react-jsonschema-form` component if a field is not required but it has a pattern, it requires de pattern to be correct anyway :(. I'll disable the pattern for the field

2. 
> Passwords are not hidden when including them in the wizard

They should be in the latest IPFS test version. I will update a hash below that should have the settings enabled to hide the password

3.
> VIPNODE keeps in “restarting” and throwing an error in the logs but I am sure this has not to do with the wizard. I fact after reinstalling it the logs where the same but the previous label “restarting” was showing “running”

The same happens with the normal package, @eduadiez @vdo  could you check it and see if something's wrong?

**Comment by Shelpin** [comment]
Hi !!!!i made another set of tests.... most of the issues had been solved, comments in blue here
https://docs.google.com/document/d/12nbQga3UTBg1GSp3uuLlqr16MFSwLrpJgvj3d3JYDYY/edit?usp=sharing

**Comment by dapplion** [comment]
@Shelpin Thank you so much!

**Comment by dapplion** [comment]
Core update tests:

#### From master to this upcoming release (setup)
1. Do a restore or make sure DAppNode versions are current master
2. Go to the ui and run in the console
```
```
3. Refresh and update like a normal update (manually, no auto-updates)

#### From upcoming release (setup) to next next release (setup)
1. Make sure the previous versions are installed = the DAppNode can understand a setup wizard.
2. Go to the UI and run in the console
```
```
3. Refresh and update like a normal update (manually, no auto-updates)

**Comment by dapplion** [comment]
Released
