### ISSUE TITLE
How to update docker in the host

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#116]
Let's start thinking about how to update Docker in the DAppNode host in case it is necessary for the future.

**Comment by vdo** [comment]
This would require to add the official docker repositories in the host. 
Do we need this for any special reason, so we need to update old dappnodes too, or we want to add it from now on?

**Comment by dapplion** [comment]
@eduadiez Should we still pursue this?

**Comment by dapplion** [comment]
Done
