### ISSUE TITLE
Package signing service - SPECS

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNode#119]
Concept: Add an API call to DAPPMANAGER so packages can sign messages with any data, prefixed by the DNP name itself.

Initial motivation: The Storj DNP will need to send a signed proof of DAppNode authenticity to a service. So the Storj DNP must do an HTTP call to a DAPPMANAGER endpoint and get a signed message back that links to a mainnet Ethereum identity with a DAppNode NFT

Details / spec: Compose the request to sign message with the name of the DNP (deduced by it's IP). Use a similar standard as Ethereum's
\x19Ethereum Signed Message:\n<length of message>, see https://github.com/ethereum/EIPs/pull/683

Following Ethereum standard, the format will be:

    "\x1dDappnode Signed Message:\n" + len(message) + message

\x1d is a UTF control char, different from the one used in Bitcoin (\x18) and Ethereum (\x19)

Also the message will have the DNP name as a prefix itself to prevent other packages impersonate it, with the format:

    <dnp name>:<message to sign>

So a complete message example would be:

    \x1dDappnode Signed Message:\n50trustlines-monitor.dnp.dappnode.eth:somerandomdata

The third party service then should be able to recover the public address from the signature and also validate the signature with this format

**Comment by dapplion** [comment]
Already implemented
