### ISSUE TITLE
Incorrect install script in docs

### ISSUE THREAD

**Issue by uniconstructor** [dappnode/DAppNode#121]
Doc page url: https://dappnode.github.io/DAppNodeDocs/troubleshooting/#i-need-to-restore-the-system-without-losing-any-data

This section contains old update script url (v 1.21).

It should be replaced with the latest version. 

( am accidentally "restored" my system to previous version, but I hope it will cause no problem.)

Correct version of the script:

```sh
sudo wget -O - https://installer.dappnode.io | sudo UPDATE=true bash
```

**Comment by uniconstructor** [comment]
Cannot make a PR, because I don't understand how the docs are compiled, and where to make edits to. Can you help me with that?

**Comment by vdo** [comment]
@uniconstructor  This is the link to the file:
https://github.com/dappnode/DAppNodeDocs/blob/master/docs/troubleshooting.md

I fixed it, thanks!
