### ISSUE TITLE
Docs statement giving a false sense of security

### ISSUE THREAD

**Issue by meeDamian** [dappnode/DAppNode#124]
While reading [docs], I've came across the statement:

> Even if the OpenVPN files are served via HTTP, they are served encrypted, and then decrypted locally in your browser with the key provided in the link, so anyone snooping the file transfer cannot use it.

This statement is misleading, and potentially giving users false sense of security.  Anyone able to snoop the HTTP traffic, is also able to see the entirety of its `GET` request (including the _decryption_ key).  Therefore, a potential attacker gains access to both the file, and its decryption key.

[docs]: https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#recommended-setup

**Comment by vdo** [comment]
@meeDamian No, this is not true. The encryption key exists only in the client, and never sent via the GET request. It's a client side decryption. If you look at the link, the decryption key is the part after the dash (#) which is never sent in the request and cannot be snooped.

**Comment by meeDamian** [comment]
Yes, you're obviously right.  I've misread.  

Perhaps wording could be improved to sth along the lines of: "[…] served encrypted for the browser-genetated pubkey provided in the link, and then decrypted locally in the browser [...]".

And while AFAIU, the scheme would still be prone to a MITM attack, but that's much harder to properly mitigate w/o trusted 3rd parties, or some prior knowledge.

**Comment by vdo** [comment]
Yes indeed, the documentation should be clearer about this topic, the VPN creds security is a critical piece.
Since there is no way to get a trusted SSL certificate without 3rd parties, we chose this option as a "poor man's SSL". Since it's a one time link, it's really hard to time the MITM attack, and in any case the attacker could not get the DAppNode creds anyway. It looked like a safe enough option. We are also considering using Let's Encrypt certificates, but there are some issues with it (limits, fixed top domain, etc) Any idea on how to improve this is very welcome, thank you!

**Comment by meeDamian** [comment]
Yup.  [50 certs/TLD/month][limit] (+5 cert regens per week) can get quite insufficient, quite quickly…  The only schemes that I've been able to come up with so far are:

1.  A 3rd party (in this case, **you**) buys a bunch of TLDs, and offers a subdomain forwarding service through an API:
	1. _user's_ device asks (your) API for subdomain forward (or through an `ssh` tunnel)
	1. API returns freshly generated `<random-subdomain>.<one-of-many>.<tld>`
	1. device generates certificate for it
	1. `OpenVPN` config is served through there
1.  **You** become the trusted proxy, where **you** generate maxed-out certs (100 subdomains each; `100 * 50` subdomains/month; maybe more if the 5/mo regen limit is also used), and then **you** are trusted to not MITM your users
1.  I'm not sure what's your distribution model, but there can be some secret etched into the storage the device runs from, that's also communicated to end-user through some other channel:  email, device QR sticker, etc…
1.  _(what I personally thing is the worst)_ make user manually add/confirm an extra certificate on their client-device.
1.  Become a root CA 😝

[limit]: https://letsencrypt.org/docs/rate-limits/

**Comment by meeDamian** [comment]
And thoughts that came to me the second I've posted the above:

Ad2: in this model subdomains are not even necessary at all…  Since you're a trusted 3rd party for that request, you can serve it however you want

6. (?) Let's encrypt permits wildcard certs, perhaps it's possible to create _one more level_ in _the-chain-of-trust_, and just sign all subdomains yourself?

In any case, I think this issue can be closed now…  I'd do it, but GH Android app doesn't seem to permit that _yet_ 🤔.

**Comment by vdo** [comment]
Thanks for your insights, we already considered most of your options. In the future we plan to move our VPN to a Wireguard based one without the need of a OVPN file, but for now we will keep the current approach.

I'm closing this issue for now
