### ISSUE TITLE
MORE UPDATE BUTTONS! Wanted to Update my Rinkeby package and there wasn't an obvious way to do it.

### ISSUE THREAD

**Issue by GriffGreen** [dappnode/DAppNode#129]
_Before filing a new issue, please **provide the following information**._

_If you are a DAppNode user, please go to http://my.dappnode/#/troubleshoot and report the issue from there, clicking on the **Report issue** button_

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue. Provide a screencapture or logs if applicable, surrounded by triple backticks: \`\`\` logs block \`\`\`_

The main thing is that i would like to see Update buttons in a few more places... Here is some screen shots of the first places I went to expecting to see the update button:

I thought this was the best place for it:
<img width="1288" alt="Screen Shot 2020-03-16 at 9 47 14 PM" src="https://user-images.githubusercontent.com/14945613/76798365-bc1b0500-67cf-11ea-858f-91a574aad3c3.png">

But it might be nice to have it in these places too :
<img width="916" alt="Screen Shot 2020-03-16 at 9 48 31 PM" src="https://user-images.githubusercontent.com/14945613/76798648-482d2c80-67d0-11ea-8b10-043fff83c352.png">
<img width="1294" alt="Screen Shot 2020-03-16 at 9 47 56 PM" src="https://user-images.githubusercontent.com/14945613/76798669-4ebba400-67d0-11ea-8094-3e0c92e13430.png">
<img width="768" alt="Screen Shot 2020-03-16 at 9 47 42 PM" src="https://user-images.githubusercontent.com/14945613/76798678-524f2b00-67d0-11ea-9e23-9ebc124a210e.png">
<img width="1288" alt="Screen Shot 2020-03-16 at 9 47 14 PM" src="https://user-images.githubusercontent.com/14945613/76798680-52e7c180-67d0-11ea-8a92-328231ed63c4.png">

Lots of update buttons

**Comment by raymonddurk** [comment]
I second this. There is a lot of promise with Dappnode but there isn't a lot of information on what is running, what version is running, how to update, etc. One example I just ran into, but how do I update the OS itself? It seems like I have to download the entire OS again then do a clean install.

**Comment by dapplion** [comment]
@raymonddurk Thanks for the feedback! If you are referring to the underlying Debian OS, we recommend to enable security updates which should be good for a long time. While we found ways to control the OS from the dockerized "core" packages, we still need to refine an update system for the OS that's both reliable and non-invasive

**Comment by raymonddurk** [comment]
I mean that broadly.

- Dappnode is currently on 0.2.37 but I installed a previous version. How do I know that I am on the latest version? What is in the latest version?

- Debian- OK you are working on that but I would still like to know what is being ran and what can be updated especially security related things

- dapps- Most of the packages are labeled as pre-releases with no further release notes or documentation. Are these actually pre-release and we shouldn't install these unless we are ok with the bugs in a beta or are a lot of  these mislableed? Medalla has a ton that are pre-release and a few that are the actual release but the one that installed by default was a pre-lease. 

- System packages - Same thing


There is very poor insight into what is going on with any of these packages and the associated change log. Clarity across the board would be appreciated.

**Comment by dapplion** [comment]
We have many buttons and reminders now
