### ISSUE TITLE
My monero node got stuck and I had no idea until it was too late

### ISSUE THREAD

**Issue by GriffGreen** [dappnode/DAppNode#130]
It would be awesome to have Alarms that report that a node isn't syncing. Emails would be dreamy, but at least a pop up once a day or something reporting that the node you are running is out of sync...

I mean I took this screen shot for the other issue: 

<img width="916" alt="Screen Shot 2020-03-16 at 9 48 31 PM" src="https://user-images.githubusercontent.com/14945613/77113485-37c4be00-6a2b-11ea-800f-436e01f2427c.png">

And didn't notice my monero chain had an issue... until the next day when i couldnt send monero because the node had a corrupted DB :-(

I had to connect to a remote node and resync.

If there was some major alert... at least if that box was blinking red or i had some sort of flag or SOMETHING! I could have been bragging about how my dappnode today.

**Comment by vdo** [comment]
Hi @GriffGreen !
It would be hard to detect issues syncing with all kind of chains, but that would be a nice feature indeed. In the meantime, can you paste the Monero logs?
If DB is corrupted, you may need to resync it from scratch
