### ISSUE TITLE
Override automatic host volume isolation (dappnode-volumes) 

### ISSUE THREAD

**Issue by nathPay** [dappnode/DAppNode#134]
Add the possibility to override the automatic isolation when creating host shared volume.

**actual**
Host: `ls /foo/bar`
`file1 dir1 file2`
Specifying host path to dappnodePackage throught interface: `/foo/bar`
Host: `ls /foo/bar`
`file1 dir1 file2 dappnode-volume`

So here my dappnodePackage cannot access to file1, dir1 and file2.

**expected**
`file1 dir1 file2`
Specifying host path to dappnodePackage throught interface: `/foo/bar`
Host: `ls /foo/bar`
`file1 dir1 file2`
So my dappnodePackage volume is shared with /foo/bar and it can access to file1, dir1 and file2

**use case**
Adding this feature can permit user to share host files with package and then in my case share it to a duplicati package (auto backup on tardigrade).

**Comment by vdo** [comment]
This should discuss the feasibility if this
