### ISSUE TITLE
dappnode.eth ENS name needs to migrated to new Registry

### ISSUE THREAD

**Issue by skylarweaver** [dappnode/DAppNode#136]
See here: https://app.ens.domains/name/gmultisig.dappnode.eth

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380400374) by [Unito](https://www.unito.io)

**Comment by dapplion** [comment]
@skylarweaver Thanks for the heads up!

**Comment by dapplion** [comment]
@eduadiez bump

**Comment by 3alpha** [comment]
@dapplion This is issue for Edu. :)

**Comment by dsimog01** [comment]
Done!
