### ISSUE TITLE
DMS link on the validator dashboard to guide to installing the package if not present

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#138]
A few users have installed the ETH2.0 validator (prysm or witti) and have clicked on the left side metrics button of the dashboard that IF you have a DMS package, will lead you to the validator metrics in DMS.

IF they don't have it installed (it is not a dependency and maybe it shouldn't be anyway), it leads them to a not found page and some come for support in the channel or twitter. 

Is there a way to solve this problem?
Potentially by:
- Detecting whether the DMS is installed or not
- If not, guiding the user to the DMS installation
- Putting it as a dependency of the validator and installing it when installing the validator (least favourite option)

**Comment by dapplion** [comment]
Detecting if the DMS is installed is the better option but I would wait for the DAPPMANAGER to have a well defined non authorized API where packages can fetch that information

**Comment by dapplion** [comment]
Done
