### ISSUE TITLE
Connecting to VPN (Windows 10)

### ISSUE THREAD

**Issue by arquimed** [dappnode/DAppNode#14]
Hi there!

I recently installed my dappNode on an 8 GB Memory / 160 GB Disk / LON1 - Ubuntu 16.04.4 x64 server. 

I got stucked at the VPN configuration steps using Windows 10. I made sure to follow the instructions provided in the DappNode repo [here](https://dappnode.github.io/DAppNode_OTP/#otp=eyJzZXJ2ZXIiOiJTRVJWRVJfSVAiLCJuYW1lIjoiU0VSVkVSX05BTUUiLCJ1c2VyIjoiVlBOX1VTRVIiLCJwYXNzIjoiVlBOX1BBU1NXT1JEIiwicHNrIjoiU0VSVkVSX1BTSyJ9). 

After configuring the VPN connection and introducing the credentials for connecting, it stayed in "connecting" status all the time, without ever successfully completing the process.

This problem was solved after download the two reg files from the [Troubleshooting ](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting)guide:
     
- https://static.ls20.com/reg-files/v1/Fix_VPN_Error_809_Windows_Vista_7_8_10_Reboot_Required.reg

- https://static.ls20.com/reg-files/v1/Fix_VPN_Error_809_Allow_IPsec_Reboot_Required.reg

And then rebooting the PC.

After doing this, I could successfully connect to my dappNode VPN and browse to http://my.admin.dnp.dappnode.eth . It felt like magic ;)

**Comment by dirkconinx** [comment]
I did all this and it still didn't work. 
Removing 'smartbyte drivers and services' (Dell) solved my issue.

**Comment by eduadiez** [comment]
@arquimed @dirkconinx Thank you very much for this incredible feedback and for all the help!

**Comment by dapplion** [comment]
Closing the issue and incorporating the feedback into our FAQ / troubleshooting guide. Thank you @arquimed @dirkconinx
