### ISSUE TITLE
Adding to Samsung Galaxy 8+ was hard

### ISSUE THREAD

**Issue by GriffGreen** [dappnode/DAppNode#15]
The android walkthru was omiting a few important phrases... 

If it is not mentioned in this walk thru, every other feild must remain empty. In some android versions you will have various fields like `L2TP/IPSEC PSK` OR `IPSec Identifier`... these should be blank... And if it says "Always -On VPN" and Advanced Options" which can be also left off

**Comment by Shelpin** [comment]
Will take care of this!

**Comment by dapplion** [comment]
Closing the issue and incorporating the feedback into our FAQ / troubleshooting guide. Thank you @GriffGreen
