### ISSUE TITLE
Dapp node doesn't include mounted volume disk stats

### ISSUE THREAD

**Issue by mpetrunic** [dappnode/DAppNode#155]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **vpn.dnp.dappnode.eth**: 0.2.5
- **admin.dnp.dappnode.eth**: 0.2.20, commit: 0cee5543
- **ipfs.dnp.dappnode.eth**: 0.2.9
- **bind.dnp.dappnode.eth**: 0.2.4
- **wamp.dnp.dappnode.eth**: 0.2.2
- **wifi.dnp.dappnode.eth**: 0.2.3
- **dappmanager.dnp.dappnode.eth**: 0.2.32, commit: 6e10ba53

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 52%

It would be convenient if dappnode would provide disk stats for mounted volume since I've set geth package to store data on mounted volume.

**Comment by dapplion** [comment]
@mpetrunic To report the size of a mounted volume we should run `du` on the directory. This could potentially be extremely slow if the directory contains blockchain data, creating a very bad UX. Do you know if there is a better way of getting the directory size?

**Comment by mpetrunic** [comment]
I meant linux mounted folder. For example external drive or some cloud service that can be attached to linux node. You should be able to get it with `df` quite fast. I think the main issue is to detect that we are storing data on external drive.

**Comment by dapplion** [comment]
Right, tho you can't guarantee that the user has multiple volumes in the mount. So reporting the volume of the entire mount as that volume could be misleading?

**Comment by mpetrunic** [comment]
Well df reports volume size (not mount), if they are all mounted to the same directory you can sum them up (or maybe df would automatically). So you would check where geth data is stored on host and if that directory belongs to some mounted directory you would report size of volumes that are mounted to that directory.
