### ISSUE TITLE
Prysm validator does not resume  after hard restart

### ISSUE THREAD

**Issue by overanalyser** [dappnode/DAppNode#159]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **wifi.dnp.dappnode.eth**: 0.2.3
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **vpn.dnp.dappnode.eth**: 0.2.6, commit: e0d9c111
- **bind.dnp.dappnode.eth**: 0.2.5
- **dappmanager.dnp.dappnode.eth**: 0.2.33, commit: ee72d26d

## System info
docker version: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
docker compose version: docker-compose version 1.25.5, build unknown
Disk usage: 35%

I was testing my disaster recovery by pulling the plug on my staking computer then turning it back on. I was running:
Ubuntu 20.04 with Dappnode on top:
Full GETH node : 0.1.9 (v1.9.18 upstream)
GoGETH node : 0.4.6 (v1.9.15 upstream)
Prysm Beacon: 1.0.4 (v1.0.0-alpha.23 upstream)
Prysm validator  1.0.7 (v1.0.0-alpha.23 upstream)
Lighthouse Beacon : 1.0.4 (v0.2.8 upstream)

On powering up everything **but the prysm validator** restarts.

The prysm validator has the following logged:

_INFO  [db/lowDb:15] Connecting to existing lowdb /app/db-api/server-db.json
INFO  [db/lowDb:15] Connecting to existing lowdb /root/.config/ethereum2/eth1Keymanager.json
INFO  [db/lowDb:15] Connecting to existing lowdb /app/db-api/deposits-db.json
INFO  [services/printGitData:9] git data {
  "version": "1.0.7",
  "branch": "v1.0.7",
  "commit": "5202eccc58b0830a73bd4ce1a567e63c3b9d0cda"
}
INFO  [index:32] App is running at http://localhost:80 in production mode
INFO  [prysm] Starting child process with 'validator --monitoring-host=0.0.0.0 --beacon-rpc-provider=prysm-medalla-beacon-chain.dappnode:4000 --datadir=/prysm --wallet-dir=/prysm/.eth2validators/primary --wallet-password-file=/prysm/.eth2validators/primary.pass --verbosity=info --log-file=/var/log/validator.log --graffiti=Dappnode Degenerate' 12
INFO  [index:19] Started validator client prysm
INFO  [prysm] time="2020-08-30 17:31:05" level=info msg="Logs will be made persistent" logFileName="/var/log/validator.log"
INFO  [prysm] time="2020-08-30 17:31:05" level=info msg="File logging initialized"
INFO  [prysm] time="2020-08-30 17:31:05" level=info msg="[95m(wallet directory)[0m /prysm/.eth2validators/primary" prefix=accounts-v2
INFO  [prysm] time="2020-08-30 17:31:05" level=info msg="Validating for public key" prefix=node pubKey=xxx
time="2020-08-30 17:31:05" level=info msg="Validating for public key" prefix=node pubKey=xxx
time="2020-08-30 17:31:05" level=info msg="Validating for public key" prefix=node pubKey=xxx
INFO  [prysm] time="2020-08-30 17:31:05" level=info msg="Checking DB" databasePath="/prysm" prefix=node
INFO  [prysm] time="2020-08-30 17:31:05" level=info msg="Starting validator node" prefix=node version="Prysm/v1.0.0-alpha.23/0a5ec502b0207c0a39484fa29331fabb351858e7. Built at: 2020-08-18 04:14:07+00:00"
INFO  [prysm] time="2020-08-30 17:31:05" level=info msg="gRPC server listening on address" address="127.0.0.1:7000" prefix=rpc
INFO  [prysm] time="2020-08-30 17:31:05" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=validator
time="2020-08-30 17:31:05" level=info msg="Starting gRPC gateway" address="127.0.0.1:7500" prefix=gateway
INFO  [prysm] time="2020-08-30 17:31:06" level=info msg="Waiting for beacon chain start log from the ETH 1.0 deposit contract" prefix=validator_

_

Restarting the validator fixes the problem.

If i try the same in light house (Prysm and light house beacons running with lighthouse validator) everything starts as normal.

**Comment by dapplion** [comment]
Please try again with the current version we have changed the start-up sequence
