### ISSUE TITLE
IPFS not resolving

### ISSUE THREAD

**Issue by BPrimeD** [dappnode/DAppNode#161]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **wifi.dnp.dappnode.eth**: 0.2.3
- **vpn.dnp.dappnode.eth**: 0.2.5
- **dappmanager.dnp.dappnode.eth**: 0.2.30, commit: dc8967d2
- **admin.dnp.dappnode.eth**: 0.2.19, commit: 875f5a7b
- **bind.dnp.dappnode.eth**: 0.2.4
- **ipfs.dnp.dappnode.eth**: 0.2.7
- **wamp.dnp.dappnode.eth**: 0.2.2

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 4%

Hi, 
I am setting up a Physical DAppNodeAdvanced, currently syncing, and I'm receiving this error.

IPFS is not resolving: Error verifying IPFS: Error parsing file
Go to the system tab and make sure IPFS is running. Otherwise open the package and click 'restart'
If the problem persist make sure your disk has not run of space; IPFS may malfunction in that case.

I'm also having login credentials which the node is not taking my attempts.

Thanks

**Comment by Pol-Lanski** [comment]
Wow. That is old. I assume this has been solved via other channels? (discord, email, forum)
