### ISSUE TITLE
can't obtain OpenVPN config file via download, link or qr code

### ISSUE THREAD

**Issue by vrortvedt** [dappnode/DAppNode#165]
*Before filing a new issue, please **provide the following information**.*

## Core DNPs versions
- **wifi.dnp.dappnode.eth**: 0.2.0
- **admin.dnp.dappnode.eth**: 0.2.1, branch: HEAD, commit: 0bec57dc
- **wamp.dnp.dappnode.eth**: 0.2.0
- **vpn.dnp.dappnode.eth**: 0.2.0, branch: HEAD, commit: 7b017e9e
- **ethforward.dnp.dappnode.eth**: 0.2.0
- **ethchain.dnp.dappnode.eth**: 0.2.0
- **dappmanager.dnp.dappnode.eth**: 0.2.1, branch: HEAD, commit: ebb5b677
- **ipfs.dnp.dappnode.eth**: 0.2.0
- **bind.dnp.dappnode.eth**: 0.2.0
- **core.dnp.dappnode.eth**: 0.2.2

## System info
- **docker version**: Docker version 18.09.1-ce, build 4c52b901c6cb019f7552cd93055f9688c6538be4
- **docker compose version**: docker-compose version 1.20.1, build 5d8c71b
- **Disk usage**: 23%

My AVADO Dappnode is running smoothly, but I can't get past the first step of connecting another device.  I'm trying to connect a windows desktop and an iOS device but can't get anywhere trying to generate .ovpn config files for those devices.  
I am connected to the DAppNode admin portal on a MacOS laptop via the DAppNodeWIFI and I can't even download device credentials using that device.  When I click the share->download icon next to a device name using Brave browser, I just get the following bad link message: 
This site can’t be reached dccdc3c0eb70dd82.dyndns.dappnode.io refused to connect.

Any ideas what might be causing this?

**Comment by VTsuprov** [comment]
Hi, it's not clear what part of the link should i replace with a local IP and where to put "8080"
I also can't download the file.
My connection is done through the LAN with ip 192.168.0.78

**Comment by JosefJ** [comment]
@VTsuprov just replace the entire url before the port:
`http://xxx.dyndns.dappnode.io:8092/?id=xyz` 
=> 
`http://192.168.0.78:8092/?id=xyz` 

Assuming `192.168.0.78` is ip of the device and you are on the same network.

**Comment by froid1911** [comment]
I have the same problem.
I guess it has something to do with IPv6.
I only have a public IPv6 address.

@JosefJ solution does not work. It helps to download the VPN files, but it doesnt allow to create a vpn connection

**Comment by ruvenni** [comment]
Friendly reminder that might be more convenient if you go to our community channels in order to find updated help and support.
Those are:
1. Our forum - https://forum.dappnode.io/
2. Our chat - https://discord.dappnode.io/

**Comment by JosefJ** [comment]
> I have the same problem.
> I guess it has something to do with IPv6.
> I only have a public IPv6 address.
> 
> @JosefJ solution does not work. It helps to download the VPN files, but it doesnt allow to create a vpn connection

@froid1911 Have you enabled the ports at your router? 
-> try doing the same = replacing the `http://xxx.dyndns.dappnode.io` => `192.168.x.y' and try if the VPN connection works. 
If it does, it could be the firewall of your router.
