### ISSUE TITLE
Connection refused to IPFS webui

### ISSUE THREAD

**Issue by osarrouy** [dappnode/DAppNode#18]
Hi guys,

Thanks a lot for your hard work on DAppNode. That's really amazing.

However i got a bug when I try to use the IPFS web UI at : http://my.ipfs.repo.dappnode.eth:5001/webui

It looks like my node refuse the connection on port 5001. Maybe a docker firewall issue ?

**Comment by eduadiez** [comment]
Hi!
are you able to access the administration console http: //my.admin.dnp.dappnode.eth/?
You should be able to see something like this:
<img width="1792" alt="captura de pantalla 2018-07-04 a las 20 29 49" src="https://user-images.githubusercontent.com/20141918/42291026-57a1c874-7fc9-11e8-8c73-8b9fe24f7247.png">
is everything ok on your DAppNode?

**Comment by osarrouy** [comment]
Hey !

Yes i got access to the administration console and everything is up and running.

I just can't access the IPFS web UI.

**Comment by eduadiez** [comment]
where did you get that link http://my.ipfs.repo.dappnode.eth: 5001/webui? 
It seems that we've an error on the documentation, the correct link is:
http://my.ipfs.dnp.dappnode.eth:5001/webui

**Comment by osarrouy** [comment]
Oh ! Thanks !

I had found this address in the installation documentation here : https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide

**Comment by eduadiez** [comment]
I just fixed the links, thanks for reporting the problem!
