### ISSUE TITLE
Error removing DAppManager.

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DAppNode#180]
Hi
I tried to remove DAppManager and found the following problem:
![image](https://user-images.githubusercontent.com/69941298/99250282-b452ab00-280b-11eb-81eb-cd851aca5771.png)

System info below and attached logs.
[dappnode-user-action-logs_2020-11-16T11 59 37.920Z.json.txt](https://github.com/dappnode/DAppNode/files/5546043/dappnode-user-action-logs_2020-11-16T11.59.37.920Z.json.txt)

## Core DAppNode Packages versions
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **dappmanager.dnp.dappnode.eth**: 0.2.35, commit: cbd7cbcf
- **ipfs.dnp.dappnode.eth**: 0.2.11
- **bind.dnp.dappnode.eth**: 0.2.6
- **wifi.dnp.dappnode.eth**: 0.2.4

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.4.0-51-generic
- **Disk usage**: 37%

**Comment by dapplion** [comment]
That is by design since the dappmanager can't delete itself. I'll add the functionality for it in another issue
