### ISSUE TITLE
Get failed command: WRITE FPDMA QUEUED

### ISSUE THREAD

**Issue by tripper311** [dappnode/DAppNode#184]
Getting an error on my dappnode NUC that says "Get failed command: WRITE FPDMA QUEUED"

Screenshot here - https://madshot.net/d18ec0e5b5ba.png

Anything I should be aware of?

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **wifi.dnp.dappnode.eth**: 0.2.3
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **dappmanager.dnp.dappnode.eth**: 0.2.33, commit: ee72d26d
- **vpn.dnp.dappnode.eth**: 0.2.6, branch: v0.2.6, commit: fb3f7316
- **bind.dnp.dappnode.eth**: 0.2.5

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **Disk usage**: 9%

**Comment by dapplion** [comment]
Should be fixed with the latest releases, please let us know if it happens again be re-opening the issue.
