### ISSUE TITLE
DappNode Advanced: Medalla stuck in beacon node syncing?

### ISSUE THREAD

**Issue by BPrimeD** [dappnode/DAppNode#186]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.34, commit: d075b2f5
- **core.dnp.dappnode.eth**: 0.2.38
- **vpn.dnp.dappnode.eth**: 0.2.6, branch: v0.2.6, commit: fb3f7316
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **bind.dnp.dappnode.eth**: 0.2.5
- **wifi.dnp.dappnode.eth**: 0.2.3

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **Disk usage**: 41%

INFO  [prysm] time="2020-10-23 20:30:34" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=validator
INFO  [prysm] time="2020-10-23 20:30:40" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=validator
INFO  [prysm] time="2020-10-23 20:30:46" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=validator
INFO  [prysm] time="2020-10-23 20:30:52" level=info msg="Waiting for beacon node to sync to latest chain head" prefix=validator

**Comment by dapplion** [comment]
Please try again with the latest version of Prysm Pyrmont
