### ISSUE TITLE
Multiple VPN connections interfere with DNS/resolving of hostnames

### ISSUE THREAD

**Issue by beralt85** [dappnode/DAppNode#187]
## Expected behaviour
- connecting multiple VPN clients should not cause problems.

## Actual behaviour
- Connecting two clients at the same time interferes with DNS resolving.

## Workaround
- Create a separate (non-admin) VPN connection for the second device
- Only establish a single VPN connection at the same time.

## Description
I am running a DAppNode with goerli geth and geth fully synced.
I then connect to the DAppNode VPN via LAN (only). Name resolution etc works perfectly, can ping and traceroute *.dappnode, can access the RPC interface on http://goerli-geth.dappnode:8545.

Now I run a second VM to the DAppNode VPN  *with the same key* also via LAN (Ubuntu Server LTS 20.04, latest upgrade).
Name resolution and access to RPC interface becomes spotty, sometimes works, sometimes doesn't.

The VM runs a lighthouse beacon client on pyrmont, connecting to the ETH1 interface at http://goerli-geth.dappnode:8545.
Everything works fine, I got perfect attestation when the VM is the only device connected to the VPN.
Example output from lighthouse logs showing that RPC requests work:

`Nov 24 18:39:18 pyrmontt0 lighthouse[765]: Nov 24 18:39:18.418 INFO Imported deposit log(s)                 new: 1, total: 103355, latest_block: 3809849, service: eth1_rpc`

As soon as I also connect the Desktop via VPN, RPC requests, pring/traceroute do not resolve (but still randomly work for short periods of time) on the VM.
The lighthouse logs also reflect this behaviour:
`Nov 24 18:58:25 pyrmontt0 lighthouse[765]: Nov 24 18:58:25.450 CRIT Error connecting to eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or pass an external endpoint using `--eth1-endpoint <SERVER-ADDRESS>`. Also ensure that `eth` and `net` apis are enabled on the eth1 http server, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID ETH1 CONNECTION, service: eth1_rpc`

Disconnecting the Desktop from the DAppNode VPN resolves the problems after 2-5 minutes or so.

I can reproduce this behaviour consistently.

## Possibly related issues
https://github.com/dappnode/DAppNode/issues/160
https://github.com/dappnode/DAppNode/issues/177
https://old.reddit.com/r/ethstaker/comments/hcetj3/trouble_with_regular_connection_when_dappnode_is/

## Core DAppNode Packages versions
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **dappmanager.dnp.dappnode.eth**: 0.2.35, commit: cbd7cbcf
- **core.dnp.dappnode.eth**: 0.2.39
- **wifi.dnp.dappnode.eth**: 0.2.4
- **ipfs.dnp.dappnode.eth**: 0.2.11
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-2-amd64
- **Disk usage**: 47%

**Comment by beralt85** [comment]
Connection to the VPN using a different (non-admin) device key seems to have fixed the problem.
I updated the issue to reflect the fact.

**Comment by pablomendezroyo** [comment]
Are you trying to connect throug VPN using virtual machines? if so the behaviour is unknown and is not officially supported by dappnode
