### ISSUE TITLE
Prysm pyrmont package 

### ISSUE THREAD

**Issue by Tcg876** [dappnode/DAppNode#188]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.33, commit: ee72d26d
- **wifi.dnp.dappnode.eth**: 0.2.3
- **bind.dnp.dappnode.eth**: 0.2.5
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **vpn.dnp.dappnode.eth**: 0.2.6, branch: v0.2.6, commit: fb3f7316

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **Disk usage**: 7%

Pyrmont installation error below:

Error: Error verifying image: image tarball must contain strictly one image
    at /usr/src/app/webpack:/src/modules/installer/downloadImages.ts:40:20
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/index.js:174508:65)

{
  "name": "prysm-pyrmont.dnp.dappnode.eth",
  "version": "0.1.0",
  "userSettings": {
    "prysm-pyrmont.dnp.dappnode.eth": {
      "environment": {
        "WALLET_PASSWORD": "**********"
      }
    }
  },
  "options": {}
}

**Comment by takamaka-1337** [comment]
Thanks!

**Comment by takamaka-1337** [comment]
> You must update your DAppNode to the latest version. Pyrmont package uses a feature not available in your version. This is enforced in the last patch for the Pyrmont package https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/blob/4876deb4d54388982fbdee9bbfa5a4963c869cb7/dappnode_package.json#L24

thanks!
