### ISSUE TITLE
Ports have to be opened and there is no UPnP device available

### ISSUE THREAD

**Issue by takamaka-1337** [dappnode/DAppNode#190]
Hello,

I did not find resources which shows if ETH2 will work with ports not being opened. I am behind router, not able to open any ports. 

I can use VPN "locally", but no connection from outside, which is OK for me.

So, my question is - will I be able to use dappnode without any problems at staking with such setup?

Please see image below and configuration for further information.

![image](https://user-images.githubusercontent.com/12158250/100191190-02dd0500-2ef0-11eb-90d5-b715956ccd6d.png)

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **wifi.dnp.dappnode.eth**: 0.2.3
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **dappmanager.dnp.dappnode.eth**: 0.2.33, commit: ee72d26d
- **vpn.dnp.dappnode.eth**: 0.2.6, branch: v0.2.6, commit: fb3f7316
- **bind.dnp.dappnode.eth**: 0.2.5

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **Disk usage**: 13%

**Comment by dapplion** [comment]
It's very important to have ports open. It's necessary to have a large amount of Eth2.0 peers and have good stacking performance.

**Comment by takamaka-1337** [comment]
So, its important but not urgent?

**Comment by dapplion** [comment]
If you want to have good validator performance now it's urgent yes
