### ISSUE TITLE
Connectivity check not working properly

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DAppNode#191]
We have detected that the connectivity check can be shown as enabled when no internet connectivity was present in a DAppNode Extreme

Opening this issue and waiting in case @eduadiez has further info to add

![image](https://user-images.githubusercontent.com/69941298/100373716-7de70e00-300b-11eb-8cd0-75823df3adf9.png)

**Comment by dapplion** [comment]
This check's text is not correct since once the DAPPMANAGER has discovered it's own public IP it will consider itself connected to the internet always. Instead, the check should be repeated on demand when the user open this page.

**Comment by pablomendezroyo** [comment]
I think this issue can be marked as solved

**Comment by dapplion** [comment]
Fixed, now the check shows if the DAppNode has internet connection in real time
