### ISSUE TITLE
Is DappNode ready to use Medalla for staking?

### ISSUE THREAD

**Issue by tripper311** [dappnode/DAppNode#192]
Hi - I love what you have put together but I see that Medalla still says testnet in the app installer - View screenshot here - https://madshot.net/8e4d9459a048.png

Am I good to stake with DappNode?

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **wifi.dnp.dappnode.eth**: 0.2.3
- **ipfs.dnp.dappnode.eth**: 0.2.10
- **dappmanager.dnp.dappnode.eth**: 0.2.33, commit: ee72d26d
- **vpn.dnp.dappnode.eth**: 0.2.6, branch: v0.2.6, commit: fb3f7316
- **bind.dnp.dappnode.eth**: 0.2.5

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **Disk usage**: 14%

**Comment by dapplion** [comment]
Medalla is deprecated, stake on https://github.com/dappnode/DAppNodePackage-prysm-pyrmont instead
