### ISSUE TITLE
Eth 2.0 Validator onboarding: Dappnode not giving access to prysm UI to store wallet data

### ISSUE THREAD

**Issue by sedamil** [dappnode/DAppNode#194]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.36, branch: v0.2.36, commit: ad68eecb
- **core.dnp.dappnode.eth**: 0.2.40
- **wifi.dnp.dappnode.eth**: 0.2.4
- **bind.dnp.dappnode.eth**: 0.2.6
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **ipfs.dnp.dappnode.eth**: 0.2.11

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-1-amd64
- **Disk usage**: 727567459942

I am accessing via Windows 10, Brave browser Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit)

The output in the browser is the following:

Failed to load resource: http://prysm.dappnode/api/v2/validator/wallet/keystores/import
the server responded with a status of 400 (Bad Request)
main.58bd9be30c2571e9610a.js:1 ERROR xh
An @ main.58bd9be30c2571e9610a.js:1

Resolved by opening additional ports via SSH:
ssh -L 3500:127.0.0.1:3500 -L 7500:127.0.0.1:7500 -L 8080:127.0.0.1:8080 -L 8081:127.0.0.1:8081 [user]@[your-vps-IP], thank you @voska from the Discord

**Comment by dapplion** [comment]
Glad you could fix it! I'll repost the solution for other users

> Resolved by opening additional ports via SSH:
ssh -L 3500:127.0.0.1:3500 -L 7500:127.0.0.1:7500 -L 8080:127.0.0.1:8080 -L 8081:127.0.0.1:8081 [user]@[your-vps-IP], thank you @voska from the Discord
