### ISSUE TITLE
Fix port in WIKI, port 8092 should be opened, not port 8090

### ISSUE THREAD

**Issue by olofedlund** [dappnode/DAppNode#198]

**Comment by olofedlund** [comment]
Actually, isn’t it safer to not open this port at all and let users fetch the .ovpn through dappnodewifi?  It might be simpler for novice users as well.

**Comment by dapplion** [comment]
That's a great point. @eduadiez Would it make sense to offer the .ovpn internally too for example at
```
http://vpn.dappnode/?id=Rm8W2HjSWQ0af6NM#s2cKEv9lVEydrXYNpCnnRBgs4uEDeNAr8xu3iQet18M%3D
```
