### ISSUE TITLE
Nethermind chain - Batch BlockByNumber Call Leads to Invalid Block Headers Being Returned error in Prysm

### ISSUE THREAD

**Issue by tripper311** [dappnode/DAppNode#199]
I was getting this error in Prysm - 
https://madshot.net/9c9e3cf6b04f.png

Found this thread - https://github.com/NethermindEth/nethermind/issues/2525

Main takeaway:
"We believe that it will happen for users who did not select --Sync.DownloadReceiptsInFastSync true during the initial sync. In such cases for now resync of Nethermind is required so the receipts are available - version 1.9.41 has this option enabled by default to avoid problems for users who are not aware of it."

Is that option available in dappnode?

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.36, branch: v0.2.36, commit: ad68eecb
- **core.dnp.dappnode.eth**: 0.2.40
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **wifi.dnp.dappnode.eth**: 0.2.4
- **ipfs.dnp.dappnode.eth**: 0.2.11
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-3-amd64
- **Disk usage**: 100072737997

**Comment by tripper311** [comment]
so with that being said - does anybody know how to take my validator keystore off of prysm so I can try a different way?  To avoid slashing when i go to a different staking method?

**Comment by dapplion** [comment]
> so with that being said - does anybody know how to take my validator keystore off of prysm so I can try a different way? To avoid slashing when i go to a different staking method?

You can remove the validator volumes to be 100% sure you've completely deleted them from the package
