### ISSUE TITLE
Issue, pls help

### ISSUE THREAD

**Issue by olivierfreuler** [dappnode/DAppNode#203]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.36, branch: v0.2.36, commit: ad68eecb
- **core.dnp.dappnode.eth**: 0.2.40
- **wifi.dnp.dappnode.eth**: 0.2.4
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **ipfs.dnp.dappnode.eth**: 0.2.11
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-1-amd64
- **Disk usage**: 284004712448

**Comment by olivierfreuler** [comment]
![Screenshot_20201201-220200_Brave](https://user-images.githubusercontent.com/58338510/100796679-4b7d4c80-3421-11eb-9eb2-747fb73eef0e.jpg)

#

**Comment by olivierfreuler** [comment]
I can not sync geth for 5 days

**Comment by ruvenni** [comment]
What kind of machine are you running dappnode on top of, @olivierfreuler ? What kind of hard disk?

I know of some cases taking that much to sync

**Comment by olivierfreuler** [comment]
DAppNodeMini
INTEL NUC J5005 SERIE 7
KINGSTON DDR4 8GB
HD WD 1TB SSD

**Comment by olivierfreuler** [comment]
All good
