### ISSUE TITLE
UPnp device not available

### ISSUE THREAD

**Issue by tntcrypto** [dappnode/DAppNode#204]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **ipfs.dnp.dappnode.eth**: 0.2.11
- **dappmanager.dnp.dappnode.eth**: 0.2.36, branch: v0.2.36, commit: ad68eecb
- **core.dnp.dappnode.eth**: 0.2.40
- **wifi.dnp.dappnode.eth**: 0.2.4
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-1-amd64
- **Disk usage**: 331464101069

EDIT:
User saw this error:

> Ports have to be opened and there is no UPnP device available If you are capable of opening ports manually, please ignore this error Your router may have UPnP but it is not turned on yet. Please research if your specific router has UPnP and turn it on

**Comment by ruvenni** [comment]
hey @tntcrypto

other user with the same issue here https://forum.dappnode.io/t/upnp-issue-although-router-upnp-is-enable/577

Please join our forum (no need to create a new account, github credentials are allowed)
