### ISSUE TITLE
Is my Dappnode running?

### ISSUE THREAD

**Issue by marshallepie** [dappnode/DAppNode#205]
*Greetings Everyone, Noobs here. **Thank you for the great software. We appreciate your contribution to the ecosystem.**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **ipfs.dnp.dappnode.eth**: 0.2.11
- **core.dnp.dappnode.eth**: 0.2.40
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **wifi.dnp.dappnode.eth**: 0.2.4
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-3-amd64
- **Disk usage**: 333826333082

## Hardware
- **HP Z240 Small Form Factor Workstation
- **1TB SSD
- **16 Gb

**Just to say I finally got all green ticks on my dappnode support tab as follows;**

_Session is open
IPFS resolves
Has connected to the internet, and detected own public IP
No ports have to be opened OR the router has UPnP enabled
NAT loopback enabled, external IP resolves
Disk usage is ok (<95%)
All core DAppNode Packages are running_

**Does this mean all is well? Can I relax now?**

**Comment by dapplion** [comment]
Your DAppNode is running, you can relax :heart:

**Comment by marshallepie** [comment]
Thank you.
