### ISSUE TITLE
Suggestion: Change color on the button to update in the DAppStore

### ISSUE THREAD

**Issue by olofedlund** [dappnode/DAppNode#208]
The “Update” button is hard to distinguish from the “Get” green. Change its color to “Update” orange or some such thing.

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **core.dnp.dappnode.eth**: 0.2.41
- **wifi.dnp.dappnode.eth**: 0.2.5
- **ipfs.dnp.dappnode.eth**: 0.2.12
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-1-amd64
- **Disk usage**: 367863948902

**Comment by pablomendezroyo** [comment]
would you mind to move your great proposal to https://github.com/dappnode/DNP_DAPPMANAGER/issues/519 ?

Just leave comment of what would you expect from the dappstore

Thanks in advanced!

**Comment by pablomendezroyo** [comment]
#519 closes
