### ISSUE TITLE
pre-seed command failed

### ISSUE THREAD

**Issue by dpdanpittman** [dappnode/DAppNode#209]
_Before filing a new issue, please **provide the following information**._

_If you are a DAppNode user, please go to http://my.dappnode/#/troubleshoot and report the issue from there, clicking on the **Report issue** button_

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue. Provide a screencapture or logs if applicable, surrounded by triple backticks: \`\`\` logs block \`\`\`_

At the end of installation when preseed command is envoked it hangs at 13% then goes to a red screen that says command failed. This happens on both the pre-built iso and the iso built from source.

**Comment by ruvenni** [comment]
Already posted in the forum https://forum.dappnode.io/t/failed-to-run-preseeded-command/562/
