### ISSUE TITLE
Zenhub Methodology *do not close*

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#21]
## Procedure:
- Add new items into **New Issues**
- Then if that issue can be solved now, move it to **Backlog**. If it will be solved in the future with no rush, move it to **Icebox**
- Once you start working on issue, move it to **In Progress**, so others know that you are doing that
- Once you are done with it, move it to **Review/QA**. 
- Some else should review it and approve it, then move it to **Done**. It will stay there after being completed but before merging its branch.
- After merging the PR or closing the issue move it to **Closed**, but this step should happen automatically.
 
## Solving an issue

1. Create a branch with the issue number and its description. For example: `43_fix_launch_button`, `120_improve_performance`. It the branch is not related to a specific issue do the same without prefixing it with a number.

2. There should always be a PR open for the next version. Go there an edit the description to add the fix you are doing. Link it to a specific issue if it was open for that purpose or reference it in the PR body if it fixes multiple issues. Just type: `fixes #32 (number of the issue)` and github will link the issue to the PR, closing it upon merge ([source](https://help.github.com/articles/closing-issues-using-keywords)).

**Comment by eduadiez** [comment]
@dapplion Move this issue to the wiki
