### ISSUE TITLE
Built from source ISO does not let you enter a username and password during install

### ISSUE THREAD

**Issue by dpdanpittman** [dappnode/DAppNode#210]
_Before filing a new issue, please **provide the following information**._

_If you are a DAppNode user, please go to http://my.dappnode/#/troubleshoot and report the issue from there, clicking on the **Report issue** button_

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue. Provide a screencapture or logs if applicable, surrounded by triple backticks: \`\`\` logs block \`\`\`_

When plugged in to ethernet directly the install allows me to set my static IP and gateway but after that it does not ask questions and auto installs.  It does not ask me to enter a username or password then the pre-seed command fails.  When it reboots everything is ok but I cannot enter the username and password because I do not know what it is since I did not set it up.

**Comment by ruvenni** [comment]
The default set-up credentials are:
User: dappnode
Password: dappnode.s0

But if you have already accessed the admin UI through wifi or VPN they might not be the same anymore, as you are asked to change them in the UI first access.
