### ISSUE TITLE
I managed to lost my login passwords to Prysm web and wallet

### ISSUE THREAD

**Issue by VTsuprov** [dappnode/DAppNode#218]
Hi could smb help me, pls!
I've succsessfully launched Prysm beacon chain. But I occasionaly lost my pwd for Web access and access to wallet in Prysm.
The deposit contract and keystore are safe. I just do not have any more access to Prysm. 
My validator is not yet active (pendng) but I do not have any more access to the Wallet :(

**Comment by dapplion** [comment]
> Hi could smb help me, pls!
> I've succsessfully launched Prysm beacon chain. But I occasionaly lost my pwd for Web access and access to wallet in Prysm.
> The deposit contract and keystore are safe. I just do not have any more access to Prysm.
> My validator is not yet active (pendng) but I do not have any more access to the Wallet :(

You can remove the Validator data volume, and start from scratch: Import your keystores and set a UI and wallet password. Make sure to use a password manager to prevent password loss

**Comment by VTsuprov** [comment]
Thank's a lot. I hopped it's a quit easy but anyway your advise is higly appreciated
