### ISSUE TITLE
DAppStore never loads

### ISSUE THREAD

**Issue by BrashFulcrum** [dappnode/DAppNode#219]
This is a new install of dappnode (and my first). I'm able to connect through the VPN, but the store never loads. It just spins with the phase "loading dappnode packages". Any help would be appreciated.

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **wifi.dnp.dappnode.eth**: 0.2.4
- **ipfs.dnp.dappnode.eth**: 0.2.11
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **bind.dnp.dappnode.eth**: 0.2.6
- **dappmanager.dnp.dappnode.eth**: 0.2.35, commit: cbd7cbcf

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-4-amd64
- **Disk usage**: 0%

**Comment by dapplion** [comment]
Probably IPFS is still propagating the package's data. Check status in a bit or add this peer to speed up the process

http://my.dappnode/#/system/add-ipfs-peer/%2Fdns4%2Fipfs.dappnode.io%2Ftcp%2F4001%2Fipfs%2FQmfB6dT5zxUq1BXiXisgcZKYkvjywdDYBK5keRaqDKH633

**Comment by BrashFulcrum** [comment]
![Screenshot_20201209-063642](https://user-images.githubusercontent.com/75714424/101631210-9b43b100-39e9-11eb-99fe-c819c7eaa77f.png)
Thank you for the help. After linking Most of apps appeared, but not Prysm which is what I'm after.

**Comment by ruvenni** [comment]
Make sure to have auto-updates on and have a look [here](http://my.dappnode/#/system/auto-updates) in case you need to update DAppNode. IPFS was fixed in our last release to include a troubleshooting under Packages > System Packages > IPFS > Config

![image](https://user-images.githubusercontent.com/69941298/101777799-4724f380-3af3-11eb-995c-74585d209fc7.png)


You can also download Prysm package directly from our [repo](https://github.com/dappnode/DAppNodePackage-prysm/releases/tag/v1.0.5), through this [link](http://my.dappnode/#/installer/%2Fipfs%2FQmRbmb7YDt7o3jQSi6VDJksGcY9UoYSn9HF9QuRL8V6EZL)

Let us know if you succeed ;)

**Comment by BrashFulcrum** [comment]
Thank you for helping me.
- Forcing a manual system update did the trick.
- Also, opening the ports buried in the DAppnode [troubleshooting page](https://dappnode.github.io/DAppNodeDocs/troubleshooting/) may have also done something to help my initial issue of the Store not propagating. My router doesn't have UPnP.

** Next problem: I get an error when attempting to import my wallet into Prysm. After the last step (wallet encryption password) I click [continue] and get this error.
> Http failure response for http://prysm.dappnode/api/v2/validator/wallet/keystores/import: 500 Internal Server Error
It will not let me continue to the prysm dashboard.
- What could be causing this?

**Comment by ruvenni** [comment]
There are some known bugs in Prysm IU.

Main work-arounds to overcome them until they fix them are:
* Making sure you are running a valid ETH1.x node and the node is full synced.
* Setting a password may require some attempts, users had reported a successful [pattern to match](https://github.com/prysmaticlabs/prysm-web-ui/issues/99#issuecomment-733991284).
* Only 'keystore-*.json' alike files should be uploaded when importing the wallet ([link](https://forum.dappnode.io/t/prysm-pyrmont-validator-signup-400-bad-request/514))
