### ISSUE TITLE
Guarantee docker execution

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#22]
Guarantee docker execution. Maybe have it in a separate partition to guaratee it doesn't run out of space. 
    - Virtual partition?

**Comment by dapplion** [comment]
@eduadiez Should we still pursue this? And alternative is to control the space of the DAppNode with aggressive action such as stoping all chains / containers if less than x GB of disk space are left.

**Comment by eduadiez** [comment]
With the current disk monitor feature is this issue done
