### ISSUE TITLE
Feature request: Big Red fix-everything-button

### ISSUE THREAD

**Issue by olofedlund** [dappnode/DAppNode#222]
A large subset of problems can be solved by updating all packages and rebooting the system and a few other simple actions.

Something that should be tried first that fixes 50% of all problems so that more time can be spent on more tricky problems.

What if there was a Big Red fix-everything-button on the support page or wherever?

Example of things that could be fixed with such a button:
1. Update to the latest version of all packages (Would for instance fix the DMS and DAppNode-exporter with a restart problem)
2. Update the DAppNode `wget -qO - https://installer.dappnode.io | sudo UPDATE=true bash`
3. ... Whatever else you guys can think of

The intent is not that this should be used on a machine in production, but it can be the first thing that an inexperienced user can try. They can use it by their own initiative, but it could also be something that he could be asked to do before diving into more detailed trouble shooting. It should come with a big warning dialog to not do it lightly on a machine in production.

This should also be available as a command line command:
dappnode_somegoodname

Yesterday it could have been useful as the first thing to try with a user for whom the GUI wasn’t working but where it was possible to ssh in.

**Comment by dapplion** [comment]
I really like the idea! It has been in the talks for a while, may be time to implement it. What do you think @eduadiez ?
