### ISSUE TITLE
Refuse to run DAppNode if it is assigned a non local IP

### ISSUE THREAD

**Issue by olofedlund** [dappnode/DAppNode#225]
If the user wants a non-local IP for whatever strange reason then that should be some active and deliberate work.

If this happens it is most likely a mistake and it is dangerous because the device is probably open to the Internet.

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **ipfs.dnp.dappnode.eth**: 0.2.14
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **core.dnp.dappnode.eth**: 0.2.41
- **wifi.dnp.dappnode.eth**: 0.2.5
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-1-amd64
- **Disk usage**: 386547056640

**Comment by eduadiez** [comment]
It is difficult to know if it is deliberate or not; in certain configurations where only public IP exists, this active configuration can be a nuisance.

So I am not entirely sure how we can manage this to avoid annoying any of the different use cases.

Any suggestions on how to deal with this in all cases are welcome.

**Comment by olofedlund** [comment]
I think that nuisance for an expert user is a very small concern compared to the safety of a noob user.

Yesterday I was helping a user who had plugged his dappnode directly into the modem. He was probably completely open to the Internet.  

I think the secondary question is how this can be simplified for the expert user that wants to use a public IP.

If the system refuses to start up because it isn’t a local IP then the user can be given a message that explains why and what needs to be done and with appropriate warnings. The wizard could even guide the user through it. An expert user would sail through this.
