### ISSUE TITLE
My mini is unstable it seems to think its running out of memory and starts to cut processes associated to geth

### ISSUE THREAD

**Issue by rylo2020** [dappnode/DAppNode#227]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **ipfs.dnp.dappnode.eth**: 0.2.14
- **wifi.dnp.dappnode.eth**: 0.2.5
- **dappmanager.dnp.dappnode.eth**: 0.2.37
- **core.dnp.dappnode.eth**: 0.2.41
- **vpn.dnp.dappnode.eth**: 0.2.7
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **Disk usage**: 344134254592

**Comment by ruvenni** [comment]
Hi @rylo2020

We are attending support cases directly in our [forum](https://forum.dappnode.io/), where in addition you will be able to see how other users solved their issues or find help in the community.

Could you please open a new topic there? There's no need to sign-up, as it is integrated with Github. Thanks!!
