### ISSUE TITLE
Reporting issues from ADMIN UI to the Forum

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DAppNode#229]
Specially for Tier 1/2 support issues it would be convenient to include a way to report them to the forum instead of GitHub.

The new feature should ideally work as the current one in terms of
* Keeping the same user journey
* Needing the minimum possible changes in the code

I've found that it is possible to open issues by simply using a URL parameters, for instance:
`https://forum.dappnode.io/new-topic?title=topic%20title&body=topic%20body&category_id=4`

If the user is not already registered, the log in screen will appear, as it already happens when reporting to GitHub.
![image](https://user-images.githubusercontent.com/69941298/102639771-cea8dd00-4159-11eb-9a8c-c91463d71d12.png)

**Comment by pablomendezroyo** [comment]
This issue can be considered as a suggestion of the following DAPPMANAGER issue https://github.com/dappnode/DNP_DAPPMANAGER/issues/507

**Comment by dapplion** [comment]
That's awesome! @ruvenni thanks for finding it, it's exactly what we need

**Comment by dapplion** [comment]
Implemented with v
