### ISSUE TITLE
Prysm Pyrmont won’t restart

### ISSUE THREAD

**Issue by Blackswan122** [dappnode/DAppNode#231]
I'm having a lot of problems with my DSL connections. Telekom have been around and have now said the 4 line to my house are bad. I have managed to restart the PP package before but this time it just won't restart.

**Comment by dapplion** [comment]
Could you paste here the full logs of the Prysm Pyrmont package + the package version + your DAppNode versions?

**Comment by Blackswan122** [comment]
[
  {
    "level": "error",
    "timestamp": 1608391804707,
    "event": "packageRestart",
    "message": "Command failed: docker-compose -f dnp_repo/prysm-pyrmont.dnp.dappnode.eth/docker-compose.yml up --detach --force-recreate <&-\nRemoving DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth\nRecreating b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth ... \r\nRecreating DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth                 ... \r\nHost is already in use by another container\n\u001b[2A\u001b[2K\rRecreating b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth ... \u001b[31merror\u001b[0m\r\u001b[2B\nERROR: for b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth  Cannot start service beacon-chain: driver failed programming external connectivity on endpoint DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (e9f94502cce619a07b2d064f3ed74d9d7c6aba2917f22c461aad155efb44c3f2): Bind for 0.0.0.0:32772 failed: port is already allocated\n\u001b[1A\u001b[2K\rRecreating DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth                 ... \u001b[32mdone\u001b[0m\r\u001b[1B\nERROR: for beacon-chain  Cannot start service beacon-chain: driver failed programming external connectivity on endpoint DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (e9f94502cce619a07b2d064f3ed74d9d7c6aba2917f22c461aad155efb44c3f2): Bind for 0.0.0.0:32772 failed: port is already allocated\nEncountered errors while bringing up the project.\n",
    "stack": "Error: Command failed: docker-compose -f dnp_repo/prysm-pyrmont.dnp.dappnode.eth/docker-compose.yml up --detach --force-recreate <&-\nRemoving DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth\nRecreating b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth ... \r\nRecreating DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth                 ... \r\nHost is already in use by another container\n\u001b[2A\u001b[2K\rRecreating b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth ... \u001b[31merror\u001b[0m\r\u001b[2B\nERROR: for b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth  Cannot start service beacon-chain: driver failed programming external connectivity on endpoint DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (e9f94502cce619a07b2d064f3ed74d9d7c6aba2917f22c461aad155efb44c3f2): Bind for 0.0.0.0:32772 failed: port is already allocated\n\u001b[1A\u001b[2K\rRecreating DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth                 ... \u001b[32mdone\u001b[0m\r\u001b[1B\nERROR: for beacon-chain  Cannot start service beacon-chain: driver failed programming external connectivity on endpoint DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (e9f94502cce619a07b2d064f3ed74d9d7c6aba2917f22c461aad155efb44c3f2): Bind for 0.0.0.0:32772 failed: port is already allocated\nEncountered errors while bringing up the project.\n\n    at Object.<anonymous> (/usr/src/app/webpack:/src/utils/shell.ts:37:16)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/index.js:19597:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "args": [
      {
        "dnpName": "prysm-pyrmont.dnp.dappnode.eth"
      }
    ]
  },
  {
    "level": "error",
    "timestamp": 1608391796038,
    "event": "packageStartStop",
    "message": "Command failed: docker start DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth\nError response from daemon: driver failed programming external connectivity on endpoint DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (9e7b1f44b6071a7536331f9d4cc6a2d978a247e37a3963fbd86060b87ca37b41): Bind for 0.0.0.0:32772 failed: port is already allocated\nError response from daemon: driver failed programming external connectivity on endpoint b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (3da80229da3ed669d7a1360eec98aa53ae8eea174e8745837611c4920e9763ca): Bind for 0.0.0.0:32770 failed: port is already allocated\nError: failed to start containers: DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth, b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth\n",
    "stack": "Error: Command failed: docker start DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth DAppNodePackage-validator.prysm-pyrmont.dnp.dappnode.eth b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth\nError response from daemon: driver failed programming external connectivity on endpoint DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (9e7b1f44b6071a7536331f9d4cc6a2d978a247e37a3963fbd86060b87ca37b41): Bind for 0.0.0.0:32772 failed: port is already allocated\nError response from daemon: driver failed programming external connectivity on endpoint b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth (3da80229da3ed669d7a1360eec98aa53ae8eea174e8745837611c4920e9763ca): Bind for 0.0.0.0:32770 failed: port is already allocated\nError: failed to start containers: DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth, b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth\n\n    at Object.<anonymous> (/usr/src/app/webpack:/src/utils/shell.ts:37:16)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/index.js:19597:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
    "args": [
      {

**Comment by Blackswan122** [comment]
![image](https://user-images.githubusercontent.com/59722401/102705056-740ba000-4283-11eb-851c-f4f00fe1cd1d.png)

**Comment by Blackswan122** [comment]
![image](https://user-images.githubusercontent.com/59722401/102705061-808ff880-4283-11eb-902d-d55f10c073b7.png)

**Comment by ruvenni** [comment]
what's the prysm pyrmont package version?

**Comment by dapplion** [comment]
The issue comes from the existence of an intermediate container by the docker-compose re-create sequence
```
b41f7afe0b2f_DAppNodePackage-beacon-chain.prysm-pyrmont.dnp.dappnode.eth
```
That container is using the same ports so it fails.

@eduadiez Should we make the Prysm ports ephemeral so there are no collisions?

**Comment by Blackswan122** [comment]
If I knew what that was I could answer you. If it helps yes... I'm up and running again when my DSL works. I'm now not sure if it's my provider or DappNode that's causing my issues. I've had Telekom around 4 times now. They say that my 4 lines are "not very good" they maybe be tasking someone to change them.
