### ISSUE TITLE
IPFS 405 Method Not Allowed

### ISSUE THREAD

**Issue by Memoi** [dappnode/DAppNode#232]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **core.dnp.dappnode.eth**: 0.2.41
- **wifi.dnp.dappnode.eth**: 0.2.5
- **ipfs.dnp.dappnode.eth**: 0.2.12
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-1-amd64
- **Disk usage**: 355301169562
-

The IPFS return a 405:

curl -I http://172.33.1.5:5001/api/v0/version
                                                                            
HTTP/1.1 **405 Method Not Allowed**                                                     Allow: OPTIONS, POST
Content-Type: text/plain; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
Date: Sun, 20 Dec 2020 18:45:35 GMT
Content-Length: 25

**Comment by dapplion** [comment]
@Memoi Since some versions ago IPFS requires all API calls to be POST, so do
```
lion@lion-gram:~$ curl -X POST http://172.33.1.5:5001/api/v0/version
{"Version":"0.7.0","Commit":"","Repo":"10","System":"amd64/linux","Golang":"go1.14.4"}
```
