### ISSUE TITLE
Support > Report: Disk usage information is not clear

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DAppNode#233]
It seems that the Disk Usage information shown under Support > Report is not accurate and doesn't match the measure in the main dashboard. Screenshots below:

![image](https://user-images.githubusercontent.com/69941298/102781715-714e9f00-4398-11eb-857e-0034773fb3b7.png)

![image](https://user-images.githubusercontent.com/69941298/102781782-89262300-4398-11eb-9848-0fe1c3a205c1.png)

**Comment by dapplion** [comment]
To be fixed by this commit once new version releases https://github.com/dappnode/DNP_DAPPMANAGER/pull/500/commits/9fe6f304b216becb857a56f2cb4f17362c003daf
