### ISSUE TITLE
High Bandwidth Usage as Eth Validator running full geth node

### ISSUE THREAD

**Issue by wibi00** [dappnode/DAppNode#234]
Not necessarily an issue, but an trying to wrap my head around how to limit excessive bandwidth in a 1 TB/mo data cap scenario. I've seen a previous not about the Routing flag set to 'dhtclient', but that is set by default. Any other changes that can be made to DappNode setups to reduce bandwidth during geth sync and ETH validation?

*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **core.dnp.dappnode.eth**: 0.2.41
- **wifi.dnp.dappnode.eth**: 0.2.5
- **ipfs.dnp.dappnode.eth**: 0.2.12
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f
- **bind.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-2-amd64
- **Disk usage**: 364535349248

**Comment by ruvenni** [comment]
Hi @wibi00

I think this is a good question that should be better commented in the forum. Can you please post a topic there? https://forum.dappnode.io/

No sign-up required, you can use your Github or Discord user directly 😉
