### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#235]
Reviewing our repos there may be some opportunities to clean things up:

Add readme to
- [x] https://github.com/dappnode/DAppNodePackage-storj
- [x] https://github.com/dappnode/DAppNodePackage-swarm
- [x] https://github.com/dappnode/DAppNodePackage-openethereum
- [x] https://github.com/dappnode/DAppNodePackage-owncloud

Review if should be deleted
- [x] https://github.com/dappnode/dappnode-newsletter
- [x] https://github.com/dappnode/DNP_WAMP
- [x] https://github.com/dappnode/DAppNodePackage-goerli-parity
- [x] https://github.com/dappnode/DAppNodePackage-grin
- [x] https://github.com/dappnode/DAppNodePackage-goerli-pantheon
- [x] https://github.com/dappnode/DWeb_publisher
- [x] https://github.com/dappnode/go-ethereum
- [x] https://github.com/dappnode/DappnodePackage-block-explorer
- [x] https://github.com/dappnode/usbmount
- [x] https://github.com/dappnode/docker-alpine-glibc
- [x] https://github.com/dappnode/oasis-direct
- [x] https://github.com/dappnode/aragon
- [x] https://github.com/dappnode/nest

Remove Travis from branch protections
- [x] https://github.com/dappnode/DNP_WIFI

**Comment by dapplion** [comment]
@pablomendezroyo bump

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNodePackage-openethereum/pull/27 and https://github.com/dappnode/DAppNodePackage-owncloud/pull/4
