### ISSUE TITLE
v0.2.42 Release

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#237]
Release testing and progress tracker for `v0.2.42` release (https://github.com/dappnode/DNP_CORE/pull/63). Core packages release PRs:
- https://github.com/dappnode/DNP_DAPPMANAGER/pull/500 `v0.2.38`
- https://github.com/dappnode/DNP_VPN/pull/173 `v0.2.8`
- DNP_BIND - no changes `v0.2.6`
- DNP_IPFS - no changes `v0.2.14`
- WIFI - no changes `v0.2.5`

-----

**Comment by pablomendezroyo** [comment]
# DAppManager check

Every new release devs should verify the relase before publishing it. To do so this list can be used as a guide to avoid missing points to check.

**Please, take into account the changes implemented in the DAppManager when follow this guide.**

## DAppManager installation check
Dappmanager update must be verified taking into accouunt the following use cases.


### From the beggining
There are 2 main different cases where DAppNode can be installed from 0.
- [ ] Install DAppNode using the **ISO** image. 
- [ ] Install DAppNode using the **script** located at [this link](https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#how-to-install-dappnode-from-an-iso).

### From downstream
Once again, there are 2 main ways of dappmanager updating: from upstream to new release and from the new release to the "future" new release.
- [ ] **Update from upstream -> new release**: use the SDK to build the new version and install it by the IPFS.
- [ ] **Update from new release -> new "future" release**. Let say that the the new release will be 0.2.38, create a new fake relase 0.2.39 by editing the manifest and verify that the update works propertly.

### DNP_CORE update
DNP_CORE package is a package that contains information about the rest of the packages versions. Furthermore, It executes a few scripts needed for developers to make things work. The DNP_CORE package executes once during updates, then it gets stopped.

Users will update their dappnode via core update, this means that the DNP_CORE package will be updated with the new core packages versions, whose will be already posted in the blockchain.

When a core package, such as IPFS or VPN, is updated, the core package use to be updated as well, pointing to the new core packages versions. 

Taking all of these information into account:
- [ ] Verify you have the current core packages versions by ssh into your DAppNode and pasting the following command: `wget -qO - https://installer.dappnode.io | sudo UPDATE=true bash` 
- [ ] Check which core packages will suffer an update and take note of them.
- [ ] Execute`dappnodesdk build` in those core packages that will be updated.
- [ ] Copy IPFS of those core packages to be updated.
- [ ] Go to: DNP_CORE > dappnode_package.json > dependencies > **core package to be updated**. Paste the IPFS in the value field. ![](https://i.imgur.com/XaooLMQ.png)

- [ ] Install the DNP_CORE with the new core packages versions in your DAppNode and verify that the update works propertly. ![](https://i.imgur.com/IHLSfvp.png)




## UI check

- [ ] **Top right Nav bar**
    - [ ] **DAppNode identity**
        Make sure that the DAppNode identity is being displayed propertly.
        **Note:** When DAppNode is hosted in digital ocean or similar, the public IP use to be the same as the local IP, if the DAppNode is phisically at your home, IPs should be different.
        ![](https://i.imgur.com/QHGOfgU.png)
    - [ ] **Chain status**
        ![](https://i.imgur.com/N2Zzau6.png)
    - [ ] **Notifications**
        ![](https://i.imgur.com/0tTrYJ8.png)
    - [ ] **User info**
        ![](https://i.imgur.com/PrqyWlH.png)
- [ ] **Left Nav bar**
    - [ ] **Dashboard**
        - [ ] **Chains**
            ![](https://i.imgur.com/DsX8TIx.png)
        - [ ] **Machine stats**
            ![](https://i.imgur.com/OVkRGQp.png)
        - [ ] **Volumes**
            ![](https://i.imgur.com/cJnZAfM.png)
    - [ ] **Devices**
    - [ ] **DAppStore**
    - [ ] **Packages**
        - [ ] **My packages**
        - [ ] **System packages**
    - [ ] **System**
        - [ ] **Info**
        - [ ] **Notifications**
            Set valid/invalid telegram tokens. Switch on/off the bot and check UI responses.
        - [ ] **Security**
        - [ ] **Auto updates**
        - [ ] **Repository**
        - [ ] **Static IP**
        - [ ] **Peers**
        - [ ] **Profile**
        - [ ] **Advanced**
        - [ ] **Power**
    - [ ] **Sdk**
    - [ ] **Support**
        - [ ] **Auto Diagnose**
            ![](https://i.imgur.com/aoSpRuf.png)
        - [ ] **Report**
            Verify that the DAppNode information (Packages versions and System info) displayed is correct.
            Do a report with and without the information and verify that both options work fine by adding a new topic in the forum.
            ![](https://i.imgur.com/IUTitG7.png)
        - [ ] **Activity**
            Do an action, such as install a new package, and verify this action has been tracked in the history view.
            ![](https://i.imgur.com/vk7EewE.png)
            Download all the logs, and check they are correct.
    - [ ] **Logos**
        Click on every logo and make sure that the links still working. 
        ![](https://i.imgur.com/WiUfmWT.png)

- [ ] Different browsers
- [ ] Dev tools


## Backend check
Some checks of the backend will need to be able to login via ssh to the dappNode.

- [ ] **Database** 
    Database is located at the path: */usr/src/dappnode/DNCORE/maindb.json*.
    Verify that it sets/deletes/changes key-value pairs when required, to do that check the current telegram-status key value pair.
    ![](https://i.imgur.com/GxiBmE5.png)
    Now switch the telegram bot status and verify that the value has changed.
    ![](https://i.imgur.com/wm9VYGW.png)

- [ ] **Daemons**
    - [ ] **Disk usage**
        To reach the treshold setted in the disk space alert you may need to use the following command.
        `fallocate -l <space>G file`
            Set the space available in your DAppNode needed for reach the space treshold (<1GB), **never** less than 0. As described in the following image:
            ![](https://i.imgur.com/s04FuAK.png)
            Also you should have received the following notification in your DAppNode (top right in the UI)
            ![](https://i.imgur.com/Fio6clK.png)
            Lastly, you packages should be in status "stopped"
            ![](https://i.imgur.com/TBewT90.png)
    - [ ] **Telegram bot**
        Get a valid telegram token and save it, switch on the bot. Make a new telegram group and add the bot to it, write something and verify that the bot has added the channle ID to the database. Add more than one channel IDs.
        ![](https://i.imgur.com/Fw6APqI.png)
        write the command `/unsubscribe` and verify that the bot has removed the channel ID.
        - [ ] **Disk space notification**:
            To verify that the bot sends the notification successfully, follow the same instructions as the disk daemon, to reach the treshold defined for the disk space.
            
            You should have recieved a notification message via telegram identical to the following image. ![](https://i.imgur.com/yafaKVl.png)


    - [ ] **Check autoupdates**
