### ISSUE TITLE
Refactor Core Update

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#24]
#### Step 1. Who lets the DAppNodes know that a core update has to be done?

- Have a different core package in the repo which has no image and only depends on other core packages.
    - This package should be an almost empty image with a DockerFile and an entrypoint that does a docker-compose up of all cores. The old patch for the dappmanager will also do the same for redundancy.
    - Very fine control over when a new multiCore update is released. It allows a period of time where a new core package is pushed in the real repo but only DAppNode devs are able to consume it. I would allow a last chance of QA/testing without compromising user's DAppNodes.

#### Step 2. How is the installation carried out?

- Using the regular DAppmanager to install the AllCore package and then it does the docker-compose up.
    - TODO: What happens when you call docker-compose up TWICE at the same time on the same package? Test it as it can mess the idea. If it produces errors, choose one of the option.

#### Step 3. How to control the update from the ADMIN_UI

- In the UI single cores should not be displayed.
- In the UI, a global core package can be displayed in the dappstore or a core update can be handle in a completely different area.

**Comment by eduadiez** [comment]
Done
