### ISSUE TITLE
Hi everybody I just start with Dappnode can somebody take i look its everything ok in my Geth? (Deep froze chain segment) Thnx.

### ISSUE THREAD

**Issue by Varezz** [dappnode/DAppNode#240]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **ipfs.dnp.dappnode.eth**: 0.2.14
- **dappmanager.dnp.dappnode.eth**: 0.2.37, commit: 2b96e582
- **core.dnp.dappnode.eth**: 0.2.41
- **wifi.dnp.dappnode.eth**: 0.2.5
- **bind.dnp.dappnode.eth**: 0.2.6
- **vpn.dnp.dappnode.eth**: 0.2.7, commit: 12ae223f

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-5-amd64
- **Disk usage**: 360240381952
- 

> 
[logs-dappnode-package-DAppNodePackage-geth.dnp.dappnode.eth (1).txt](https://github.com/dappnode/DAppNode/files/5793283/logs-dappnode-package-DAppNodePackage-geth.dnp.dappnode.eth.1.txt)

**Comment by dapplion** [comment]
Logs look great, I don't think you have any issue :+1:
