### ISSUE TITLE
VPN use should be downgraded from first class feature into an expert level feature

### ISSUE THREAD

**Issue by olofedlund** [dappnode/DAppNode#242]
It should not be put in the way for novice users to get started.

The VPN is needed for remote control of the server. This is a small use case and can be considered an expert level requirement.

Ideally the user should be able to control the machine through his normal local network but if that can’t be achieved securely then the user should initially be directed to DAppNodeWifi, until he/she is ready to configure VPN.

**Comment by dapplion** [comment]
@olofedlund I like the proposal, it does make sense now for a lot of users. Initially, DAppnode did not had a WIFI option so VPN was the only way to connect.

@eduadiez @Pol-Lanski @pablomendezroyo would love to know your opinion

**Comment by pablomendezroyo** [comment]
Definetely VPN is something that is generating a lot of support. Sometimes non-advanced users have to do extra stuff (router config)  and thats annoying for them I guess, they should have as primary option to connect to their dappnode via wifi.

@olofedlund Totally agree with you!

**Comment by Zer0Wei** [comment]
Could be a flag in the install process where if wifi is enabled you can turn off the VPN.

**Comment by pablomendezroyo** [comment]
https://github.com/dappnode/DNP_DAPPMANAGER/issues/698 closes
