### ISSUE TITLE
Pleas help me, clean installation first run and what i can do ?

### ISSUE THREAD

**Issue by Varezz** [dappnode/DAppNode#244]
![20210111_201447.jpg](https://user-images.githubusercontent.com/77089849/104260729-adca6380-5449-11eb-8866-60eacc94dd80.jpg)
![Screenshot_20210111-204734_Video Player.jpg](https://user-images.githubusercontent.com/77089849/104263056-6a262880-544e-11eb-8dfe-9a45b98915aa.jpg)

**Comment by tomgetty** [comment]
I am also experiencing the same error when attempting to install on a NUC 10. I have tried on two different newer NUC hardware platforms and also enabled IPv6 on my LAN. No success with the same error as above.

**Comment by Varezz** [comment]
Hi this was installed on Sandisk plus ssd 2 TB failed,   but Samsung 680 pro 500GB working ok the same computer , anybody know what's wrong?

**Comment by Varezz** [comment]
Solved :  new ISO 0.2.39
1 and working good.

Thanks !  Pablo

**Comment by dapplion** [comment]
For other users landing on this issue:

----

:floppy_disk:  DAppNode ISO installation has been fixed!

Now you can try again installing DAppNode using the ISO method.
You can download the ISO from here https://github.com/dappnode/DAppNode/releases/download/v0.2.39/DAppNode-0.2.39.1-debian-bullseye-amd64.iso
