### ISSUE TITLE
Research: Improve DAppNode user accessing model

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#245]
1) Re-think how users access the Admin UI to manage the DAppNode. The VPN could become a secondary way in favor or simpler alternatives:
- Local WIFI. Must limit resources of other packages so syncing Prysm and Geth do not DOS the WIFI
- Expose the Admin UI to the router's local network
- Expose the Admin UI to the outside with a pre-generated password

2) Study the feasibility of removing the VPN from the mandatory core and being optional. It could manage devices on it's own UI and be completely standalone.

3) Research existing solutions for new UX ideas that solve the autonomous install on all situations problem.

**Comment by lukagulin** [comment]
> Local WIFI. Must limit resources of other packages so syncing Prysm and Geth do not DOS the WIFI

Have you taken a look at the `--cpu-shares` docker option? I think that could work. Docs are here: https://docs.docker.com/config/containers/resource_constraints/

**Comment by dapplion** [comment]
> > Local WIFI. Must limit resources of other packages so syncing Prysm and Geth do not DOS the WIFI
> 
> Have you taken a look at the `--cpu-shares` docker option? I think that could work. Docs are here: https://docs.docker.com/config/containers/resource_constraints/

Yes but we would need some serious research on what numbers to put since we want the other packages (validators) to perform and their maximum possible capacity.

**Comment by dapplion** [comment]
Implemented
