### ISSUE TITLE
Developing and testing on DAppNode: Watchtower

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#248]
As far as I concern, right now there are 3 main ways of developing and testing new features/realeses/branches... of DAppNode core packages:

1. Using the SDK: to build the ipfs and install the new version using the UI. This has been recently improved so the IPFS is generated automatically with github actions.
2. Watchgit: thanks to @dapplion, this repository checks periodically a core package branch set in a config file. So if there is a new push, this branch will be updated.
3. Update using the script: using the installer repository to update a core package. As an example: `sudo wget -O - https://installer.dappnode.io | sudo UPDATE=true VPN_VERSION=dev:pablo/fix bash`

As a new suggestion: there is something called [watchtower](https://hub.docker.com/r/v2tec/watchtower/), which "watches your containers and automatically restarts them whenever their image is refreshed".

I guess that the flow would be something similar to:

**github action in each core package publish its image in docker hub** > **developers configure watchtower in their dappnodes** > **watchtower updates when new image get published**

**Comment by dapplion** [comment]
@pablomendezroyo Please add this content to the DAPPMANGER README in a PR and reference this issue
