### ISSUE TITLE
Strict core release workflow

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#249]
The process to release a DAppNode core update could be sped up improving on:
- Tracking status better. Is is feature ready? Waiting to be test? Always assign a person to be responsible of a specific phase
- Automate processes where possible. ISO and test core version generation should be automatic
- Document changes and a way to test them in the repos itself. Consider committing in the DNP repo a markdown file with instructions to test all of their features. This doc must be updated in the same PR where features are added, removed or modified.

**Comment by pablomendezroyo** [comment]
I would say first 2 points are done. Add documentation to test the feature would be a nice to have.

Having a PR template in the core packages with a template to fullfill on how to test the PR to be implemented could be a solution? @dapplion

**Comment by dapplion** [comment]
I think we are good, not too sure about committing how to test the feature is a good idea. Would focus on doing strong PRs that include that info.
