### ISSUE TITLE
IPFS system package not working

### ISSUE THREAD

**Issue by imyjimmy** [dappnode/DAppNode#253]
**Description**
The IPFS system package is not working, and restarting it doesn't fix the problem:

The logs for this package has this message repeat
```
ipfs version 0.7.0
Found IPFS fs-repo at /data/ipfs
Error: failed to parse multiaddr "": empty multiaddr
```

**To Reproduce**

I'm not sure when this first occurred, but I think it was sometime after I set the BIOS settings to power up after a power outage and tested it by pulling the plug.

**Expected behavior**

IPFS should run normally and I should be able to browse the DAppStore

**Screenshots**

<img width="1568" alt="Screen Shot 2021-01-19 at 4 04 11 PM" src="https://user-images.githubusercontent.com/489440/105109108-ae2db480-5a70-11eb-8871-eebf8707d255.png">

(after clicking on Show Packages Still Propagating)
<img width="1568" alt="Screen Shot 2021-01-19 at 4 10 17 PM" src="https://user-images.githubusercontent.com/489440/105109186-e1704380-5a70-11eb-9ace-50e2b61936d3.png">

**DAppNode version:**

Core DAppNode Packages versions

    ipfs.dnp.dappnode.eth: 0.2.12
    dappmanager.dnp.dappnode.eth: 0.2.37, commit: 2b96e582
    core.dnp.dappnode.eth: 0.2.41
    wifi.dnp.dappnode.eth: 0.2.5
    bind.dnp.dappnode.eth: 0.2.6
    vpn.dnp.dappnode.eth: 0.2.7, commit: 12ae223f

System info

    docker version: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
    docker compose version: docker-compose version 1.25.5, build unknown
    platform: linux, x64, 5.9.0-5-amd64
    Disk usage: 363246859059

**Comment by pablomendezroyo** [comment]
hey @imyjimmy!
Before going further with your issue, could you try the following steps please:

1. Restart ipfs package: this can be done by going to Packages > System packages > click restart
![Screenshot from 2021-01-20 09-51-03](https://user-images.githubusercontent.com/41727368/105150429-0ca47280-5b05-11eb-9325-480f69a62e1a.png)

2. Reboot DAppNode

3. Update ipfs package: if you do not have access to the dappstore, you will have to connect to your DAppNode using the ssh. Once inside the terminal, execute the command: `wget -qO - https://installer.dappnode.io | IPFS_VERSION=0.2.14 sudo bash`
Wait for the installation to conclude.

4. Check that the ipfs version has changed (in the UI) to 0.2.14. Go to: Packages > SYstem packages > Ipfs > Config > set low power mode
This mode will consume less bandwidth (that may be the problem)

If previous steps did not solve your problem, contact us again. Paste the logs here for further support

**Comment by imyjimmy** [comment]
@pablomendezroyo that didn't work, installing SGX Modules failed:

![IMG_9277-min](https://user-images.githubusercontent.com/489440/105275049-4c924680-5b53-11eb-9193-e768935070f3.png)

**Comment by imyjimmy** [comment]
Hi, just wondering if there's any updates to this? Thanks

**Comment by pablomendezroyo** [comment]
> Hi, just wondering if there's any updates to this? Thanks

Hey @imyjimmy sorry for the response delay!

Other thing might be breaking ipfs in your dappnode is the internet provider you have or the router from your home.

Also double check that ports are propertly mapped to your dappnode local IP. For IPFS should be 4001 TCP and 4002 UDP

For further debuggin, you could do right click and click on **inspect** (other way is going to browser > settings > developer tools). Once inside in the **console tab** and/or in the **network tab** you should see some kind of error that might help to debug your issue.

**Comment by imyjimmy** [comment]
@pablomendezroyo no worries, this is a weekend project for me.

In terms of setting 4001 TCP and 4002 UDP I tried to do that through DappNode UI (Packages > System Packages > IPFS > Ports) However after it says "updated Ipfs port mappings" the Port screen is still blank.
<img width="1255" alt="Screen Shot 2021-02-28 at 23 06 58" src="https://user-images.githubusercontent.com/489440/109450932-301edf00-7a1a-11eb-9f23-bfe7a022ed40.png">

I am connected through LAN and not wifi, the internet settings have not changed, I'm still able to validate etc

In the network tab, a bunch of these: socket.io/?EIO=3&transport=polling&t=NVh_ULR failed, name not resolved.
In the console:

Error on checkCoreUpdate: Error: Error downloading core.dnp.dappnode.eth release from IPFS: Error downloading core.dnp.dappnode.eth release from IPFS: Ipfs hash [some hash] not available error

Main concern is, let's say I'm never able to get IPFS working, what's the worst that can happen--will there ever be a mandatory package upgrade for eth stakers?

Thanks

**Comment by ehariton** [comment]
Having a similar issue as described above. Ports 4001/4002 are setup to forward. Restarted IPFS / dappnode several times. Fully synced Geth node. 

```
Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
dappmanager.dnp.dappnode.eth: 0.2.38, commit: 85e2b4cf
ipfs.dnp.dappnode.eth: 0.2.14
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.6
System info
docker version: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
docker compose version: docker-compose version 1.25.5, build unknown
platform: linux, x64, 5.10.0-3-amd64
Disk usage: 25%
```
Auto-diagnose says:
> IPFS is not resolving: Error verifying IPFS: Failed to fetch

IPFS logs state:
> ipfs version 0.7.0
> Found IPFS fs-repo at /data/ipfs
> Error: failed to parse multiaddr "": empty multiaddr

Dapp store shows no packages. After clicking on packages still propagating and selecting Prysm it says:
`Error downloading prysm.dnp.dappnode.eth release from IPFS: Ipfs hash Qmb9pg6y3WmjTXMgxkwJbPiNYYq89CX67Bg496GibwyB4L not available error: request to http://ipfs.dappnode:5001/api/v0/object/stat?timeout=30000ms&arg=Qmb9pg6y3WmjTXMgxkwJbPiNYYq89CX67Bg496GibwyB4L failed, reason: connect EHOSTUNREACH 172.33.1.5:5001`

Details:
`Error: Error downloading prysm.dnp.dappnode.eth release from IPFS: Ipfs hash Qmb9pg6y3WmjTXMgxkwJbPiNYYq89CX67Bg496GibwyB4L not available error: request to http://ipfs.dappnode:5001/api/v0/object/stat?timeout=30000ms&arg=Qmb9pg6y3WmjTXMgxkwJbPiNYYq89CX67Bg496GibwyB4L failed, reason: connect EHOSTUNREACH 172.33.1.5:5001
    at objectSize_1.default.catch.e (/usr/src/app/webpack:/src/modules/ipfs/index.ts:27:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Error downloading prysm.dnp.dappnode.eth release from IPFS: Ipfs hash Qmb9pg6y3WmjTXMgxkwJbPiNYYq89CX67Bg496GibwyB4L not available error: request to http://ipfs.dappnode:5001/api/v0/object/stat?timeout=30000ms&arg=Qmb9pg6y3WmjTXMgxkwJbPiNYYq89CX67Bg496GibwyB4L failed, reason: connect EHOSTUNREACH 172.33.1.5:5001
    at http://my.dappnode/static/js/main.7c9afe49.chunk.js:1:295241
    at c (http://my.dappnode/static/js/2.50073e12.chunk.js:2:614670)
    at Generator._invoke (http://my.dappnode/static/js/2.50073e12.chunk.js:2:614423)
    at Generator.next (http://my.dappnode/static/js/2.50073e12.chunk.js:2:615029)
    at n (http://my.dappnode/static/js/2.50073e12.chunk.js:2:2567)
    at s (http://my.dappnode/static/js/2.50073e12.chunk.js:2:2770)
    at http://my.dappnode/static/js/2.50073e12.chunk.js:2:2829
    at new Promise (<anonymous>)
    at http://my.dappnode/static/js/2.50073e12.chunk.js:2:2710
    at d (http://my.dappnode/static/js/main.7c9afe49.chunk.js:1:295054)`

**Comment by imyjimmy** [comment]
I'm staking successfully even with this package down. 

So hopefully I will never have to upgrade, but I'd like to know if that's a likely scenario 👀

**Comment by pablomendezroyo** [comment]
IPFS issues are really hard to debug, thats why it will be an optional feature in dappnode from the next release https://github.com/dappnode/DNP_DAPPMANAGER/issues/833
