### ISSUE TITLE
WiFi password too long makes the package crash and no way to restart it.

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#254]
**Describe the bug**

If the password is set-up to be more than the maximum limit, the wifi package crashes, not allowing connection via Hotspot and locking new users who haven't set up the VPN yet out of their DAppNodes.

**To Reproduce**

1. Received New DAppNode
2. Follow the set-up steps of the UI wizard
3. Change WiFi password for a super long password (93 characters)
4. WiFi crashes, AdminUI connection is lost and does not generate a new hotspot. Rebooting doesn't fix.
5. Checking logs connecting to the host machine it shows: `Line 7: invalid WPA passphrase length 95 (expected 8..63)`

**Expected behavior**

If the password the user chooses is too long (more than 63 characters), the UI should reject and prompt the user for a valid one.

**Comment by Pol-Lanski** [comment]
Not sure if it's already handled, but it should do the same for passwords too short :)

**Comment by pablomendezroyo** [comment]
Issue identified for DNP_WIFI

https://github.com/dappnode/DNP_WIFI/issues/20
