### ISSUE TITLE
Include an option to edit the recovery token 

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNode#255]
Include an option to Edit the recovery token 

I think this is something we should discuss it.  The recovery token is not auto-generated after resetting the password. It's constant unless you change it manually from the file which contains that token.

User can change this value in case he suspects someone knows it. To change this value would be correct to ask the actual value of the token. 

However, I think it is a good idea to implement this. I would not include a way to recover or get the actual_recovery token using the UI.

**Comment by dapplion** [comment]
@tropicar Sounds good! Feel free to spec out and implement
