### ISSUE TITLE
Geth in light client mode does not find peers - update to Upstream v1.9.25

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#256]
**Describe the bug**

User @DerpDiggler in the forum reports not being able to sync geth in light client mode - it finds no peers. 

**To Reproduce**

1. Run Geth in light client mode.

I have been able to reproduce the error: it also does not work for me

**Expected behavior**

Geth light client finds peers and syncs.

**DAppNode version:**

- Package version: 0.1.12 (v1.9.24 upstream)

**Additional context**

The [new Geth version](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.25) includes a mention in its changelog about this topic:
- Light client peer discovery now uses DNS (#[21906](https://github.com/ethereum/go-ethereum/pull/21906))

Updating the new Geth could fix it.

**Comment by dapplion** [comment]
Have you personally tested that the new version works? I have experienced with Geth light client not ever finding peers

**Comment by Pol-Lanski** [comment]
Fixed.
