### ISSUE TITLE
Problem when downloading file

### ISSUE THREAD

**Issue by ligi** [dappnode/DAppNode#261]
We try do download a file from dappnode:

![Selection_437](https://user-images.githubusercontent.com/111600/105712266-d8242280-5f19-11eb-8012-af8410a73df9.png)

the link is then like this:

http://my.dappnode/file-download/DAppNodePackage-geth-fork-rinkeby.dnp.dappnode.eth/?path=/tmp/codedb.sqlite

but it seems to try to download test-dappnode-file and fails

![Selection_438](https://user-images.githubusercontent.com/111600/105712356-f38f2d80-5f19-11eb-8152-d7f8b2334a4d.png)

![Selection_439](https://user-images.githubusercontent.com/111600/105712409-09045780-5f1a-11eb-8d1c-a2c622f9aca7.png)

**Comment by ligi** [comment]
Fun fact: the problem only happens when the container is stopped. Maybe downloading should not be available in this case.
Btw.: we are searching for a way to stop the process in the container without stopping the container currently

**Comment by dapplion** [comment]
@pablomendezroyo Could you investigate the issue?

**Comment by pablomendezroyo** [comment]
@ligi Hey there!

I have checked myself stopping a random package, and then downloading a random file and it works.

When the file exists it downloads like the image

![Screenshot from 2021-01-25 18-14-17](https://user-images.githubusercontent.com/41727368/105740285-593ee200-5f39-11eb-9be1-6ab63e4dfe37.png)
When It does not exist it throws the following error

![Screenshot from 2021-01-25 18-14-39](https://user-images.githubusercontent.com/41727368/105740272-56dc8800-5f39-11eb-81d8-8c7a83ac8c93.png)

Are you pretty sure that file exists? 

You could verify that by connecting to your dappnode via ssh:
- `docker exec -it DAppNodePackage-<YOUR PACKAGE NAME>.dappnode.eth sh`
- Once inside: ` find /tmp -name "codedb.sqlite"

If it exists, then it occurs to me that it may be the size of the file to be downloaded

**Comment by ligi** [comment]
@pablomendezroyo yes the file exists - did you see this: https://github.com/dappnode/DAppNode/issues/261#issuecomment-766829536

**Comment by pablomendezroyo** [comment]
@ligi my bad, what happens exactly when you try to download the file? is there any error message on the screen when you attempt to download the file?

**Comment by ligi** [comment]
no - there is no error message - it tries to download  test-dappnode-file and fails

**Comment by pablomendezroyo** [comment]
@ligi It seems like that files in the tmp folder may be deleted when shutting down the container. It is a default behaviour of the Linux file system. If you want you may store that file in another folder so it keeps after a reboot. 

What is the application so I can debug your specific error?

**Comment by ligi** [comment]
@pablomendezroyo is that needed after the PR of @dapplion ?

**Comment by pablomendezroyo** [comment]
@ligi I guess yes, has nothing to do with this. Everything stored in tmp folder (temporary) will be removed when stopping the container unless you specify it as a persistent volume (I think). in docker.

**Comment by ligi** [comment]
The file is not deleted - I could copy it with `docker cp`

**Comment by dapplion** [comment]
@ligi If you can, could you install this dev version of the DAPPMANAGER which fixes the "test-dappnode-file" typo and try again? We should get a clearer error message to debug what's going on

https://github.com/dappnode/DNP_DAPPMANAGER/pull/596#issuecomment-767589441

**Comment by ligi** [comment]
Cool - this fixes the problem for me! Thanks @dapplion

**Comment by dapplion** [comment]
> Cool - this fixes the problem for me! Thanks @dapplion

Awesome! Please re-open the issue if you get more problems downloading files
