### ISSUE TITLE
.eth domains cannot be accessed when connected to DAppNode

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#262]
**Describe the bug**

DAppNode is supposed to allow users to access decentralized websites under the .eth domain. It does not work.

**To Reproduce**

Try to visit *some* .eth domain (dappnode.eth/) with a website behind does not resolve to the website.
decentral.eth *does* resolve.

**Expected behavior**

It takes me to the IPFS-hosted .eth website.

**Comment by ligi** [comment]
Interestingly it works for me:

![Selection_440](https://user-images.githubusercontent.com/111600/105842056-ee8fb400-5fd5-11eb-9f6c-e087635d3fde.png)
