### ISSUE TITLE
Switching Eth Full node stops and removes package

### ISSUE THREAD

**Issue by q9f** [dappnode/DAppNode#267]
**Describe the bug**
You can chose between Geth, OpenEthereum, and Nethermind as full-node provider.

If you have a fully synced Geth node, and want to switch to Nethermind, it does stop and remove the Geth package. It should give you the option to retain the Geth package.

Currently it only allows you to keep the Geth data (at least).

**To Reproduce**

1. Use DAppNode with full node, (e.g. Geth)
2. Switch Dropdown to Nethermind
3. Select "Keep" (data)
4. See that the Geth package was removed

**Expected behavior**

It should allow you to not only keep the data but also the package.

**Screenshots**

**DAppNode version:**

- Package version: Core 0.2.40

**Comment by pablomendezroyo** [comment]
Nice catch! this issue is already tracked by https://github.com/dappnode/DNP_DAPPMANAGER/pull/832

To be more precise at https://github.com/dappnode/DNP_DAPPMANAGER/pull/832/files#diff-409ecc0cc3cf03cc98df990d7efeef34715dc309e89e601b6dc103a6e2ae6ef6R47
