### ISSUE TITLE
Tornado Cash Relayer

### ISSUE THREAD

**Issue by luisalrp** [dappnode/DAppNode#268]
Tornado Cash Relayer can't be used as a custom relayer.

If you follow package steps after installation everything is ok until step 8, where you have to configure the tornado package relayer as custom relayer.

Two friends of mine tried it to ensure it was not my problem and they couldn't either.

I don't know if I should open ports on the router or maybe is a problem with the autosigned certificate.

Thanks!

**Comment by pablomendezroyo** [comment]
This issue should have been created at Tornado repository: https://github.com/dappnode/DNP_DAPPMANAGER/issues/850

**Comment by pablomendezroyo** [comment]
This issue should have been created at Tornado repository: https://github.com/dappnode/DNP_DAPPMANAGER/issues/850
