### ISSUE TITLE
Add a security feature on dappmanager for Prysm keystore's file

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNode#272]
The Keystore password is stored in the machine in plaintext in a file called 'walletpassword.txt'. This is not the best practice. 
Due to the prysm documentation [](https://docs.prylabs.network/docs/wallet/nondeterministic), the password to unlock this file should not be stored on disk by Prysm. It's recommended providing it anytime you start the validator or using the flag `--wallet-password-file`.

The reason why it's not stored on disk is for security. DappNode eliminates this security by storing the password in a text file. Not good.

**Describe the solution you'd like**

Users who want security should have an option to configure the package so that the password has to be entered manually every time the machine restarts.

**Comment by dapplion** [comment]
For this to work Prysm should do changes in their validator client so it doesn't crash in loop. The validator client expects the password to be available always on start-up once some validators have been imported.
