### ISSUE TITLE
Can’t load the DApp packages

### ISSUE THREAD

**Issue by frisir** [dappnode/DAppNode#274]
Need help

**Comment by pablomendezroyo** [comment]
Can you be more specific with your issue?

If you are referring to the DAppStore view, right now DAppStore is only available for those users running its own full node. Those users running remote client will have to wait until our server that provides the connection through the node supported by DAppNode gets fixed.

**Comment by frisir** [comment]
Thank you for answering. I am running a new dappnodeXtreme for a few days now. It is running fine now. Just needs time to set up and me getting to know. 
Is there the possibility to run an IDEXnode on the dappxtreme. For idex I need Ubuntu and a Docker. Cheers for your help. Grüße Hermann 

Von meinem iPhone gesendet

**Comment by pablomendezroyo** [comment]
@frisir there is no a DAppNode package for that project at this moment but you could propose that on our community platform Discord

**Comment by Pol-Lanski** [comment]
Hi @frisir , please drop by our [discord](https://discord.dappnode.io) or [forum](https://forum.dappnode.io) if you haven't been able to solve your issue yet!

**Comment by pablomendezroyo** [comment]
closed due to inactivity
