### ISSUE TITLE
Discussion: Move all Wiki content to docs

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#284]
Github Wiki has been alright to handle some content but it does not allow commits by external contributors and fragments our content. https://github.com/dappnode/DAppNode/wiki

**Should we move all our Github Wiki content to docs.dappnode.io?**
- YES: hit emoji :+1: 
- NO: hit emoji: :-1:

**Comment by tropicar** [comment]
I did a backup of the content of the wiki and the relevant content was moved to the docs already.
