### ISSUE TITLE
bee: Invalid (obsolete) threshold values

### ISSUE THREAD

**Issue by ldeffenb** [dappnode/DAppNode#288]
Please read the issue I've opened at https://github.com/ethersphere/bee/issues/1503

I downloaded the DAppNode bee .tar file from  /ipfs/bafybeifdy2o6jh2gjw4l4kn5j36mfvkdppjdlbazrphtop42worhesosy4 and found the following values in config.yml:

\# amount in BZZ below the peers payment threshold when we initiate settlement (default 10000)
payment-early: 10000
\# threshold in BZZ where you expect to get paid from your peers (default 100000)
payment-threshold: 100000
\# excess debt above payment threshold in BZZ where you disconnect from your peer (default 10000)
payment-tolerance: 10000

These values are too small for the current bee swarm to deliver a single chunk to one of these nodes.  They need to be increased to the (new) bee defaults of:

payment-early: "1000000000000"
payment-threshold: "10000000000000"
payment-tolerance: "50000000000000"

Once these values are set and the node is restarted, I suspect you'll see balances increase and settlements (checks) start to happen.

I don't know how DAppNode works, but if someone can put together and publish a guide for how to get these values entered, it would be good.  And to get the DAppNode bee distributable to have the proper values on the initial install.

**Comment by ldeffenb** [comment]
In actual fact, it would be better if the config.yml file only specified those values that need to be non-default.  That way as bee improves, values like this would not need to be changed...

**Comment by ldeffenb** [comment]
I just checked a few more parameters, and the swap-initial deposit is also too small:

\# initial deposit if deploying a new chequebook (default 100000000)
swap-initial-deposit: 100000000

should be:

swap-initial-deposit: "100000000000000000"

These parameters all date to the original token and were invalidated when the new gBZZ token was deployed with 16 decimal places.

**Comment by filoozom** [comment]
Related PR: https://github.com/dappnode/DAppNodePackage-bee/pull/19

**Comment by tropicar** [comment]
Fixed https://github.com/dappnode/DAppNodePackage-bee/pull/19
