### ISSUE TITLE
Connecting to your DAppNode refactor

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#291]
For pre-install connectivity UX improvements see https://github.com/dappnode/DAppNode/issues/292

----

See https://github.com/dappnode/DAppNode/issues/292 for context. A user may need to access their DAppNode from different network, from home, from an external network, etc. Historically DAppNode only offered a VPN to do so but now we have a bunch of more UX friendly options.

This issue is meant to track an effort to rethink how users can connect to DAppNode in easiest frictionless way possible. It is very important to fine tune how this different options are present to the user, providing safe sane defaults for non-technical people.

- [x] Create a table with different ways to connect. When they are available, pros, cons, etc.
- [x] Explain what we do now regarding offering this connection options to users.
- [x] Share ideas, thoughs and whishes on how an awesome onboarding experience would look like. Please don't be shy and drop a comment.

CC: @3alpha @Pol-Lanski @pablomendezroyo @tropicar @eduadiez

**Comment by pablomendezroyo** [comment]
### DAppNode connectivity refactor

I would say:
- Edit dappmanager view: 
   - Join all different ways of connections in a same view (HTTPS, wifi, wireguard, ssh, VPN)
   - Give **much more** importance to Wifi
- In the installer ?

**Comment by dapplion** [comment]
Implemented in current release :tada:
