### ISSUE TITLE
Onboarding DAppNode refactor

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#292]
Historically users have struggled with specific local network issues when installing DAppNode. Each user's network is different and each router is different making it hard to open P2P ports.

When DAppNode started in 2018 the only option we offered users to connect to their packages was via a VPN. However since then we have started to offer boxes that have an integrated WIFI antena, added mDNS discovery and setup a certificate server allowing secure encrypted connections.

This issue is meant to track an effort to rethink how users can onboard DAppNode in easiest frictionless way possible. Using this awesome new tools that now are available to us.

- [x] Create a table with different on-boarding strategies. When they are available, pros, cons, etc.
- [x] Explain in detail our current onboarding strategy for physical pre-installed DAppNodes, self-installed physical DAppNodes (ISO + script) and remote server DAppNodes.
- [x] Share ideas, thoughs and whishes on how an awesome onboarding experience would look like. Please don't be shy and drop a comment.

CC: @3alpha @Pol-Lanski @pablomendezroyo @tropicar @eduadiez 

----

For after-install connectivity UX improvements see https://github.com/dappnode/DAppNode/issues/291

**Comment by pablomendezroyo** [comment]
### How to improve users' onboarding?

I would say:
- Give more importance to WIFI when installing DAppNode from script/ISO
- Remove VPN step on https://welcome.dappnode.io/
- Edit the card that users receive on their dappnode's orders explaining the easiest and fastest way to connect to dappnode (I would say wifi)
- Move other connectivity ways (VPN, wireguard, SSH) to advanced/extra stuff

Thoughts?

**Comment by dapplion** [comment]
Implemented in current release :tada:
