### ISSUE TITLE
Terminal Access for Packages inside the Package Manager View

### ISSUE THREAD

**Issue by androolloyd** [dappnode/DAppNode#295]
**Describe the solution you'd like**
Terminal Access from the Package Log Screen
When viewing a package and its underlying service, having a terminal window tunnel right inside the package manager view would make checking and debugging things super easy.

Package Maintainers can define the shell command for the different packages inside the package manifest.

`"shellTunnels" : {
'serviceName1': '<shellCmd1>',
'serviceName2': '<shellCmd2>'
}
`

**Describe alternatives you've considered**
SSH alias scriping into the box for every time i wanna check something out on the services im installing

**Comment by dapplion** [comment]
We have considered this feature for a long time but decided against for security concerns. We have been able to help users in almost all situations without a shell. If some functionality really requires a shell we should find a way to integrate that functionality without a shell tunnel.

@androolloyd Please expand with some concrete examples that you see are important enough to offest the security risks.
