### ISSUE TITLE
Https connection fails at regular intervals

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#307]
**Describe the bug**

At regular intervals, the node exposed via HTTPS stops responding and returns 502: Bad Gateway (nginx)
Going to Network > HTTPS Portal and untoggling and toggling again (unexposing and exposing again) fixes it. 

**Expected behavior**

The node should be available consistently as some applications will depend on this to get their data. (i.e.: Rotki in an external machine different than the dappnode, or metamask).

**Screenshots**

<img width="282" alt="Screenshot 2021-07-01 at 08 31 59" src="https://user-images.githubusercontent.com/19168735/124076629-d15c8700-da46-11eb-8cc4-0dec9681ebbd.png">

**DAppNode version:**

## Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.47
dappmanager.dnp.dappnode.eth: 0.2.42, branch: v0.2.43, commit: ec541936
https.dnp.dappnode.eth: 0.1.1
ipfs.dnp.dappnode.eth: 0.2.14
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.7
## System info
dockerComposeVersion: 1.27.4
dockerServerVersion: 19.03.15
dockerCliVersion: 19.03.15
os: debian
versionCodename: buster
architecture: amd64
kernel: 4.19.0-13-amd64
Disk usage: 70%

**Comment by 3alpha** [comment]
We had that issue already: https://github.com/dappnode/DNP_DAPPMANAGER/issues/657

**Comment by dapplion** [comment]
> We had that issue already: [dappnode/DNP_DAPPMANAGER#657](https://github.com/dappnode/DNP_DAPPMANAGER/issues/657)

@3alpha right but we can't expect everyone to click that button always. Can we do something to prevent that from happening automatically?

**Comment by pablomendezroyo** [comment]
@3alpha @dapplion how can we know from the code point of view that is not working and need to be refreshed?

**Comment by dapplion** [comment]
> @3alpha @dapplion how can we know from the code point of view that is not working and need to be refreshed?

I'm not sure, @3alpha ?

**Comment by 3alpha** [comment]
I think it is issue with the public network, so we can probably find it that way, i.e. checking whether container is connected to public network.
