### ISSUE TITLE
New install connection trouble

### ISSUE THREAD

**Issue by CMTRACE** [dappnode/DAppNode#310]
Install from USB on exisiting dappnode extreme

- Boot machine
- install latest release
- set up defaults
- logon ok with both root and dappnode user accounts l
- reboot for good measure
- connect phone, or pc to dappnode wifi
- connects ok
- try to resolve http://my.dappnode as per documentation
Result fails to resolve
- flush client DNS reset adapter, restart machine etc 
- fails to resolve again
- disconnect from wifi hotspot 
- connect to local lan
- try resolve http(s)://dappnode.local
- fails to resolve
- find local IP from dappnode MAC address 
- try to connect with http(s) get asked to confirm insecure connection 
- page loads empty ERR_empty_reponse

Can't get VPN QR code, can't otherwise connect to dappnode

**Expected behavior**

Be able to follow the documentation and arrive at the logon screen or connect with VPN like in the older versions 

Running latest ISO

**Comment by pablomendezroyo** [comment]
Hi there!

OPENVPN is no longer the service installed by default on dappnode, it is WIREGUARD, which means you have to execute `dappnode_wireguard --qr`  to get the credentials

Hope this will be updated on the documentation ASAP
