### ISSUE TITLE
Add a better partitioning recipe

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNode#314]
Add a layout using `/var` partition instead of `/home`, as described here:

https://help.ubuntu.com/lts/installation-guide/armhf/apbs04.html

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380424962) by [Unito](https://www.unito.io)

**Comment by dsimog01** [comment]
There are no resources available to manage this currently
