### ISSUE TITLE
Installation process does not detect correctly if avahi and wifi are working

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNode#321]
**Describe the bug**

When dappnode is installed, the function dappnode_startup_delay is so fast, and some process is not finished. You will see on the installation logs:
* Wifi not available when it's created
* Avahi not available when it's working

Several messages related to access appears, all of them indicating they does not work. But after a while, it appear you will access via VPN and a qr with your credentials appears on the screen.

![arm_bug](https://user-images.githubusercontent.com/59098811/121342541-02eba200-c922-11eb-890a-afddc4cd03cb.jpg)

What it's happening is dappnode is checking too soon, before the containers are running. So there are false negatives. Avahi was working and wifi was working too. 

Avahi daemon was working but it does not work because using this installation method https package and wireguard are not installed.

**Comment by pablomendezroyo** [comment]
This script should be only executed on demmand. Commands refactor should take this script as a dappnode command instead of executing it by default
