### ISSUE TITLE
Show wireguard credentials in QR format by default

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#323]
The script `dappnode_access_credentials.sh` shows the wireguard credentials in text format. To be consistent with the format (Open VPN credentials are shown in QR format), there should be displayed wireguard creds in QR format

https://github.com/dappnode/DAppNode/blob/ff232d028dbc90372b4914cf319af6ce46e1fe16/scripts/dappnode_access_credentials.sh#L17

```
docker exec -i $WIREGUARD_CONTAINER getWireguardCredentials --qr
```

Then update dappnode users scripts through DNP_CORE

**Comment by dapplion** [comment]
Both are very useful depending on the situation. If you are connected by SSH you need text format to be able to copy it. QR codes are only useful when connecting keyboard + screen to an external host. We could offer both with a command or flag

**Comment by pablomendezroyo** [comment]
> Both are very useful depending on the situation. If you are connected by SSH you need text format to be able to copy it. QR codes are only useful when connecting keyboard + screen to an external host. We could offer both with a command or flag

Both of them are already contemplated with flags. The point is that the script `dappnode_access_credentials.sh` which is executed on dappnode startup show WIREGUARD credentials in text format. I think that this credentials should be shown by default in QR format to be consistent with the past (we have been showing OPENVPN credentials in QR format)

**Comment by pablomendezroyo** [comment]
users can figgure out easily how to get wireguard creds in QR format https://github.com/dappnode/DAppNode/pull/341
