### ISSUE TITLE
Sign releases in release content

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#332]
We want to be able to distribute releases with an IPFS hash directly or through lower trust distribution channels and be resilient against release corruption or malicious versions.

For that we should add a signature of a partial release inside the release directory. The signing key should be a well-known key distributed by the source and add a view in the UI to add and remove trusted keys. The DAPPMANAGER should verify the release directory hashes against the signature before downloading content.

A key should be attached to one or more packages specifically, or a range of packages
```
- `some-package.public.dappnode.eth:0xaaaabbbbaaaabbbbaaaabbbbaaaabbbb`
- `*.dnp.dappnode.eth:0xaaaabbbbaaaabbbbaaaabbbbaaaabbbb`
```

The SDK and publish UI should be expanded to support signing this data easily. We could use Metamask if we want to use the same key that publishes on chain since developers already have that key available. Note that ledgers don't allow to sign arbitary data with Ethereum keys, and can only sign regular transactions. The Metamask approach would only work when the private key is hold directly on the extension.

CC: @eduadiez 

## Developer / signer workflow

**Current DAppNode devs workflow**

Github actions prepare a "pre-release" with all files built, uploaded to IPFS and pinned. A transaction is crafted ready to be executed by the developer with permissions. All data is packed in a URL to a helper UI that will interact with Metamask to send the transaction. Example URL: https://dappnode.github.io/sdk-publish/?r=dappmanager.dnp.dappnode.eth&v=0.2.42&h=%2Fipfs%2FQmaonPyyb1N74GiPJLUjQ7E6sepmSSRi5VgSaZnn3YP16x

**Proposed DAppNode devs workflow**

The address holder must now:
1. Sign the release files
2. Generate a new release hash after uploading the signature with the release to IPFS (again)
3. Publish this new release hash to the blockchain as canonical release hash.
4. Pin the new release hash.
5. Update the Github release with the signature and new IPFS hash.

Now the dappnode.github.io/sdk-publish must be stateful to be able to publish and persist the new content to IPFS. The UI could request the user credentials to an IPFS node, or to Pinata and keep them in local storage. After signature, do a request to upload the content (if CORS and mixed-content allow) and craft the resulting transaction with the new hash.

A separate bot must subscribe to the release distribution channel (i.e. the blockchain) and when the new release is detected, update the Github release with the signature and the new release hash. Plus mark the release as final and in production, consider adding the publish transaction.

## Signed content format

Signed content must be re-create-table deterministically. A rough spec for it:

Given an IPFS UnixFS directory:
```json
[
  {
    "Name": "avatar.png",
    "Hash": "QmTfnrUdZWaMgr2Zi1h1Z7zS5CbYtQZRs72yqKZQHj5fxT",
    "Size": 23107
  },
  {
    "Name": "dappnode_package.json",
    "Hash": "QmTRKT4oBef93Xdyvm2VRoPvhRN2HnUPvHuJ9PpSpEjdYw",
    "Size": 1645
  },
]
```

1. Pick a specific CID version, base and codec. In this example v0, base58btc, dag-pb.
2. Convert all the entries hashes to those choices.
3. Sort entries in alphabetical descending order, following `us-ascii` ordering (safe sorting for all possible characters?)
4. Concat the strings of the entries `.Name` and `.Hash`, then concat all entries respecting the ordering above.

```
hash("avatar.png" | "QmTfnrUdZWaMgr2Zi1h1Z7zS5CbYtQZRs72yqKZQHj5fxT" | "dappnode_package.json" | "QmTRKT4oBef93Xdyvm2VRoPvhRN2HnUPvHuJ9PpSpEjdYw")
```

## Signature distribution format

The signature must be added to a new UnixFS directory that includes all previous files + `signature.json`. The format of `signature.json` is

```json
{
  "version": 1,
  "cid": {
    "version": "v0",
    "base": "base58btc"
  },
  "signature_protocol": "ECDSA_256",
  "signature": "0xdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
}
```

- `version`: Versioning of the DAppNode release signature scheme. Future proofing so far only supports 1.
  - version 1: As described in this document
- `cid`: Format of the CID of each directory entry. See https://github.com/multiformats/cid for available formats
- `signature_protocol`: Signature protocol to allow multiple signature algorithms and formats.
  - `ECDSA_256`: To integrate with existing Ethereum wallets such as Metamask
  - `RSA_2048`: For IPNS integrations
  - `OpenPGP`: Standard protocol to sign releases
- `signature`: Hex encoded (with 0x prefix) of the resulting signature.

------

TODO:

- [ ] How to add a new entry to an IPFS UnixFS directory without having to re-upload all the contents?
- [ ] Can a stand-alone browser hit the IPFS API and the Pinata API?
- [ ] What signed content format works well with Metamask API? Such that signers are properly informed of the content to sign.
- [ ] How would a CLI only flow look like?
- [ ] How could this be integrated in CI if the developer accepts to submit the private key to the CI runner?

**Comment by alexpeterson91** [comment]
@dapplion Csn you comment on if this can be closed? It seems you merged s few things but this issue is still open. Should it be reassigned or has it been resolved in some way?

**Comment by dapplion** [comment]
Resolved
