### ISSUE TITLE
OpenEthereum not correctly feeding repository info?

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#333]
As reported by GBeast:
Okay - Here is a bizarre one. This guy was not getting updates in the DAppStore. I was trying different alternatives. Then he changed his default client from OpenEthereum to Geth, and suddenly his DAppStore recognized all the new package updates.
Update by nustaker:
Hi, I finally managed to get OpenEthereum to update.  I had to toggle the repository to Geth, uninstall OpenEthereum, and toggle back to Open Ethereum and reinstall.  Nearly sync'd now, looks like we're on the right track now.    Prysm also just managed to auto update itself this AM.  thx.

Needs to be investigated

**Comment by dapplion** [comment]
Is OpenEthereum still capable of progressing Mainnet?
