### ISSUE TITLE
DAppNode commands refactor

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#338]
The current available commands are described in the `.dappnode_profile`:
- `dappnode_stop`
- `dappnode_start`
- `dappnode_connect`
- `dappnode_wireguard`
- `dappnode_wifi`

Furthermore, its been executed the script `dappnode_access_credentials.sh` on startup, which sometimes is not ideal.

## New approach

- Consider rename `dappnode_connect` to `dappnode_openvpn`
- Consider having command `dappnode_connect` to execute `dappnode_access_credentials.sh` script to get the connectivity method available
- Consider having `dappnode_help` to display all commands available: https://github.com/dappnode/DAppNode/issues/320
- Consider removing executing `dappnode_access_credenitals.sh` on startup
- Consider displaying a new message on startup, asking the user to execute `dappnode_help` so the user can decide what action to take

**Comment by 3alpha** [comment]
This seems very sensible.

**Comment by pablomendezroyo** [comment]
The current approach is not correct and should be improved. We should have also well documented all commands available. Also command names must be consistent, right now some they are confusing. Also having a help command should be mandatory for users. Lastly, the script `dappnode_access_credentials.sh` should not be executed by default but on demmand
