### ISSUE TITLE
motd is printed twice when ssh

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#344]
### ISSUE
The motd logo of DAppNode is printed twice when ssh into dappnode
![image](https://user-images.githubusercontent.com/41727368/130940097-5ef54a4c-c67d-4930-81fb-4c9f3651cc67.png)

### Fix
To solve this bug there must be edited the config file `/etc/ssh/sshd_config `
hashing out the following lines:

```
#session    optional     pam_motd.so  motd=/run/motd.dynamic
#session    optional     pam_motd.so noupdate
```

![image](https://user-images.githubusercontent.com/41727368/130940280-dca9014a-01e7-488f-920d-757ab88e7f49.png)

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380382408) by [Unito](https://www.unito.io)

**Comment by 3alpha** [comment]
Was this resolved with new installer? I don't get it twice.

**Comment by vorburger** [comment]
@pablomendezroyo I think this issue can be closed now? `/etc/ssh/sshd_config` (now) has `PrintMotd no`.
