### ISSUE TITLE
Research for a workaround if `dappnode_install_pre.sh` fails during installation

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#345]
When `dappnode_install_pre.sh` fails there should be defined a workaround to do, this is something critical specially for dappnode purchased by dappnode org

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380381802) by [Unito](https://www.unito.io)

**Comment by alexpeterson91** [comment]
This remains unaddressed AFIK
