### ISSUE TITLE
vps installation

### ISSUE THREAD

**Issue by rafalohaki** [dappnode/DAppNode#361]
Can it be installed and configured on vps for example with debian?
And access via browser.

**Comment by tropicar** [comment]
Yes, you could install it in a VPS, but the way to access you should access via VPN (OpenVPN or Wireguard). I mean, you connect to via VPN and access via browser to the UI. The UI is not exposed to the internet global network.

**Comment by rafalohaki** [comment]
![image](https://user-images.githubusercontent.com/20607107/135645702-a3064dff-76f8-4544-a163-f5c0195401f3.png)
is there a way to change ports?

**Comment by pablomendezroyo** [comment]
Hi there,

This is a great report of a failure while installing dappnode.

@3alpha @tropicar The OpenVpn package port was in use during installation, we should include a rollback to install the Wireguard package in that case.

If the Wireguard package is also in use, warn the user there is no VPN solution installed

**Comment by 3alpha** [comment]
True, and until then we should include in installation instructions what ports need to be available.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNode/issues/377
