### ISSUE TITLE
Display amber alert if beacon node is running in failover

### ISSUE THREAD

**Issue by CMTRACE** [dappnode/DAppNode#365]
Searching logs very far back doesn't seem to show my beacon node as running in failover mode. However when looking at infura directly I see thousands of requests per day.

Solution:
If local execution client is green, but the beacon node is using infura or alchemy display a yellow alert, send a telegram message
 
I suppose DMS could also handle this somehow but it has lots of issues too and is pretty slow to get fixed. syslog would also work but doesn't exist yet. Having telegram notifications would be icing on the cake.

**Comment by CMTRACE** [comment]
> That would be very useful to know but I'm not sure how DAppNode could query Prysm to know which beacon node it's using. First Prysm should expose that info somehow. Otherwise it would be hard for DAppNode too to quantify if the execution client it's being used. I'm not sure if Geth exposes that information either.
> 
> 
> 
> 
I guess these messages could be used from the Prysm BC


level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: Post "http://geth.dappnode:8545": dial tcp: connect: connection refused"

Level=info msg="Falling back to alternative endpoint: https://mainnet.infura.io/" prefix=powchain

level=info msg="Connected to eth1 proof-of-work chain" endpoint="https://mainnet.infura.io/" prefix=powchain

level=info msg="Primary endpoint ready again, switching back to it" prefix=powchain

Because they are log triggered perhaps having a reset function would be good if the "resolved" messages are missed, for instance in the event the client is restarted

**Comment by dapplion** [comment]
Not a huge fan of parsing logs directly since it's hard to mantain long term. Maybe Prysm could expose this information through a custom API endpoint?

**Comment by alexpeterson91** [comment]
> Not a huge fan of parsing logs directly since it's hard to mantain long term. Maybe Prysm could expose this information through a custom API endpoint?

I've spoken to the Prysmatic team and they are aware of this as a request and is on their plan/roadmap but from my talks it seems to be quite low priority. compared to other things like upgrading the UI and getting the web3signer API done (which has now started btw ;) )

**Comment by CMTRACE** [comment]
> > Not a huge fan of parsing logs directly since it's hard to mantain long term. Maybe Prysm could expose this information through a custom API endpoint?
> 
> 
> 
> I've spoken to the Prysmatic team and they are aware of this as a request and is on their plan/roadmap but from my talks it seems to be quite low priority. compared to other things like upgrading the UI and getting the web3signer API done (which has now started btw ;) )

By the time the merge comes it is probably far less important unless there's some dappnode specific EL failover between nodes

**Comment by alexpeterson91** [comment]
This should take care of this request.  Prysm is on it.  https://github.com/prysmaticlabs/prysm/issues/9972

**Comment by dapplion** [comment]
I see https://github.com/prysmaticlabs/prysm/issues/9972 closed, should be ready to add here!

Usage from impl PR https://github.com/prysmaticlabs/prysm/pull/10073#issuecomment-1011356404
```
curl http://localhost:3500/eth/v1alpha1/node/eth1/connections
{"currentAddress":"http://localhost:8545","currentConnectionError":"Post \"http://localhost:8545\": dial tcp [::1]:8545: connect: connection refused","addresses":["http://localhost:8545"],"connectionErrors":["Post \"http://localhost:8545\": dial tcp [::1]:8545: connect: connection refused"]}%  
```
