### ISSUE TITLE
ISSUE on wiki

### ISSUE THREAD

**Issue by wimel** [dappnode/DAppNode#370]
On wiki in the part of [Post-installation](https://docs.dappnode.io/get-started/installation/custom-hardware/installation/script/#post-installation) the link for `wireguard` and `OpenVPN` are broken, redirect to `https://docs.dappnode.io/get-started/user-guide/ui/access/vpn#wireguard` and `https://docs.dappnode.io/get-started/user-guide/ui/access/vpn#openvpn` but give the error
```
Oh oh... You probably weren't looking for this.
We've changed the documentation to serve you better and we might have broken this link.

If you got here following one of our links, please report the broken link here.

Back to homepage
```

> Steps to reproduce:

Go to [wiki](https://docs.dappnode.io/get-started/installation/custom-hardware/installation/script/#post-installation) and push `Wireguard` or `OpenVPN`.

![dapBugg](https://user-images.githubusercontent.com/17170149/142243023-01a9939c-9284-4109-8af4-d8ec1ab4ff12.png)
![dappbug2](https://user-images.githubusercontent.com/17170149/142243111-409d28eb-b6eb-42d8-9e0a-909d2a6cc951.png)

Thanks for all!!

**Comment by H4RDSTYLE** [comment]
Checking the issue I´ve seen that buttons Wifi and Local Proxy dont work neither

**Comment by H4RDSTYLE** [comment]
@tropicar I think the links should point to:
Local Proxy -> https://docs.dappnode.io/user-guide/ui/access/local-proxy
Wifi -> https://docs.dappnode.io/user-guide/ui/access/wifi
Wireguard -> https://docs.dappnode.io/user-guide/ui/access/vpn#wireguard
OpenVPN -> https://docs.dappnode.io/user-guide/ui/access/vpn#openvpn
