### ISSUE TITLE
Instructions during script installation seem incomplete

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DAppNode#371]
Instructions during script installation seem incomplete:

```
/usr/src/dappnode/scripts/dappnode_access_credentials.sh               100%[=========================================================================================================================================================================>]   3.96K  --.-KB/s    in 0s      
Execute dappnode_help to see a full list with commands available
root@LionDynamics ~ # dappnode_help
dappnode_help: command not found
```

You need to run `$source .profile` o exit an re-enter to the terminal to be able to run `dappnode_help`

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380376549) by [Unito](https://www.unito.io)

**Comment by pablomendezroyo** [comment]
@ alexgonmad @dsimog01 @Marketen This is a good first issue for the dappnode installer

**Comment by dsimog01** [comment]
I have already reviewed this to reproduce the error and it looks like it is just a matter of re-opening the terminal or rebooting the device to complete the installation process. I think this issue can be closed now.
