### ISSUE TITLE
Can not update Core package - Core package core.dnp.dappnode.eth is from a foreign registry

### ISSUE THREAD

**Issue by SKFrozenCloud** [dappnode/DAppNode#373]
**Describe the bug**
Can not update core package to version 0.2.50

I set up the Dappnode on a custom computer in February of 2021.
I enabled auto-update and have let it update everything automatically.
But I can not update the core package manually nor automatically.

I have tried to switch between remote IPFS and local IPFS but to no avail.

![image](https://user-images.githubusercontent.com/39242670/145993949-66b22663-6e40-44b9-a28e-d6a2eaf1a5a6.png)

**To Reproduce**

1. I press update:
![image](https://user-images.githubusercontent.com/39242670/145994170-fd95661f-f660-46f2-88ef-ebb6e86d4e68.png)

2. After a while I get this error in the corner:
![image](https://user-images.githubusercontent.com/39242670/145994279-7b56417a-9e08-4d8d-a38e-3ff2ffc81fa4.png)

**Expected behavior**

It should update the core package.

**Screenshots**

See above

**DAppNode version:**

- Package version: 0.2.44
- OS: Dappnode
- Browser Firefox

Core DAppNode Packages versions

bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.49
dappmanager.dnp.dappnode.eth: 0.2.44, commit: 7c9a6772
ipfs.dnp.dappnode.eth: 0.2.15
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.8

System info

dockerComposeVersion: 1.25.5
dockerServerVersion: 19.03.8
dockerCliVersion: 19.03.8
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.9.0-5-amd64
Disk usage: 66%

**Additional context**

**Comment by pablomendezroyo** [comment]
Hi there!

To fix this issue you must update your dappnode at **http://my.dappnode/#/system/update**

Once updated the auto-updates will work as usual

More info at https://forum.dappnode.io/t/update-to-core-0-2-50-fails-with-package-from-foreign-registry/1336
