### ISSUE TITLE
Record video tutorial with screen capture and voice over, how to decentralize websites. 

### ISSUE THREAD

**Issue by YalorMewn** [dappnode/DAppNode#38]
We are looking forward to having many different kinds of tutorials of how to smooth the process of developing the decentralized web. 

For this issue we would like [This medium post](https://medium.com/@DAppNode/how-to-decentralize-wallet-ethereum-org-with-dappnode-242ec8e4d9fd) turned into a high quality video tutorial with a screen capture of the process and voice over. Preferably using a different example other than an Ethereum wallet. Such as migrate your decentralized web, converting an existing websites into a decentralized site.

**Comment by dapplion** [comment]
Good idea, we should start by outlining a script with a very easy simple example.

- [ ] Choose easy simple relatable example web -> dweb case
- [ ] Write script
- [ ] Record video and voiceover

**Comment by YalorMewn** [comment]
Started this bounty https://explorer.bounties.network/bounty/1778 to resolve this issue.

**Comment by Anish-Agnihotri** [comment]
Hey folks! Bumping this thread to see if any progress was made on the bounty? It shows up as `Dead` with the only submission being `Not Accepted`.

If you'd still like some help with this, I'd be more than happy to record and edit a tutorial over the next couple of days.

**Comment by vdo** [comment]
We already have a workshop tutorial for this, closing issue.
