### ISSUE TITLE
Trouble Exposing Nethermind xDAI via HTTPS

### ISSUE THREAD

**Issue by bh2smith** [dappnode/DAppNode#385]
**Describe the bug**

I am able to configure a subdomain in `Package > Nethermind > Networks` (http://my.dappnode/#/packages/nethermind-xdai.dnp.dappnode.eth/network)

but this never appears in the system networks (http://my.dappnode/#/system/network)

I have the HTTPS package installed and have exposed port 443 on my router. Continue to get Bad Gateway when trying to access my node via the configured subdomain.

**To Reproduce**

1. Install Nethermind xDAI
2. Navigate to networks tab and create "HTTPs domain mapping" - http://my.dappnode/#/packages/nethermind-xdai.dnp.dappnode.eth/network

![Screenshot 2022-02-07 at 9 11 34 AM](https://user-images.githubusercontent.com/11778116/152749482-0b3950bc-8543-4ebc-a433-a2ff2296455d.png)

3. Navigate to system networks tab http://my.dappnode/#/system/network
4. Find that there are no clickable options available:

![Screenshot 2022-02-07 at 9 10 57 AM](https://user-images.githubusercontent.com/11778116/152749300-4a253ea6-e804-4627-958b-2d362c2920c2.png)

**Expected behavior**
I would expect to get a JSON RPC endpoint when visiting the configured URL 

![Screenshot 2022-02-07 at 9 13 20 AM](https://user-images.githubusercontent.com/11778116/152749699-a31b6ccc-8037-4a47-99f5-db7121fba166.png)

Instead, I get Bad Gateway:
![Screenshot 2022-02-07 at 9 13 36 AM](https://user-images.githubusercontent.com/11778116/152749745-cfdbaacd-6871-47d4-b504-8a638af66763.png)

**Additional context**

I have been in contact with @eduadiez regarding this issue who suggested that I tag 3alpha (who does not appear to exist here).

**Comment by eduadiez** [comment]
@3alpha please, could you check this?

**Comment by 3alpha** [comment]
Port 8545 should be forwarded instead of port 80. There is an issue (@alexpeterson91) to add Nethermind xDAI to the list of pre-approved packages so people won't have to bother with that.

**Comment by bh2smith** [comment]
@alexpeterson91 - I see that this was closed, but then the fix was reverted... Is this still an issue or not?

**Comment by alexpeterson91** [comment]
The requested changes broke the install, added too many parameters that it wouldn’t install so I had to revert it was going to be testing it right then but I’ve had all kinds of stuff messing up my life and ability to work. Since then Anyways I’ll finish testing today and will have a version ready for publishing by end of day. But the nethermind packages still have major memory and cpu leaks. The testing upstream of the refactored nethermind had similar resource issues and the same progress bar issue.

**Comment by bh2smith** [comment]
Thanks for the update. I have also been experiencing issues with the memory leak and have to restart my services regularly (at least once per day to calm down my machine). Looking forward to both updates!

**Comment by alexpeterson91** [comment]
> Thanks for the update. I have also been experiencing issues with the memory leak and have to restart my services regularly (at least once per day to calm down my machine). Looking forward to both updates!

This is a long known issue and is not specific to xDai it's a nethermind issue and it's upstream so we're waiting on a fix from the nethermind team as are basically all other users. 
So far we have no better solution to the cpu and or memory leaks from nethermind than restarting the package. Which is not what we want but the issue isn't ours to fix. Though we are closely tracking progress.
