### ISSUE TITLE
Track Eth2 clients

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#389]
Eth2 clients have been progressing their support on the web3signer. This issue aims to track the web3signer support in each Eth2 client as well as the main features required to make them work

<center>

| Eth2 client |     [web3signer](https://eips.ethereum.org/EIPS/eip-3030)     | [Remote keymanager API](https://ethereum.github.io/keymanager-APIs/) | Checkpoint sync | Fee recipient API [ref](https://github.com/ethereum/keymanager-APIs/pull/24) | Separated services |  Gnosis-chain |
|:----------- |:------------------:|:----------------------------------------:|:----------------------:|:--------:|:--------:|:--------:|
| Prysm       |      :heavy_check_mark:      |   :heavy_check_mark: [ref](https://github.com/prysmaticlabs/prysm/commit/64f64f06bf198c08b5fdc96eaff73189125f1ea6)  |  :rocket: [ref](https://docs.prylabs.network/docs/devtools/init-state/) | :rocket: [ref](https://github.com/prysmaticlabs/prysm/issues/10292) | :heavy_check_mark: | :heavy_check_mark:  |
| Teku | :heavy_check_mark: | :rocket: |  :heavy_check_mark: [ref](https://docs.teku.consensys.net/en/latest/HowTo/Get-Started/Checkpoint-Start/) | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: [early-stage](https://github.com/ConsenSys/teku/releases/tag/22.4.0) | 
| Lighthouse  | :heavy_check_mark: | :heavy_check_mark:  *Not following standard   [ref](https://lighthouse-book.sigmaprime.io/api-vc.html)   | :heavy_check_mark: [ref](https://lighthouse-book.sigmaprime.io/checkpoint-sync.html) | :heavy_check_mark: |:heavy_check_mark: | :heavy_check_mark:| 
| Nimbus | :heavy_check_mark: |   :rocket: [ref](https://nimbus.guide/keymanager-api.html) | :grey_question: | :grey_question: | :x: [ref](https://github.com/status-im/nimbus-eth2/issues/3088) | :heavy_check_mark: |
| Lodestar | :heavy_check_mark: |  :grey_question:   | :grey_question: | :grey_question:| :grey_question: |  :x:  | 
| web3signer | -  |  :heavy_check_mark: | - | - | - | :rocket: |

</center>

#### DAppNode needs
* **web3signer**: would allow to easily switch between clients, letting users switch the client they are using to validate and not rely just on Prysm.
* **Remote keymanager API**: would allow to import/delete keystores on validator services on the fly without having to restart the service.
* **Checkpoint sync**: this path is very important for dappnode users due to the high host resources consumption when syncing from genesis.
* **Fee recipient API**: something to be implemented for the Bellatrix merge.
* **Separated services**: to avoid spamming web3signer is very important to have beacon and validator as separated services, allowing to keep syncing beacon while having validator stopped.
* **Gnosis-chain**: the gnosis chain support is crucial for dappnode and dappnode users and clients should be pushed to support it.

#### References
* [Road to eth2 multiclients in DAppNode](https://github.com/dappnode/DAppNode/issues/329)
* [web3signer docs](https://docs.web3signer.consensys.net/en/latest/)
* [Teku docs](https://docs.teku.consensys.net/en/latest/)
* [Prysm docs](https://docs.prylabs.network/docs/prysm-usage/parameters/)
* [Lighthouse docs](https://lighthouse-book.sigmaprime.io/)
* [Nimbus docs](https://nimbus.guide/e)

cc: dapplion mgarciate eduadiez @Pol-Lanski

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380371268) by [Unito](https://www.unito.io)

**Comment by james-prysm** [comment]
- teku https://github.com/ConsenSys/teku/pull/4642
- teku  https://github.com/ConsenSys/teku/pull/4894
- teku https://github.com/ConsenSys/teku/pull/4863
- lighthouse https://github.com/sigp/lighthouse/pull/2924/files
- lighthouse https://github.com/sigp/lighthouse/pull/2884/files

here are some reference prs for teku and lighthouse

**Comment by pablomendezroyo** [comment]
Implemented
