### ISSUE TITLE
Consider removing `BUILD` option from installer

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#394]
## Context

The `BUILD` option in the installer is a flag used to generate the dappnode core packages with the versions based on the `.dappnode_profile`

This option is used nowhere and does not work at all right now (see https://github.com/dappnode/DAppNode/issues/386), since it attempts to clone all the repositories from github and switch to the git branch of the version specified, which may not exist.

Consider removing this option 

## References
- Set env in compose at https://github.com/dappnode/DAppNode/blob/724a45885af8d981c4ab05b586286af1328c38b5/docker-compose.yml#L8
- Script executed if `BUILD=true` https://github.com/dappnode/DAppNode/blob/master/iso/scripts/generate_docker_images.sh

**Comment by dapplion** [comment]
I think we can remove @eduadiez is anyone using this still?
