### ISSUE TITLE
Eth2 migration 

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#398]
## Context
DAppNode will migrate from validating on Ethereum with Prysm -non-web3signer to validate with almost any available client with web3signer. This process must be done carefully taking into account all the edge cases.

### Approach 1: Dappmanager will handle the migration 
- Implementation: https://github.com/dappnode/DNP_DAPPMANAGER/pull/936
- This migration will be manually triggered by the user
- There are contemplated all the clients to migrate to

**Pros**
- Full control of the process, using strong types, and more.
- Easy rollback implementation
- Integration tests implemented

**Cons**
- Really complicated process, a big PR
- This migration takes longer in time than others
- Use of many intermediaries: intermedium containers, docker volumes, docker images, the dappmanager...
- Usually, the more complicated the more edge cases

### Approach 2: Prysm will handle the migration  
- Implementation: https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/37
- Package will have the web3signe as dependencies
- Package will have a breaking change, making users do a normal update from the dappstore UI
- Only migration to Prysm contemplated

**Pros**
- Really simple process, Prysm will update itself
- No intermediaries in the process
- Fewer edge cases than other approaches
- Quick migration process in time

**Cons**
- The few existing edge cases are dangerous and must be handled in deep
- More difficult to implement a rollback

### Approach 3: Prysm + dappmanager will handle the migration
- Implementation: to be done
- Use of Prysm orphan containers to trigger the migration from the dappmanager

**Comment by alexpeterson91** [comment]
Completed in other issues in production issue resolved.
