### ISSUE TITLE
Automate releases with a CI

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#40]
Script to upload a release asset using the GitHub API v3.
https://gist.github.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447

Semantic release CI configuration
https://github.com/semantic-release/semantic-release/blob/HEAD/docs/usage/ci-configuration.md#ci-configuration

**Comment by eduadiez** [comment]
We've started to integrate it in all our repos
