### ISSUE TITLE
Set extra package to be installed in the ISO 

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#401]
## Context 
In DAppNode there are many partnerships with other projects such as GNOSIS, eventually this partnerships would require to sell DAppNodes with the package of such project already installed by default in DAppNode.

## Proposal
Would be easy to implement to add a new optional variable in the `release.yml` to select a package or list of packages to be installed in another asset ISO to be included in the release. This ISO will contain the extra package installed by default

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380368728) by [Unito](https://www.unito.io)

**Comment by Pol-Lanski** [comment]
100% yes

**Comment by alexpeterson91** [comment]
Can we include the server/cloud version of IPFS with this as well?

**Comment by pablomendezroyo** [comment]
Duplicate of https://github.com/dappnode/DNP_DAPPMANAGER/issues/1133
