### ISSUE TITLE
403 forbidden error on IPv6 networks + workaround

### ISSUE THREAD

**Issue by MelvinRook** [dappnode/DAppNode#407]
**Bug description**
I've been troubleshooting the 403 forbidden error on local network. This is due to a strict access configuration on the nginx docker container, which is fine from security perspective. The main issue is that the default config doesn't work on IPv6 networks, defaults to block, resulting into the 403 forbidden error on the local network client browser.

Check if you have an IPv6 network (MacOS terminal):
```
% traceroute6 dappnode.local
traceroute6 to dappnode.local (fe80::***2 from fe80::***1, 64 hops max, 12 byte packets
 1  dappnode.local  1.982 ms  1.843 ms  2.427 ms
```

**Workaround**
Perform one of the following workarounds to gain access:
1. Add a null route for the IPv6 target address - figure out target IP with `traceroute6 dappnode.local` and add the null route to your network settings (depending on your client OS)
2. In Firefox perform the following steps:
* Open `about:config`
* Find config key: `network.dns.ipv4OnlyDomains`
* Add the local dappnode domain: `dappnode.local`

**Related file**
https://github.com/dappnode/DNP_HTTPS/blob/master/fs_overlay/var/lib/nginx-conf/nginx.conf.erb

**Comment by 3alpha** [comment]
Hm, it seems that we forgot to include link-local range into allowed range. Adding `allow fe80::/10;` line in there should resolve that issue. With hope that routers won't route that range on public internet 😅, I don't see any security issue adding that line in the next release.

**Comment by 3alpha** [comment]
Tracked here: https://github.com/dappnode/DNP_HTTPS/pull/64
