### ISSUE TITLE
Survey button taking the user to a different screen

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DAppNode#41]
When you click the survey button, the tab just goes to the survey substituting  the  ADMIN UI, would not be better to just open another window???

**Comment by dapplion** [comment]
Good suggestion, implemented at https://github.com/dappnode/DNP_ADMIN/commit/cf63b49918a18b1c248af9034a58e38986d6852f

**Comment by Shelpin** [comment]
Great thanks!!

**Comment by Shelpin** [comment]
Checked and  working!!Thanks!!
