### ISSUE TITLE
Add testing templates

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#410]
## Context
DAppNode releases are tedious and difficult to test. There is no official way to test every new release, and even there are unit tests integration tests, and more, there are a few things that are not test automated and would be really difficult to automate.

## Approach
Write down 2 test documents and find a location for them so other dappnode team members can use it for every new release

* **Critical features test**: this test document must contain all the critical functionalities that makes the dappnode work: IPFS, dappstore, repository, ipfs remote, etc
* **New features test**: this test document would change on every release and will contain the most critical changes developed in the release which will come from any core package (most of the times from the dappmanager). Every most critical feature included in the release should be included to the **critical features test** document

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380365487) by [Unito](https://www.unito.io)

**Comment by dsimog01** [comment]
This template has already been defined in our Notion
