### ISSUE TITLE
Incorrect volume size reported when using non-default mountpoint

### ISSUE THREAD

**Issue by TripleSpeeder** [dappnode/DAppNode#417]
**Describe the bug**
The volume size in the package details screen is incorrect. I think this happens because i changed the default mountpoint when installing the package. The package is installed under "/mnt/raid" where i have mounted a LVM volume.

**Screenshots**
Example for the Nethermind XDai package:
![image](https://user-images.githubusercontent.com/754478/162179937-ed3c9e15-ee27-4d2d-a5b8-cdb0854a2765.png)
Actual size on disk is about 238 Gigabyte:
![image](https://user-images.githubusercontent.com/754478/162179976-df3c9c1e-0931-43ef-8439-2cd29ce5f546.png)

Same issue with all packages that are installed at the `/mnt/raid` mountpoint.

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.54
dappmanager.dnp.dappnode.eth: 0.2.49, commit: 14f56e8e
https.dnp.dappnode.eth: 0.1.3
ipfs.dnp.dappnode.eth: 0.2.16
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.1
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.6
dockerCliVersion: 20.10.6
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-8-amd64
Disk usage: 71%

**Additional context**

**Comment by 3alpha** [comment]
We have known about this issue for a while, however it is non-trivial to solve. I don't know why UI shows "All volumes" size when one of volumes has unknown size.
