### ISSUE TITLE
Https only on local network

### ISSUE THREAD

**Issue by Memoi** [dappnode/DAppNode#418]
Hello, I would like to have geth and goerli-geth in HTTPS on internal network not on external, the HTTPS feature don't allow it just in internal network.

There is a way to do it only on internal network ?

Thanks

**Comment by 3alpha** [comment]
Hi, sorry, currently there isn't a user-friendly way to do it.

**Comment by Memoi** [comment]
> Hi, sorry, currently there isn't a user-friendly way to do it.

I'm a tech guy so if there is a complex way it's good too.
I guess it's to apply it and block the port on my router from Internet ?

**Comment by alexpeterson91** [comment]
> Yeah, you have to disable UPnP on your router (you'll need to open every port manually for each package), delete 443 and 80 port forwarding and somehow make sure that https://... domain resolves to the private IP of your dappnode machine.

This won't work really either. The container ports change every restart of the container for most ports. Need DMZ or UPnP or setup ports to be static for each of your containers. It's really a lot of work undoing the way things are setup. You can secure your RPC connections within your network without using HTTPS portal but you'd have to manually setup tls or something in the flags of each container.

**Comment by 3alpha** [comment]
Nope, 80 and 443 won't change. I agree with the rest of the comment.
