### ISSUE TITLE
Kubernetes Operator / Clustering

### ISSUE THREAD

**Issue by META-DREAMER** [dappnode/DAppNode#420]
**Is your feature request related to a problem? Please describe.**

I would like to run DappNode as a cluster instead of a single node so I can more easily scale up/down my compute capacity and have more consistent uptime when I have to take down certain nodes for hardware upgrades etc. 

**Describe the solution you'd like**

Ideally reworking Dappnode to run containers using Kubernetes. [Kotal](https://www.kotal.co/) is one project that is building a Kubernetes operator for web3 infra, could collaborate there / build off that. A good example of the end user experience would be something like [Kubesail](https://kubesail.com/homepage) has where the implementation details of Kubernetes are abstracted from the user but allows them to easily add more nodes to their cluster. [K3S](https://k3s.io/) would likely be a good foundation to build on as its very lightweight and can run a fully compliant Kubernetes cluster on low power hardware like a Raspberry Pi.

**Describe alternatives you've considered**

Rolling my own cluster and writing my own manifests to deploy packages and manually keep up them up to date etc. Not feasible for anyone who doesnt have devops / kubernetes experience.

**Additional context**

Building out a Kubernetes operator / platform that could consume Dappnode packages could set the foundation for a much broader use case for orchestrating containers and compute nodes for the decentralized web and allow Dappnode infrastructure to scale better to more professional / power user use-cases.

This is definitely a pretty big lift but definitely doable if there's some experienced devops/kubernetes talent in the community to help execute this. It would be something that DappNode community could raise funds for as well from entities like Protocol Labs etc since its an incredibly valuable public good/

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380363292) by [Unito](https://www.unito.io)

**Comment by dapplion** [comment]
420 :eye: :eye:

**Comment by Pol-Lanski** [comment]
I support this proposal. I do not currently have bandwidth to take a project lead role, but I will support by writing any grant proposals necessary and facilitating coordination.

**Comment by META-DREAMER** [comment]
Will start to rally support. And def agree that this can be developed standalone. Would be a "platform of platforms" of sorts, with its own single node plug and play version for more consumer friendly use (still allowing you to get benefits of Kubernetes orchestration even as a single node cluster).

E.g. various protocols (Ceramic, connext, IPFS) could complement Kubernetes operators for their client / node software that integrated nicely with standardized web3signer containers in a secure way etc.

Lots of potential for self hosted decentralized federated compute clusters as well when you merge power of Kubernetes (things like [kubespan](https://www.talos.dev/v1.0/kubernetes-guides/network/kubespan/) and [loft](https://loft.sh)) with web3 tech like [radical](https://radicle.xyz), DNP, Handshake, Arweave, etc all orchestrated together into higher level platforms.

**Comment by dsimog01** [comment]
This looks like a very good idea, but with the current resources it is impossible for us to implement this. This issue is marked as susceptible of being reopened when there are enough resources
