### ISSUE TITLE
Association vote in GIP-34

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#421]
Vote [here](https://snapshot.org/#/gnosis.eth/proposal/0xdeadb69e1c18ea78e6592664d2be34f7705ebb040c0b1788514b39bd9a2e2096) (Gnosis Snapshot)
According to the result [here](https://snapshot.org/#/dao.dappnode.eth/proposal/0x5482a0ee2d838ca28cc801a40c187ffb6d9a9fcacc8bbca85db1e5e3a1822a04) (DAppNode Snapshot)

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380363020) by [Unito](https://www.unito.io)

**Comment by dsimog01** [comment]
This looks outdated
