### ISSUE TITLE
Connext Package / Contribution Program

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#424]
I have reached out and applied to the Connext Contribution program. 

1. Low hanging fruit: [Connext](https://www.connext.network/) has `Routers` with the potential of being deployed as a DAppNode package. We need a builder that wants to create and maintain the package. 
1. Someone could research the project properly and try to propose better ways of continuously collaborating with them / apply for grants / better embed ourselves in the Connext ecosystem.

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380362341) by [Unito](https://www.unito.io)

**Comment by ef3n9r98** [comment]
Hi @Pol-Lanski, I know dappnode is open source, but are there any github issues that you have a budget for? 

Thanks!

**Comment by pablomendezroyo** [comment]
@ef3n9r98 hey! sorry for the delay, would be great to get some help. If you still are interested on contributing to the project pls reach me out
