### ISSUE TITLE
SSV - Grant

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#425]
Need to follow up on this. Money needs to be sent to the DAppNodeDAO multisig: 
eth:0x6bE7a88b4CFD3F94adA8a7a17dea7a760380050c

https://snapshot.org/#/mainnet.ssvnetwork.eth/proposal/0x6c06e1020c784db168d91410c8035d2431b1419037ab99f5795e9c797da8caa2

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380362057) by [Unito](https://www.unito.io)

**Comment by alexpeterson91** [comment]
Discussion about the passed proposal. [here](https://forum.ssv.network/t/network-growth-grants/231)

**Comment by Pol-Lanski** [comment]
Funds received in the assoc. wallet as per:
https://etherscan.io/tx/0xb8bab3768834f0e1e3163d9df1198acdb2d3f3970bb4355f88a3d71d496d9d18

@eduadiez, can you send the funds to the DAO?
https://gnosis-safe.io/app/eth:0x6bE7a88b4CFD3F94adA8a7a17dea7a760380050c/home

**Comment by eduadiez** [comment]
@Pol-Lanski this address only has one owner, how is that possible? have we created the multisig correctly in both networks?

**Comment by alexpeterson91** [comment]
> Funds received in the assoc. wallet as per:
> 
> https://etherscan.io/tx/0xb8bab3768834f0e1e3163d9df1198acdb2d3f3970bb4355f88a3d71d496d9d18
> 

This was the address Lanski had me send to the SSV team for payment.
@Pol-Lanski is this resolved yet?

**Comment by Pol-Lanski** [comment]
Need to add the rest of signers to the multisig - will do ASAP

**Comment by dsimog01** [comment]
Closing this as it is not directly related to product software
