### ISSUE TITLE
Show in the dappstore some tag that shows a package is arm compatible

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNode#428]
People that run dappnode in an arm machine don't know an easy way to check if a package is arm compatible. They realize a package is not compatible because the installation process fails or they check the package.json of the package.

**Describe the solution you'd like**

It would be interesting to have an arm architecture or arm compatible tag in the dappstore.

**Describe alternatives you've considered**

A visual icon I personally think is too much.
If you type in the search bar, it could appear all the arm compatible packages.

**Additional context**

There is a field in the package.json of the packages that indicate the multi architecture of the package.

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380361448) by [Unito](https://www.unito.io)

**Comment by 3alpha** [comment]
This is DAppManager issue. Also, it seemed to me that incompatible packages were not even shown in DAppStore.

**Comment by dapplion** [comment]
> This is DAppManager issue. Also, it seemed to me that incompatible packages were not even shown in DAppStore.

Yep, the DAppStore of a DAppNode shows only the packages with compatible architecture. However, some packages may be broken and lie about compatibility, so there's nothing we can do here, any info would lie.

**Comment by dsimog01** [comment]
Closing this issue as the packages shown only include those which are compatible
