### ISSUE TITLE
DappNode IP change

### ISSUE THREAD

**Issue by kosecki123** [dappnode/DAppNode#43]
Hey,

looks like after IP change on my DappNode host the VPN connection no longer works for me. 

Is it expected that dyndns got updated with new IP?

**Comment by Shelpin** [comment]
Thanks @kosecki123   !!! When you enable static IP, the VPN profile still uses the DYNDNS domain  as it is not automaatically updated, but still it should work as that is your assigned DYNDNS.... we will have a look to it , in the mean time you can connect again to the URL you accessed to get your first credentials and it will give you a new VPN profile with  your new static ip in it

**Comment by kosecki123** [comment]
I've tried to get new VPN profile by going to https://dappnode.github.io/DAppNode_OTP/#otp=... link displayed after DappNode boot. Does not work for me.

The problem seems that my DynDNS still resolves to the previous IP.

**Comment by Shelpin** [comment]
Can you please  check if the server address below the otp link is updated with your static  IP? @dapplion what do you think?Thanks!!

**Comment by kosecki123** [comment]
> Can you please check if the server address below the otp link is updated with your static IP? @dapplion what do you think?Thanks!!

I see 470...34c.dyndns.dappnode.io

**Comment by Shelpin** [comment]
Weird...could you try again please after cleaning cache or with another browser?nornally once the static ip is selected the otp link is generated with the static ip as server address.thanks!

**Comment by kosecki123** [comment]
> Weird...could you try again please after cleaning cache or with another browser?nornally once the static ip is selected the otp link is generated with the static ip as server address.thanks!

Just to give you the full picture, my DAppNode is running on Azure cloud, so switch to public IP was essentially one setting on the Azure panel.

**Comment by Shelpin** [comment]
Ok.... sorry i thought you meant that you had set a static IP in the DAppNode admin UI, i do not know exactly what Azure does when hitting that button, but it seems the address changes so your DYNDNS is not working anymore.Can you try to edit the VPN profile with the Public IP that Azure gave you and then set that ip in the tab system (Enable Static IP) please?

**Comment by vdo** [comment]
@kosecki123 The dynamic DNS refresh is done every 30 minutes. Did you wait this time before experiencing this? If the problem persists, could you restart the dappnode services to force the update?

**Comment by dapplion** [comment]
@kosecki123 Thanks for reporting, it was due to a bug that mutated the privateKey necessary for DAppNodes to perform a dyndns updates. We will release a new version of the DNP_VPN package in a few hours that will solve it.
