### ISSUE TITLE
Can't extend volume.

### ISSUE THREAD

**Issue by CMTRACE** [dappnode/DAppNode#435]
System

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.54
dappmanager.dnp.dappnode.eth: 0.2.49, commit: 14f56e8e
https.dnp.dappnode.eth: 0.1.3
ipfs.dnp.dappnode.eth: 0.2.16
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.1
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.6
dockerCliVersion: 20.10.6
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-7-amd64
Disk usage: 83%
Disk physical size 1.8TB

**Describe the bug**

Extending the file system does not work

**To Reproduce**

![image](https://user-images.githubusercontent.com/51069646/170131307-0fcc51d0-1f31-4769-bc07-b0d61d897e51.png)

**DAppNode version:**

Included at top

**Comment by 3alpha** [comment]
I think this is fixed in next release. @tropicar?

**Comment by tropicar** [comment]
Yes , i think this error that was fixed in this PR https://github.com/dappnode/DNP_DAPPMANAGER/commit/66237bdaaccf64a224a329e4d8f7cca5efcbb96c for the next release

**Comment by tropicar** [comment]
@CMTRACE if you can md me via discord, we can try to expand the volume with a little fix of a script, i cant guide you step by step

**Comment by CMTRACE** [comment]
> @CMTRACE if you can md me via discord, we can try to expand the volume with a little fix of a script, i can guide you step by step

Thanks mate, DM sent - if you like you can paste the general steps here too if that's easier for everyone

**Comment by tropicar** [comment]
> 

I have answered you, i will do it but, this issue should be fixed in the next release

**Comment by tropicar** [comment]
1. you have to access the machine via cli, using a keyboard and a screen or via ssh.
2. Execute this command: docker exec -it DAppNodeCore-dappmanager.dnp.dappnode.eth /bin/sh
3. Now type:  nano /usr/src/app/hostScripts/lvm.sh 
4. we have to add a flag to command, be careful here:

we have to change this line: 
```
pvcreate "/dev/${1}" &>> "$LOG_FILE"
```
to this one:
```
pvcreate "/dev/${1}" -y &>> "$LOG_FILE"
```
you check where is the file, here https://github.com/dappnode/DNP_DAPPMANAGER/pull/1019/files

**Comment by CMTRACE** [comment]
Cheers for that.

**Comment by 3alpha** [comment]
I'll close this for now, if the issue reappears, we can reopen it.
