### ISSUE TITLE
Download link in installation wiki is broken

### ISSUE THREAD

**Issue by wildmolasses** [dappnode/DAppNode#44]
Section 1.1 here: https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#11-download-the-image

The download link is broken.

**Comment by Shelpin** [comment]
Hey @wildmolasses !!! thanks for reporting! it seems that you were to download at the same time the iso was being updated...just checked it out now and it is working. have a nice weekend!!

**Comment by wildmolasses** [comment]
Oh man OK! Thanks @Shelpin !
