### ISSUE TITLE
Web3signer does not allow users to download the keystores

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#441]
Web3signer should have a way to extract the keys from there and let the user download it for safeguard / backup.

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380359130) by [Unito](https://www.unito.io)

**Comment by dapplion** [comment]
The keymanager API standard explicitly does **not** support that for security reasons. The keystores you import are generated with some other tooling (i.e. the deposit-cli). The mnemonic is your main backup, and if a user wants to backup the keystores it should not be done from a place that's actively signing. That adds greater risks if the API auth security is compromised

**Comment by pablomendezroyo** [comment]
Implemented with the standard backup docker volume system for dappnode packages
See https://github.com/dappnode/DAppNodePackage-web3signer/pull/26
