### ISSUE TITLE
Add latest current full node size to Readme file

### ISSUE THREAD

**Issue by hatgit** [dappnode/DAppNode#45]
I was looking to get an idea how much diskspace is needed to run DAppNode, perhaps this could be added to the readme unless it is already listed elsewhere?

**Comment by Shelpin** [comment]
Hi @hatgit !!! it depends on the nodes / Dapps you want to have installed, for the basic setup including  ETH mainet node, IPFS node, VPNand the rest of the core packages you will need  at least 4 gbs (better 8) RAM and a 160 Gbs  SSD disk...

**Comment by dapplion** [comment]
We added a recommended broad specs description here https://github.com/dappnode/DAppNode/wiki/Recommended-specs-for-DAppNode-hardware

@hatgit Thanks for the recommendation, but the specs may vary immensely depending on your needs and all blockchains are changing their sizes quickly
