### ISSUE TITLE
Implement better avatars for clients and web3signer packages

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#452]
The upcoming eth2 multiclient in dappnode is going to fulfill the dappstore with new packages either from prater, gnosis, and mainnet. Every package should have its own avatar, identifying the client and the network.

* According to dapplion the [current avatar from clients in prater](https://github.com/dappnode/DAppNodePackage-teku-prater/blob/master/teku-avatar.png) is not well defining the prater network, see https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/76#issuecomment-1158655321
* The web3signer logo is using the dappnode logo, which is not accurate. Also, the web3signer logo does not shows the network it belongs to. See https://github.com/dappnode/DAppNodePackage-web3signer-prater/blob/master/node-avatar.png and https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/blob/master/node-avatar.png

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380356814) by [Unito](https://www.unito.io)

**Comment by dsimog01** [comment]
Avatars for staker packages already include the network and the signer logo can be left as it is, because the web3signer package includes the staking brain which is fully developed by us
