### ISSUE TITLE
Preparation for the Goerli Merge (Is to be done until afternoon 02/08)

### ISSUE THREAD

**Issue by DAppDanil** [dappnode/DAppNode#461]
Issue 1: Incompatibility of 2 CL pointing to the same EL
EL:

- [x] dappnode/DAppNode#462

- [x] dappnode/DAppNode#463

CL: (they need to identify themselves in order for passing the allowlist)

- [x] dappnode/DAppNode#468

Issue 2: Include explanation on the two endpoints: RPC and Engine API
- [x] dappnode/DAppNode#464
- [x] dappnode/DAppNode#465

(If there’s no way to put a header from the beacon chain, we can ask users to delete the URL of the EL from their unused CL).

- [x] Announcement for merge
- [x] AMA

UI App manager bugfixes:

![image](https://user-images.githubusercontent.com/109515640/182183072-2fea7d7f-fda1-4e8f-9b4a-6b4263c7a167.png)
- [x] dappnode/DNP_DAPPMANAGER#1088

![image](https://user-images.githubusercontent.com/109515640/182183423-e42ea257-1456-418e-b1e5-577f779939b0.png)
- [x] dappnode/DNP_DAPPMANAGER#1090

![image](https://user-images.githubusercontent.com/109515640/182183507-e2370ae3-e429-478e-acf6-64d4d92f8f2a.png)
- [x] dappnode/DAppNode#469

 
![image](https://user-images.githubusercontent.com/109515640/182183607-1c5bb58b-2283-49a4-b4b8-3765d96677f2.png)
- [x] dappnode/DAppNode#470

**Comment by alexpeterson91** [comment]
> * [ ]  Client names should come first, then network name. (Lighthouse Prater - good, Goerli Geth - not good)
> 
> ![image](https://user-images.githubusercontent.com/109515640/182183607-1c5bb58b-2283-49a4-b4b8-3765d96677f2.png)


I think its a major change to rename the testnets ENS, not impossible but costly and time consuming, not sure it can or should be done right now but i need someone else to weigh in on this

> 
> * [ ]  Fix “1.x” → ‘2.x”

im confused by this one, i thought we are done with 1 and 2 and its just EL and CL for terminology.
