### ISSUE TITLE
No checksums at download page

### ISSUE THREAD

**Issue by 3esmit** [dappnode/DAppNode#47]
I am unable to check integrity of my DappNode iso. 
Please, provide md5 or sha-1 checksums.

**Comment by eduadiez** [comment]
We just added it to the latest [version](https://github.com/dappnode/DAppNode/releases/tag/v0.1.11). Thank you very much for the suggestion and sorry for the inconvenience

**Comment by dapplion** [comment]
@eduadiez, closing this issue
