### ISSUE TITLE
Support Gnosis testnet 'Chiado'

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#482]
DAppNode users represent a very significant portion of Gnosis Beacon Chain validator set. The purpose of Chiado is for consensus stakers to get familiar with required infrastructure post-merge.

**Tasks todo**

Prepare images with Chiado genesis.ssz, config.yaml and bootnodes for

* [x] Nethermind
* [x] Prysm
* [x] Lighthouse
* [x] Teku
* [ ] Lodestar :heart: 

Then just distribute the images as IPFS hashes in a common blog post and accessible doc

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380351154) by [Unito](https://www.unito.io)

**Comment by alexpeterson91** [comment]
I need info to add chiado testnet to the gnosis key gen.

**Comment by tropicar** [comment]
> I need info to add chiado testnet to the gnosis key gen. Edit I looked over their docs and their validator generator and they haven't added the chain specs for chiado or any other testnet that isn't from before mainnet launch.

This are the configuration for chiado testnet https://github.com/gnosischain/consensus-deployment-ansible/tree/master/chiado/custom_config_data

**Comment by tropicar** [comment]
Prysm is not possible now, because we need to use the 2.1.3 version that is compatible with the web3signer.
We are working on building Lodestart, to make this possible its required to add some changed to the web3signer package.

**Comment by dapplion** [comment]
Update on Prysm: We hope to have a working version of Prysm for Gnosis Beacon Chain today on version v2.1.4

**Comment by Pol-Lanski** [comment]
@dapplion wen chiadov2?
