### ISSUE TITLE
In the setup wizards, change mention of "eth1.x" to "Execution Layer" Client

### ISSUE THREAD

**Issue by DAppDanil** [dappnode/DAppNode#484]
![image](https://user-images.githubusercontent.com/109515640/182816016-4eeeddd6-b410-46d0-a39f-a826c853fca1.png)
- [x] Prysm

![image](https://user-images.githubusercontent.com/109515640/182813208-2b22fdc2-1977-4444-b505-fd938796b620.png)
- [x] SSV Prater 

![image](https://user-images.githubusercontent.com/109515640/182813243-2b25d306-0b01-4374-adaf-b74cbff492b7.png)
- [x] Prysm Pyrmont

**Comment by alexpeterson91** [comment]
Prysm Pyrmont is deprecated

**Comment by alexpeterson91** [comment]
Prysm fix here https://github.com/dappnode/DAppNodePackage-prysm/pull/79

**Comment by alexpeterson91** [comment]
SSV Prater fix here https://github.com/dappnode/DAppNodePackage-SSV/pull/39

**Comment by alexpeterson91** [comment]
@DAppDanil these listed the only you found? or is there more not listed or checked yet?
rest is done wont close it till thats confirmed

**Comment by DAppDanil** [comment]
> @DAppDanil these listed the only you found? or is there more not listed or checked yet? rest is done wont close it till thats confirmed

yep, was checking through all of them, only found in those 2
closing the issue, gj
