### ISSUE TITLE
Change VPN installer scripts - We must install Wireguard as the first option and OpenVPN as a fallback, if wireguard can't be installed.

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNode#488]
We must install Wireguard as the first option and OpenVPN as a fallback, in case there is no possibility to install Wireguard. For example, if the following prerequisite installation fails https://github.com/dappnode/DAppNode/blob/ee1e0c90ff318977c80deecb80196c3d1a63fa5b/scripts/dappnode_install_pre.sh#L120

Regarding commands and docs, we must keep them in favor of backward compatibility but encouraging users to switch to Wireguard

**Originally posted by pablomendezroyo in https://github.com/dappnode/DAppNode/pull/486#issuecomment-1217527350**

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380349479) by [Unito](https://www.unito.io)

**Comment by pablomendezroyo** [comment]
Isn't wireguard been installed by default?

**Comment by 3alpha** [comment]
I think yes. Further on this, I would completely phase out OpenVPN since now issue with Wireguard doesn't exist anymore.

**Comment by alexpeterson91** [comment]
Yeah this was made before you approved me adding WireGuard to all installs. I didn't know if you wanted to leave it open or not so I left it. that said it's not core required DNP Just a note. Idk if it should or shouldn't be.

And I agree fully with @3alpha on ending OpenVPN. And look into how hard it'd be to start converting to use an actual private subnet which is already baked into WG?not the ip block we are using?

**Comment by alexpeterson91** [comment]
So close it if you want, I didn't actually open it or care about it since I've long been in favor of full migration to WireGuard. I did by request so if that's no longer requested neither is this issue.

**Comment by dsimog01** [comment]
Closing this since it is no longer an issue
