### ISSUE TITLE
ENS .eth domains: ipfs resolve -r /ipfs/: invalid path "/ipfs/": not enough path components

### ISSUE THREAD

**Issue by vorburger** [dappnode/DAppNode#492]
While connected to DAppNode's VPN, when I access e.g. http://alice.eth/ in Brave (which has some sort of ENS support built-in) as well as in Firefox (which as far as I know does not?) the browser just shows:

```
ipfs resolve -r /ipfs/: invalid path "/ipfs/": not enough path components
```

I'm assuming this message comes from DAppNode, but I don't know what it means in relation to ENS .eth domains, or how to fix it.

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380348608) by [Unito](https://www.unito.io)

**Comment by vorburger** [comment]
As far as I understand, because this affects both Firefox and Brave, this is probably a bug in `dappmanager/src/ethForward/resolveDomain.ts`, and not related to (my) https://github.com/dappnode/DAppNode/issues/406 IPFS tribulations, and actually has nothing directly to do with Brave's built-in IPFS and ENS support.

**Comment by pablomendezroyo** [comment]
@vorburger hey! thanks for the report. Will look into it a contact you back

**Comment by 3alpha** [comment]
Hm, it seems that http://alice.eth/ doesn't have contenthash field set https://app.ens.domains/name/alice.eth/details.

**Comment by 3alpha** [comment]
I still haven't been able to figure out what standards those websites use, since it is certainly not [EIP-1577](https://eips.ethereum.org/EIPS/eip-1577). Compliant websites work in my DAppNode, at least. See http://vitalik.eth
