### ISSUE TITLE
Make a better guide

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DAppNode#5]

**Comment by YalorMewn** [comment]
#### For this example we'll be installing DAppNode on a [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-create-your-first-digitalocean-droplet) droplet, but the process should work in any other VPS provider like [AWS](https://aws.amazon.com/lightsail/?sc_icampaign=pac_q12018_site_merch_2up_lightsail&sc_ichannel=ha&sc_ioutcome=Product_Adoption_Campaigns&sc_iplace=ContentPage2up&trk=ha_a131L000005CvhBQAS), [Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/), etc.

**Step 1.)** Set up your VPS using Digital Ocean by [following official documentation](https://www.digitalocean.com/community/tutorials/how-to-create-your-first-digitalocean-droplet) 

**Step 2.)** Open your computers terminal, proceed to install CE for Ubuntu by [following official documentation](https://docs.docker.com/install/linux/docker-ce/ubuntu/).
**2.1)** Enter the code below, (***Note each $ symbolizes a line of code you must enter individually***)

`$ sudo apt-get update
$ sudo apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
$ sudo apt-key fingerprint 0EBFCD88
$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
$ sudo apt-get update
$ sudo apt-get -y install docker-ce"\`

**Step 3.)** Install Docker Compose for Linux by [following their official documentation](https://docs.docker.com/compose/install/).

`$ sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose`

**Step 4.)** Install Node 8 or 9 for Ubuntu:

`$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
$ sudo apt-get install -y nodejs`

**Step 5.)** Install DAppNode:

`$ sudo npm i -g @dappnode/dappnode 
$ dappnode init $ sudo npm i -g @dapp` 

**Step 6.)** Start the node:

`dappnode start`

### You're done with installation! 

** 7.)**Now that the system has started , you can check to see that all the systems are running:

`dappnode ps`

**8.)** You can check the state of the chain:

`docker logs -t dncore-dnp_ethchain` 

Note: The chain will take some time to synchronize. 

Once it syncs, this number........👇🏼 in your terminal 
![Screen Shot 2018-05-24 at 9.30.36 PM.png](https://images.zenhubusercontent.com/5ac63b174b5806bc2bcdcab6/56d30023-2421-4f18-9d67-c3a5aa99c065) 

Will match the "Last Blocks"  number on [etherscan.io](https://etherscan.io/) ![Screen Shot 2018-05-24 at 9.37.27 PM.png](https://images.zenhubusercontent.com/5ac63b174b5806bc2bcdcab6/056b531b-a0de-4fbf-8afe-db87a374af55)

**Comment by YalorMewn** [comment]
Step #1 [Follow Ubuntu Guide](https://tutorials.ubuntu.com/tutorial/tutorial-install-ubuntu-server)

When asked to configure:
Option 1. Install DAppNode
Option 2. Install DAppNode from Kernel 

Hostname: 
ubuntu ___________ enter your own name ( like naming your Wifi Router) 

#### Encrypt your home directory? 
- Up to you 
Unmount partitions that are in use? 
- No ( What does this mean ?)
Partitioning discs ( needs lots of clarification here) 

*2 users (Technical open) and (fast newbie friendly) create ISO for each*

**Comment by sponnet** [comment]
During the dappnode installation I ran into following things 

- you should have a system username / password in mind for the ubuntu installation - it should be made clear that this u/p is not related to the dappnode VPN credentials later on
- during Ubuntu setup I was confused : install OpenSSH server or not ?
- the QR code did not fit my screen because of the text displayed under it. I had to press newline a few 10-times to scroll it up and then using page-up I could see it fully. Maybe it would make sense to move the QR code to the bottom.

**Comment by geleeroyale** [comment]
I installed DAppNode on my regular system (18.04 - Kenel 4.17 ... probably not the best idea in current state but here is how it went).

## 1
First it seems rc.local is not set up regularly anymore - so if we want it to run on newer distributions this should go into **prerequisites** ...  Found this suggestion and also ran installer as root - seemed to absolve the *seb - error* from my log file (at the end of this report).
 
```
sudo -i

touch /etc/rc.local

chmod +x /etc/rc.local

(add whatever you want to your /etc/rc.local file)

systemctl enable rc-local.service
```

## 2
I would love to have an **uninstall script**

## 3
Missing more detailed instructions on:
- Configuring the VPN connection
- stopping, starting DAppNode services
- where Parity lives on the system and how to configure using my own, already running, version of parity

My log file
```

[32mLoading DAppNode Core...[0m
Loaded image: bind.dnp.dappnode.eth:0.1.1
Loaded image: ipfs.dnp.dappnode.eth:0.1.1
Loaded image: ethchain.dnp.dappnode.eth:0.1.3
Loaded image: ethforward.dnp.dappnode.eth:0.1.0
Loaded image: vpn.dnp.dappnode.eth:0.1.3
Loaded image: wamp.dnp.dappnode.eth:0.1.0
Loaded image: dappmanager.dnp.dappnode.eth:0.1.2
Loaded image: admin.dnp.dappnode.eth:0.1.1
sed: can't read /etc/rc.local: No such file or directory
[32mDAppNode installed[0m
[32mDAppNode starting...[0m
Creating network "dncore_network" with driver "bridge"
Creating volume "dncore_ipfsdnpdappnodeeth_export" with default driver
Creating volume "dncore_ethchaindnpdappnodeeth_data" with default driver
Creating volume "dncore_dappmanagerdnpdappnodeeth_data" with default driver
Creating volume "dncore_vpndnpdappnodeeth_data" with default driver
Creating volume "dncore_ipfsdnpdappnodeeth_data" with default driver
Creating volume "dncore_binddnpdappnodeeth_data" with default driver
Creating DAppNodeCore-dappmanager.dnp.dappnode.eth ... 
Creating DAppNodeCore-ethforward.dnp.dappnode.eth ... 
Creating DAppNodeCore-ipfs.dnp.dappnode.eth ... 
Creating DAppNodeCore-vpn.dnp.dappnode.eth ... 
Creating DAppNodeCore-wamp.dnp.dappnode.eth ... 
Creating DAppNodeCore-admin.dnp.dappnode.eth ... 
Creating DAppNodeCore-dappmanager.dnp.dappnode.eth
Creating DAppNodeCore-ethchain.dnp.dappnode.eth ... 
Creating DAppNodeCore-bind.dnp.dappnode.eth ... 
Creating DAppNodeCore-ethforward.dnp.dappnode.eth
Creating DAppNodeCore-ipfs.dnp.dappnode.eth
Creating DAppNodeCore-vpn.dnp.dappnode.eth
Creating DAppNodeCore-wamp.dnp.dappnode.eth
Creating DAppNodeCore-bind.dnp.dappnode.eth
Creating DAppNodeCore-admin.dnp.dappnode.eth
Creating DAppNodeCore-ethchain.dnp.dappnode.eth
[1A[2K
Creating DAppNodeCore-ethforward.dnp.dappnode.eth ... [32mdone[0m
[1B[1A[2K
Creating DAppNodeCore-dappmanager.dnp.dappnode.eth ... [32mdone[0m
[1B[1A[2K
Creating DAppNodeCore-vpn.dnp.dappnode.eth ... [32mdone[0m
[1B[1A[2K
Creating DAppNodeCore-wamp.dnp.dappnode.eth ... [32mdone[0m
[1B[1A[2K
Creating DAppNodeCore-bind.dnp.dappnode.eth ... [32mdone[0m
[1B[1A[2K
Creating DAppNodeCore-admin.dnp.dappnode.eth ... [32mdone[0m
[1B[1A[2K
Creating DAppNodeCore-ipfs.dnp.dappnode.eth ... [32mdone[0m
[1B[1A[2K
Creating DAppNodeCore-ethchain.dnp.dappnode.eth ... [32mdone[0m
[1B[32mDAppNode started[0m
[32m
```

**Comment by JComulada** [comment]
Hi,

I tried with 4 new installations. All those was made from VMWare, using local and iSCSI disks, with 8/16Gb assigned memory and 4 virtual Xeon CPUs for each virtual machine

1. DAppNode from ISO: Easy to install for a regular tech-user. Useful "Suggested options for Ubuntu Server installation" document. Ends correctly but VPN doesn't works. 
Suggestion: For evaluation tests, could be interesting to do a "basic services list" to debug first incidences or a "logs list" to explore for errors.

2. Ubuntu 17.04LTS from ISO + DAppNode installation: It works at first time. You can connect to dashboard and observe chain synchronization. After 3 days, chain has not been synchronized.
Suggestion: At Docker and Docker-compose installation, system asks for a sudo password. But this message is covered by new messages and it's difficult to see (after 3 attempts....)

3. Ubuntu 18.04LTS from ISO + DappNode installation: As 2., works at first time, but chain sync never ends (stops at 58%). After restart and install Ubuntu's upgrades, it arrives at 98% and stops (time count indicates "infinity")

4. Ubuntu 18.04LTS from ISO + DAppNode installation: Similar results as 3, but after some reboots (5-6), VPN stops to respond

Resume:
1. DAppNode is a high bandwith disk consumer, tests with iSCSI, local and remote disks shows an intensive disk transference from vm. As developers recommends: better SSD units
2. It's necessary to have a basic list of services and log files for check basic errors or report bugs to team
3. Normal www navigation through VPN (without DAppNode synced) is very smooth and stable, you can't find differences with or without DAppNode intermediation.

**Comment by YalorMewn** [comment]
Hey @JComulada, this is an incredible analysis! 

Thank you so much for taking the time and providing such recommendations, we absolutely will take  these into account.

People like yourself are exactly the types we need to help us get DAppNode streamlined and delivered to the people ASAP!

**Comment by JComulada** [comment]
Ok, and if you can write me a list of logs files, I can fill the site with a more thorough analysis...

;o)
