### ISSUE TITLE
Add swap memory to dappnode ISO images by default

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#502]
Add 16gb swap memory file by default. Take as example https://github.com/dappnode/DNP_CORE/blob/master/src/scripts/add_swap.sh

**Comment by CMTRACE** [comment]
Line 55 in the example divides by 1024 then 1204

**Comment by pablomendezroyo** [comment]
Nice catch! 
Fixed on https://github.com/dappnode/DNP_CORE/commit/52dab6f5355c976c833dc2f31285ca939fca05a4
