### ISSUE TITLE
Implement `logrotate` to every dappnode logs files

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#510]
Implement `logrotate` to every dappnode log file:
- `/usr/src/dappnode/logs*`
- `/usr/src/dappnode/DNCORE/userAction.logs`

**Comment by dsimog01** [comment]
@3alpha Why is this on hold? Can you merge the PR and close the issue?

**Comment by 3alpha** [comment]
This breaks .json logs which accumulate the most so we have to find another solution for that.
