### ISSUE TITLE
Geth high CPU consumption

### ISSUE THREAD

**Issue by sbuljac** [dappnode/DAppNode#515]
since like ~15days ago geth package is consuming significant percentage of my CPU(55%+), my total CPUload is almost always high(97%+), I think this started happening after the last system update, around the same time I also updated t both Prysm packages 

![image](https://user-images.githubusercontent.com/8759971/201882485-39ac6739-334c-41a6-8917-ed5045861650.png)

Everything was working fine before and CPU rarely went over 90%+.

![image](https://user-images.githubusercontent.com/8759971/201883545-51bddbc5-b7bd-4415-b28f-1f816a7c20cb.png)

- Package version: Geth 0.1.36 (v1.10.26 upstream), Prysm 3.0.3 (v3.1.2 upstream), Web3Signer 0.1.3 (22.8.1 upstream)
- OS:  DAppNode Advance

**Comment by sbuljac** [comment]
The issue described still exists for me.

**Comment by alexpeterson91** [comment]
Please post updated screenshots of your DMS docker dashboard, and download logs from Geth (please note geths version when you do) and post them.  Same for your support report tab showing system versions. 

Without any more info right now Id say your CPU is underpowered so just to check can you send specs of yiur processor? What model? What generation is etc. but also I noticed you're on an older Linux kernel which could be playing a factor.

**Comment by sbuljac** [comment]
Tried to update system to latest release, during the update docker needed to be restarted, after the restart Geth got broken, removed it and the Prysm and installed Besu & Teku since I did have a plan to move to minority client at some point. After the sync everything seems to be working fine now, CPU is no more extremally high all the time, so I guess this issue is fixed for me now although I can't say what exactly  fixed it. Thx.

**Comment by alexpeterson91** [comment]
Glad you got it resolved. I have some ideas as to why it happened but they won't recur so long as any future changes to ETH or geth clients or changing or installing new clients. Is done in the stakers UI or the repository tab only.
