### ISSUE TITLE
Dappnode ISO out of date

### ISSUE THREAD

**Issue by CMTRACE** [dappnode/DAppNode#518]
The hosted dappnode ISO comes with an old UI, makes for many additional UI changes in the setup process. 

It would be better to baseline the ISO to avoid issues with multiple updates

For instance the current iso has a limited number of EL clients in repository. If someone chooses geth for instance but want to actually use erigon they are unable to unless they fully update everything then change from remote to local repo and run through the stakers UI

Reducing the number of update events would also greatly improve the out of box experience and streamline worst case recovery options

**Comment by pablomendezroyo** [comment]
Thanks for the report!

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DAppNode/releases/tag/v0.2.61
