### ISSUE TITLE
DNSCrypt package

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNode#52]
It would be nice to have a DNS proxy, so instead of forwarding to 1.1.1.1 et al, we can make use of a local package running [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) and BIND forwarding to it. 

This DNS proxy could do load balancing between many servers, with more resiliency, privacy and censorship resistance for regular DNS queries.

**Comment by vdo** [comment]
Added to dnscrypt branch: https://github.com/dappnode/DNP_BIND/tree/dnscrypt

**Comment by Shelpin** [comment]
included in bind 0.1.6
