### ISSUE TITLE
Implement workflows for the Github self-host runner

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#528]
Implement the corresponding workflows that will run these [tests](https://github.com/dappnode/DAppNode/issues/526) on the Github self-host runner  

Deppends on:
- https://github.com/dappnode/DAppNode/issues/527
- https://github.com/dappnode/DAppNode/issues/526

**Comment by alexpeterson91** [comment]
I've got plenty of dedicated server space to dedicate to hosting our own runners. Shutting some older test servers down and firing up dedicated ones and rebuilding some home servers. I should have a data center like connection at home with as many static IPs as I want $15/monrh
