### ISSUE TITLE
Add Fee Recipient as Global Env in all staker Consensus + Signer packages

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#544]
Add the Fee Recipient as a global environment variable in all staker packages:
- Consensus clients: validator service
- Signer packages: brain service

- [ ] Remove Env `FEE_RECIPIENT` from the package compose
- [ ] In the validator entrypoint add a checker for whenever the Env is set or not
- [ ] Add global Env in the manifest
- [ ] Set minimum dappnode version in the manifest

Depends on:
- Allowing to set Global env fee recipient from dappmanager: https://github.com/dappnode/DNP_DAPPMANAGER/issues/1386
- Fee recipient migration: https://github.com/dappnode/DNP_DAPPMANAGER/issues/1398

**Comment by dsimog01** [comment]
This needs to be re thought as we might remove the default fee recipient from the stakers to leave only the input in the staking brain

**Comment by pablomendezroyo** [comment]
We should consider closing it
