### ISSUE TITLE
Add general contributor guide

### ISSUE THREAD

**Issue by eddyariki** [dappnode/DAppNode#546]
I am trying to start contributing to this project, but as a beginner into dappnode, it can be very confusing to get up to speed. 

I think the DAppNode general repository can be a place that developers can use as a guide for navigating through the project. 

Some information that would help:
- architecture 
- prerequisite setup (if any)

**Comment by pablomendezroyo** [comment]
> 

Hey! so sorry for the late reply and it's awesome that you want. to contribute to this project. You can reach me via Private message in the dappndoe discord channel.

There are 2 main things you can contribute and you can even get grants for them:
- DAppNode packages: building and maintaining dappnode packages
- DAppNode core: developing core functionalities in dappnode
  - Dappndoe installer
  - Dappnode core package
  - Installer
  - Dappnode SDK

Dappnode is a small team and would be great to have better contributions and instructions to benefit the community. Actually this would be a great first contribution for you, reach us through Discord to learn on how to create this contributions guide
