### ISSUE TITLE
Make sure every dappnode package has `mainservice` in the manifest

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#548]
Make sure every dappnode package has `mainservice` in the manifest for:
- Monoservices packages that are built as multiservices
- Multuservices packages that does not contain the `mainservice`

**Comment by 3alpha** [comment]
Is this obsolete now that we enforce image names in the SDK?

**Comment by pablomendezroyo** [comment]
> Is this obsolete now that we enforce image names in the SDK?

yes!
