### ISSUE TITLE
Web3signer update in GBC causing huge spike of memory usage

### ISSUE THREAD

**Issue by zengzengzenghuy** [dappnode/DAppNode#559]
**Describe the bug**

The recent update of web3signer in Gnosis Chain are causing memory usage in Dappnode up to 97%. 
Some users are claiming that their Dappnode stopped automatically and UI stopped working. It takes a couple times of manual restart to make it works again.

**To Reproduce**

1. Run Gnosis Chain on Dappnode
2. Update web3signer to latest version.

**Expected behavior**

1. Memory usage increases up to 97%.
2. Dappnode stopped automatically and UI stopped working.

**Screenshots**
<img width="599" alt="web3signer_memory" src="https://user-images.githubusercontent.com/85567868/234173398-ac09c1d8-560c-499b-a622-dda041436194.png">

**DAppNode version:**

- Web3signer: v1.0.1 upstream v23.3.1

**Additional context**

**Comment by pablomendezroyo** [comment]
thanks for the report, will research on this.
