### ISSUE TITLE
Consensus Client always lag behind the Execution Client (~2000 blocks) Erigon+Nimbus

### ISSUE THREAD

**Issue by ShurikMMS** [dappnode/DAppNode#560]
![nimbus](https://user-images.githubusercontent.com/88925811/235582078-7089e2b9-a3bc-4d1a-a4cf-675c9d1a4a8a.png)
![erigon](https://user-images.githubusercontent.com/88925811/235582092-8d954ea7-0ef8-4d8f-b0fc-4809da7362f9.png)
Is it normal that nimbus always lags behind erigon? I thought it would catch up over time, but the number of lagging blocks always stays the same.

**Comment by pablomendezroyo** [comment]
@3alpha is that number of blocks acceptable to be behind the head of the chain from the execution client point of view?

**Comment by ShurikMMS** [comment]
Yes, my validator became active today. I made a deposit recently, there was a pending status. The lag between nimbus and erigon is not affecting the node in any way. Everything is ok.
