### ISSUE TITLE
Ability to run multiple EL Clients

### ISSUE THREAD

**Issue by 0xfarhaan** [dappnode/DAppNode#569]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to run two EL clients so I can switch to a backup EL incase there are issues with the primary. Currently there is no obvious way to do this as part of the UI. 

**Describe the solution you'd like**
A simple solution would be to allow us to download and run another EL client from the DAppStore and if another EL client is present to use a secondary set of ports.

**Describe alternatives you've considered**
You could also let us select a primary and secondary EL from the stakers menu with clear labelling for which is which. 

**Additional context**
We used to be able to run multiple clients prior to the stakers UI.

**Comment by pablomendezroyo** [comment]
Hi there!

There is a project in the backlog where using a multicaster middleware no matter which clients you are running. @3alpha can bring some light about this.

For the moment, you can simply install manually the Execution Client by typping the ENS name in the dappstore search bar, i.e `geth.dnp.dappnode.eth`. Once installed this backup client, go to its config and make sure that under the variable `_DAPPNODE_GLOBAL_CONSENSUS_CLIENT_MAINNET` is set the consensus client you are using.

Also, notice that on every change you do in the  stakers UI, the configuration of you execution client backup may change.

Please, close this issue if you have no more doubts.
