### ISSUE TITLE
Bump gha checkout from v2 to v3

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNode#570]
**Issue**
GitHub actions `checkout V2` script seems to be deprecated and this is making all the actions fail (see [examples of failures](https://github.com/dappnode/DAppNodePackage-erigon/actions)), see [an example](https://github.com/dappnode/DAppNodePackage-erigon/blob/a3952fbd87243ba8d00b7d4130bf8218155d52f6/.github/workflows/build.yml#L10) of the checkout implementation. 

**Solution**
Bump the GitHub actions checkout from V2 to V3 (i.e [erigon PR](https://github.com/dappnode/DAppNodePackage-goerli-erigon/pull/4)) and open a PR

**Comment by ziogaschr** [comment]
Is the https://github.com/dappnode/DAppNodePackage-goerli-erigon/pull/4 related?

I bumped the checkout version [here](https://github.com/ETCCooperative/DAppNodePackage-etc-mordor-core-geth/actions/runs/5043607750/jobs/9045606115) but the issue is not solved.

**Comment by pablomendezroyo** [comment]
Thanks for the typo report!

Checking your case

**Comment by alexpeterson91** [comment]
@pablomendezroyo let me know if you want me to go around and do this on all our repos, ive done it to a bunch of the repos i work with regularly, and implemented it on all my GHAs of my forks in my organization solved a lot of problems for me, not everything but it's made a bunch of packages start working again with CI etc.  i just run into issues with releases/bump upstream on unpublished packages, like erigon gnosis, which is working pretty damn good so far ive got it working beautifully with no external CL just using the internal CL.  
So let me know if i should just be going around and do the tedious task of updating every repo we have. or at least adding PRs for it on all packages. 
 I also just checked some open issues with Github Checkout, github actions and github runners, and added a comment or 2 on several issues of people asking for node18 support, node16 is supposed to be EoL like September this year, some talked about going straight to Node20, but others asked for node 18 too, so i did too.  apparently theres a bunch of people looking for an answer to when and if Node18 is gonna be implemented on the runners, im subscribed to some of the threads now too so hopefully something gets resolved shortly

**Comment by pablomendezroyo** [comment]
Hey, yeah souds great, you could implement a script to do that:
```bash
git clone repo
cd repo
if .github/workflows/*.yml | grep github actions checkout v2
then
....change it to v3
fi
cd ..
```

Just as a quick example

**Comment by alexpeterson91** [comment]
Will do, ive already have been doing backups of all dappnode repos every once in a while, so ill refresh mine and try my scripting skills.
