### ISSUE TITLE
Unable to connect using Wireguard VPN

### ISSUE THREAD

**Issue by jnsrikanth** [dappnode/DAppNode#581]
I am seeing an error while connecting to DappNode using the Wireguard VPN with the connection configuration given by dappnode_connect command on the CLI.
I received the Wireguard configuration by running the below command
$dappnode_wireguard

I copied the text from the console and copied into a file by name wireguard.conf and used that file to import into the Wireguard VPN application on my Windows 11 laptop.

However I am facing the issue with the wireguard vpn unable to connect and is throwing the error on the screen as follows:

"Unable to import configuration: Invalid Endpoint Host: "" "

That is the exact error I see from a dialog box.

Can you please help me with this?

**To Reproduce**

 "Unable to import configuration: Invalid Endpoint Host: "" "

**Expected behavior**

**Screenshots**

<img width="330" alt="image" src="https://github.com/dappnode/DAppNode/assets/17452662/c6794157-f21e-477d-8f23-96801bb90aae">

**DAppNode version:**
Latest as of 14/06/2023

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by 3alpha** [comment]
Please redownload certificates you get with dappnode_connect and make sure that line `Endpoint = ...` has something after equals sign. For further issue please get back to us on Discord.
