### ISSUE TITLE
Wireguard cant change port

### ISSUE THREAD

**Issue by knightsolidus** [dappnode/DAppNode#591]
**Describe the bug**
Cant connect when i change port on dappnode wireguard and pc or android wireguard

**To Reproduce**
When i go to change port number on wireguard
http://my.dappnode
--> packages -->system packages -->wireguard -->config -->show advanced editor --> serverport=21820 -->update
-->network --> service -->wireguard -->host port=21820 --> package port number --> 21820 -->update port mappings
Then i reboot the system and i cant enter to my.dappnode, i change the port on wireguard pc on endpoint and listen point to 21820 and sent packages but not receive any package

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.77
dappmanager.dnp.dappnode.eth: 0.2.72, commit: 26bbe6f9
https.dnp.dappnode.eth: 0.2.1
ipfs.dnp.dappnode.eth: 0.2.20
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.2
System info
dockerComposeVersion: 1.29.2
dockerServerVersion: 20.10.24+dfsg1
dockerCliVersion: 20.10.24+dfsg1
os: debian
versionCodename: bookworm
architecture: amd64
kernel: 6.1.0-10-amd64
Disk usage: 61%

**Comment by 3alpha** [comment]
First thing that comes to mind is that you have to redownload config files with new port. For further support, please join our Fiscord. If we find an actionable issue here we can reopen this.
