### ISSUE TITLE
Build script to tag packages with commit and version

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNode#75]
Add a build script to get the short SHA commit (`git rev-parse --short HEAD`) and current version from manifest, and add it to the logs of our packages: VPN, ADMIN and DAPPMANGER to know the exact commit of the build. 

Now, using the `docker-compose build` method, the git information is out of the context.

**Comment by dapplion** [comment]
Duplicate of https://github.com/dappnode/DAppNode/issues/77
