### ISSUE TITLE
Define a convention for upstream versions

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNode#76]
Currently, we add the upstream version to some of the packages description. Define a convention to add them to all packages in a consistent way. 

Ideally, it should be visible when installing the package (some descriptions cannot be read).

**Comment by dapplion** [comment]
Related to https://github.com/dappnode/DAppNode/issues/83.
I agree we should add a field in the manifest for this. What naming and value convention would you suggest @vdo ?

**Comment by dapplion** [comment]
Add new field:
```
upstreamVersion: 0.18.0
```

**Comment by dapplion** [comment]
Done
