### ISSUE TITLE
Restore functionality SPECS

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#78]
Proposed solution to avoid users having to ssh into the server in certain *extreme* cases.

The `core.dnp.dappnode.eth` DNP will have a super simple API. It will have one endpoint `recover` that accepts an array of core DNPs version or a global core DNP version. This endpoint will verify the IP range to add some security and only allow admins and the ADMIN DNP to call the endpoint. The `core.dnp.dappnode.eth` already has access to docker, so it will execute the [restore script](https://github.com/dappnode/DAppNode/wiki/DAppNode-Installation-Guide#3-how-to-restore-an-installed-dappnode-to-the-latest-version) and `docker-compose up` a certain version of the core DNPs.

The `core.dnp.dappnode.eth` API endpoint will have a UI to support calls from the ADMIN UI, a dedicated restore ui and even a direct browser GET request from the browser.

**Comment by vdo** [comment]
- Limit this call to accept only values like version, never execute any arbitrary command.
- Consider using python for crossbar if it's a lighter alternative to node.
- Expose it only to the 172.33.0.0/16 range.
