### ISSUE TITLE
Automate DNP maintenance - SPECS

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#83]
We are facing serious scalability issues to maintain all DNPs and DWebs up to date. To tackle this problem we should:
- Create the DNPs in a way that using the next version release of the underlying software is just changing a number or even nothing, as it fetches the latest stable release from somewhere.
- Use hooks with travis or some other CI, that notices the new release and generates the new DNP automatically
- Then, aggregate the to-be-updated DNPs so the repo administrator only has to do a click to approve the update transactions.

**Comment by vdo** [comment]
I find the first point very hard to accomplish, as every project has it's own channels, or way to create releases (even if using github, which is not always the case)
If we can build our own all-in-one CI system, then we can parametrize the version of each upstream version for each DNP and automate as much as we can, but each pipeline will be different.

**Comment by vdo** [comment]
https://github.com/pyatyispyatil/github-releases-notify-bot
