### ISSUE TITLE
Option to enable DNS Blacklists for Ad Blocking like the Pi-hole does

### ISSUE THREAD

**Issue by Beasta** [dappnode/DAppNode#84]
Because we already run a dnscrypt forwarder, it would be awesome if we could also sink ad traffic when connected.

Links:
https://github.com/jedisct1/dnscrypt-proxy/wiki/Public-blacklists
https://pi-hole.net/

**Comment by dapplion** [comment]
Thanks for the idea @Beasta ! Looks like an interesting feature, but we would put it on hold for now
