### ISSUE TITLE
Option for full tunnel when configuring VPN clients

### ISSUE THREAD

**Issue by Beasta** [dappnode/DAppNode#85]
When I'm at the coffeeshop on insecure wifi, would be nice to have an option to tunnel all of my traffic through the Dappnode.

**Comment by dapplion** [comment]
@Beasta Thanks for reaching out! I believe that tunneling all traffic through DAppNode is an option that must be turned on in each client profile / app. @vdo can you confirm?

**Comment by dapplion** [comment]
Yes that's an option of each VPN client. So whenever you are in an insecure environment go to your VPN client configuration and activate the option to redirect all traffic through the server. If you need help doing that let us know, as well as your OS and specific client / version

**Comment by vdo** [comment]
@dapplion  We could force it from the server side, but for now we prefer to leave the option to the user if he/she wants to tunnel everything.

**Comment by Beasta** [comment]
I was thinking it might be nice to have it part of the automated setup process. That way I could create a profile for the full VPN and a profile for the partial VPN. Right now we choose whether a new profile would be admin or guest. We could also have the option to choose full or partial vpn at that point. It would also help the user understand that the standard option isn't a full vpn. Not a huge deal but definitely helpful for those like myself who are somewhat ignorant about how vpn works.

**Comment by Shelpin** [comment]
> I was thinking it might be nice to have it part of the automated setup process. That way I could create a profile for the full VPN and a profile for the partial VPN. Right now we choose whether a new profile would be admin or guest. We could also have the option to choose full or partial vpn at that point. It would also help the user understand that the standard option isn't a full vpn. Not a huge deal but definitely helpful for those like myself who are somewhat ignorant about how vpn works.

What do you think about this @vdo and @dapplion ?  it seems like a nice option, thanks for the suggestion @Beasta !

**Comment by vdo** [comment]
This is managed from the client side, depending on the OS. There is no way to force it in the OVPN file, so I'm closing it for now

**Comment by Beasta** [comment]
should still be clarification to the user during setup that this IS NOT a full vpn. I think that most folks think VPN means all traffic is tunneled

**Comment by Pol-Lanski** [comment]
I think what @vdo tries to say is that it can be a full vpn, and it depends on the VPN client and not on DAppNode. On my tunnelblick client, the second option seen in this image, which is ticked, routes all traffic through the VPN. 
<img width="426" alt="Capture d’écran 2020-02-07 à 12 43 50" src="https://user-images.githubusercontent.com/19168735/74018877-bbf54180-49a7-11ea-9987-e7205a108ff2.png">

That said, you're right and there's probably a way to maybe transmit the essence of this discussion to DAppNode users. For simplicity of UX, I would keep this information on the Docs and not in the UI. Probably along the lines of something like that:
```
The OVPN file makes sure that all requests to the DAppNode services are captured, but not necessarily all traffic. If a user wants to route all traffic through the DAppNode VPN it is up to the VPN client to perform this function. Kindly check your VPN client's settings to do so.
```

Would that make sense @vdo ?
