### ISSUE TITLE
Data Usage Limits or throttling? Or even just data usage tracking

### ISSUE THREAD

**Issue by Beasta** [dappnode/DAppNode#89]
I'm paying extra for my internet bill this month because the dappnode has used a whole terabyte. Would be nice to have some means to keep it under control (or at least have an idea of how much it has used )

**Comment by Beasta** [comment]
recently discovered vnstat as useful command line tool for keeping long terms stats on data usage

**Comment by eduadiez** [comment]
We've discovered this:
https://github.com/dappnode/DNP_IPFS/issues/16

Related issue:
ipfs/go-ipfs#3429

In the next version of the IPFS package we're going to add `--routing=dhtclient` as a default option

**Comment by Shelpin** [comment]
closing this issue and opening  a new one about providing data usage in the  admin ui as @beas suggest. thanks  for the feedback!
