### ISSUE TITLE
Add access url to the otp.dappnode.io page to invite other users to your DAppNode

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DAppNode#91]
It was extremely easy to install a new VPN and connect to someone else's dappnode through the easy sharing link: http://otp.dappnode.io#XXXXXXXXX...
Nevertheless, once installed I had no idea where to go to actually access the dappnode. I think a new step should be added at the bottom of the otp.dappnode.ioXXX webpage indicating to connect to: http://my.admin.dnp.dappnode.eth or the right access point.

**Comment by dapplion** [comment]
Sounds good:
- [ ] Add a "Go to DAppNode" linking to the admin ui main page

**Comment by Shelpin** [comment]
Checked!!
