### ISSUE TITLE
Installation DAppNode from ISO fails without network connection

### ISSUE THREAD

**Issue by uniconstructor** [dappnode/DAppNode#94]
I recently installed dappnode on the dedicated machine.
I had no access to internet during installation, but install wizard has an option "setup network later". I use it.
When I back online I tried to connect to my wifi router from dappnode, and I understand that I can't do that. 

Here is why:
- dappnode has no GUI, but ok, I am a programmer, let's use shell
- I go to the duckduckgo to find a way to connect a wifi network via console. No problem Here the solution: https://askubuntu.com/questions/461825/how-to-connect-to-wifi-from-the-command-line

But this instruction does not work for dappnode package: it doesn't have the "nmcli" package pre-instaled in ISO.

And I can't do "apt-get install network-manager" because, as you may guess I don't have network access :)

Is there a different way to setup a wifi from cli on dappnode (not via nmcli)?
Is there any commands for wifi setup in dappnode ubuntu image?

Should I reinstall the system or there is a more simple way to solve my problem?

If reinstall is only option - I recommend you to disable an ability to skip network setup step during installation, and update the installation manual (users should know that internet access in required diring installation process).
Another way - include "network-manager" package and "nmcli" util in the ISO image to make it accessible without network connection, just after install.

**Comment by uniconstructor** [comment]
I reinstalled system and realized that we have another problem: the installer don't provide an ability to setup wifi connection at all.
Here is my steps:
1) in installer on network setup step wait until auto-configuration fails (auto-config does not know my wifi SSID and password) and select "set up network connection manually".
2) enter computer name
3) enter username for new user (WTF? I just want to continue network setup! maybe network cannot be configured when no root user created? ok - I enter "dappnode")
4) enter, confirm password (done)
5) disk partition manager starts (hey! What about my network connection?)

Did I miss something? Maybe I should choose some extra options in setup menu?

I am using latest ISO release v 0.1.21.

**Comment by uniconstructor** [comment]
More info: because of wpasupplicant package is also not installed by default looks like you cannot set WPA connection credentials at all.

Anyway, here is a good guide for setting up WPA connection from console: http://www.pc-freak.net/blog/how-to-connect-to-wifi-network-using-console-or-terminal-on-gnu-linux/

**Comment by uniconstructor** [comment]
Another observation: if you install dappnode without network access, you will see a message after login "command 'docker' not found, use 'apt install docker-ce' to install package' (or something like that).

It looks strange: you should definitely use docker in your ISO. Now I think that installation process **requires** network connection - without it some important packages will not be installed, or, maybe some important scripts will not start.

Well, there is no other options left, I want finish it today, so I have to do some "hotfix" decisions.

**Comment by uniconstructor** [comment]
My hotfix: I connected my pc to router directly, and you know what?
**I see a different boot menu**.
I had only 30cm of network cable - so I have to do this the hard way:

![photo_2019-04-29_04-10-42](https://user-images.githubusercontent.com/1384545/56872735-fdc68400-6a34-11e9-8031-66430e0a659a.jpg)
![photo_2019-04-29_04-10-55](https://user-images.githubusercontent.com/1384545/56872736-fdc68400-6a34-11e9-8d93-287a93cfe283.jpg)

As you see, wireless drivers, WPA config tools, and network manager are really need to be pre-installed to avoid wiring schemes like this one :)

**Comment by uniconstructor** [comment]
Summary:
1) network connection is required during install process
2) offline installation from ISO image leads to broken system without any error messages
3) even if you have a wifi card - it doesn't help, because installer does not provide an ability to set up WPA2 connection
4) installation docs (or "troubleshooting" section) needs to be upated so users be aware of those pitfalls
5) "network-manager", "wpasupplicant" and maybe some other packages needs to be included in ISO to provide an ability of wireless setup
6) setup wizard needs to be updated: "network setup" section should have a "wifi connection setup" step or something similiar

Some final questions:
- I never created an ISO images - is there a standard way to auto-test a console installator like this one?
- why do I see a different boot menu when I booting up without network access? From witch step install wizard have an access to the WAN?
- original Ubuntu installer (gui-based) connects to wifi (WPA/WPA2) without any problem from version 14 (or earler). Can dappnode installer use the same functionality? What can be done to achieve this?

**Comment by dapplion** [comment]
Damn, @uniconstructor thank you for providing such valuable feedback! I'm linking @vdo to see if we can develop solutions to ease these situations.

**Comment by vdo** [comment]
Hi @uniconstructor , did you try our latest 0.2.x ISO? It should provide wireless connectivity for WPA2.
Even though, dappnode is intended to be connected via Ethernet, and the Wireless card to be used as a hotspot, but please try to setup your wireless card working with our latest, debian based ISO

**Comment by uniconstructor** [comment]
@vdo I am tryed an external USB adapter (Tenda U6) to set up wifi, but current version of official Linux 
U6 drivers cannot be build on DappNode Debian.

For now I connect my DAppNode via Ethernet.
When I connect DAppNode machine to the router I am have to deal with a NAT or have to set up a reserve proxy for some system services (for example Matrix Synapse server may need a special setup for this case).
I failed to set up VPN because of this (or maybe this caused by some other errors).

I am messed up with network configuration.

Can you explain some things about network configuration when using DAppNode host behind the router?

My questions are:
1) What apps or services are affected by the different types of connection ("direct connection to the Internet" vs "connection via router")? 
2) What ports should be opened in router to allow DAppNode operate normally behind this router? Can you provide a list of this ports and list of the DAppNode apps, using each port (incoming/outgoing, Protocol, etc.).
3) For question #1: if DAppNode needs a special config in order to continue to operate behind the router, what are those apps? What can I do with their config to make them work correctly behind the router?

**Comment by uniconstructor** [comment]
4. I use a Docker inside my DAppNode Debian. What IP adress should be set as "External" for Docker host?
1) DAppNode LAN IP-address should be an "external" for Docker host (example: 192.168.10.17)
2) Router WAN IP address should be "external" for Docker host (example: 85.111.93.1)

**Comment by uniconstructor** [comment]
UPD: Problem with wifi and drivers for wireless adapter is solved by switching to non-free Debian distribution, that contains all necessary 3rd party firmware by default.

Here is the more detailed description: https://superuser.com/questions/267282/how-to-use-non-free-drivers-during-debian-install
Debian images with pre-installed firmware: http://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/

Wireless connector just works after install, no additional actions needed. Magic.

**Comment by vdo** [comment]
Hi @uniconstructor I'm glad you solved this issue, let me know if you need more help
